### ISSUE TITLE
ueditor生成的百度音乐，放到页面上以后不能播放，403

### ISSUE THREAD

**Issue by whahuzhihao** [fex-team/ueditor#1015]
应该是百度音乐屏蔽了非法域名吧？有没有什么办法解决呢？

**Comment by whahuzhihao** [comment]
改了下代码 搞了个iframe嵌进去就可以了。 其实当时就解决了 今天想起来关一下

**Comment by poisonbian** [comment]
楼主的iframe是怎么实现的呢?能否分享一下~~

**Comment by whahuzhihao** [comment]
请参看我的这篇日志 [http://bewithyou.me/archive/detail/1](http://bewithyou.me/archive/detail/1)

**Comment by poisonbian** [comment]
非常感谢,已经可以使用了~
