### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by weelion** [fex-team/ueditor#1045]
API文档有误
http://ueditor.baidu.com/doc/#UE.ajax

request(URLString url, Object ajaxOptions) 方法 静态  1.2.6.1

示例
javascript代码：

     //向sayhello.php发起一个异步的Ajax GET请求, 请求超时时间为10s， 请求完成后执行相应的回调。
     UE.ajax.requeset( 'sayhello.php', {

应该是

     //向sayhello.php发起一个异步的Ajax GET请求, 请求超时时间为10s， 请求完成后执行相应的回调。
     UE.ajax.request( 'sayhello.php', {

request 写错了

下面的一个

request(Object ajaxOptions) 方法 静态  1.2.6.1
示例
javascript代码：

     //向sayhello.php发起一个异步的Ajax POST请求, 请求超时时间为5s， 请求完成后不执行任何回调。
     UE.ajax.requeset( 'sayhello.php', {

         //请求的地址， 该项是必须的。
         url: 'sayhello.php'

     } );

应该是

    UE.ajax.request({

         //请求的地址， 该项是必须的。
         url: 'sayhello.php'

     } );

应该是这样的吧

**Comment by Phinome** [comment]
对的，多谢反馈
