### ISSUE TITLE
关于编辑器支持WORD导入的问题

### ISSUE THREAD

**Issue by zbligang** [fex-team/ueditor#1091]
最新版本发布，编辑器可以支持导入WORD文档的，但下载下来的最新版本中，一直没找到WORD文档导入功能的入口，请问在哪儿呢？这个编辑器支持公式编辑器吗？类似于中学的代数或几何那样的公式，如果能编辑，编辑出来的在WORD文档中能识别出来吗？麻烦楼主以及技术帮忙解答一下，十分感谢！

**Comment by akene** [comment]
同问，现在表格贴进去容易错乱，但ckeditor就没有问题
