### ISSUE TITLE
ueditor对table的处理有问题，要使用ueditor处理表格的同学请警惕。

### ISSUE THREAD

**Issue by xuhong** [fex-team/ueditor#1131]
RT，这次被坑的厉害，重构公司的项目，鉴于ueditor在国内还是大受好评的，于是我花了一天多的时间把编辑器从ckeditor换到ueditor，结果发现被坑了，ueditor对表格的处理存在严重问题，截图如下：

![ueditor](https://cloud.githubusercontent.com/assets/1656327/3872124/9c2e5758-2110-11e4-864d-ea5fbc667d02.png)

而是用ckeditor则样式正常：

![ckeditor](https://cloud.githubusercontent.com/assets/1656327/3872140/319f5652-2111-11e4-91c8-83ff2db23aec.png)

是用的HTML都是来自[a-simple-responsive-html-email](http://tutsplus.github.io/a-simple-responsive-html-email/HTML/index.html)

希望ueditor团队能够完善uedior！
![bye](http://img1.wikia.nocookie.net/__cb20101010081641/sims/images/e/e2/Bye.gif)

**Comment by think2011** [comment]
坑死人了！！
