### ISSUE TITLE
问下ueditor官方：你们是怎样压缩JS的？我试了几个工具压缩的体积都没有你们官方的好。

### ISSUE THREAD

**Issue by tellyou666** [fex-team/ueditor#1372]
问下ueditor官方：你们是怎样压缩JS的？

我试了几个工具压缩的体积都没有你们官方的好，害我折腾了几个晚上。

我修改过ueditor.all.js里面的代码，理论上压缩后，不会比官方的ueditor.all.min.js大多少，但我实际上压缩后的代码比官方ueditor.all.min.js大200多K。

有没有比较好用的压缩工具呀？？？？

**Comment by ImYoursH** [comment]
你是怎么压缩的？求助，我现在也是改了ueditor.all.js    不知道该怎么压缩成ueditor.all.min.js，是有保留哪些关键字么？

**Comment by tellyou666** [comment]
yahoo压缩 应该是YUI composer什么的，你搜索一下。不过可以告诉你，插入图片时有bug，title还是alt来着，忘记了。已经放弃ueditor了。它的底层兼容性不是很好。

**Comment by ImYoursH** [comment]
嗯？我是用npm && grunt压缩的，完美兼容，插入图片木有问题。。不过还是谢谢了

**Comment by tellyou666** [comment]
你这个压缩体积会比较的大。
