### ISSUE TITLE
bootstarp模版中使用ueditor

### ISSUE THREAD

**Issue by zhangweissya** [fex-team/ueditor#1437]
bootstarp模版中使用ueditor，报错Uncaught TypeError: Cannot read property 'offsetWidth' of null 
不能使用！请问这个怎么解决···

**Comment by 3xxx** [comment]
var ue2 = UE.getEditor('editor_photo');
页面中没有这个editor_photo就会出现这个错误。

**Comment by Phinome** [comment]
具体要看报错信息，最好提供详细的报错信息。
