### ISSUE TITLE
ASP版1.4.3 server 2003 IIS6下一切正常 server 2008 IIS7 上传图片提示下载controller.asp

### ISSUE THREAD

**Issue by iceherald** [fex-team/ueditor#1451]
因为必须要更换服务器
只有Server 2008 IIS 7可以选择
以前在IIS 6下一切都正常

IIS7下已经按照说明文档进行过权限设置
上传目录也设置过用户写入权限
在服务器的浏览器上使用时可以上传图片
但是客户端的就上传不了图片，上传附件正常

ie 9会提示下载controller.asp 
打开后是如下内容
-------------------------------------
{
    "url": "../../post_upload/image/20141008/14127790462864759.jpg",
    "original": "C:\\Users\\Administrator\\Desktop\\上传暂存\\L1000800[1].jpg",
    "state": "SUCCESS",
    "title": "C:\\Users\\Administrator\\Desktop\\上传暂存\\L1000800[1].jpg"
}
-------------------------------------
此时图片其实已经上传到指定文件夹，但是编辑器不会显示出来

用遨游的浏览器（两个内核模式都试过），上传图片不成功，服务器上也不存在上传的文件，编辑器无反应

这个问题我在做本地测试（win7 IIS7）的时候就出现过，当时没多想，上传到服务器（server 2003 IIS 6）后发现功能一切正常，也就没管了。

现在换了新服务器，问题出现，找了论坛里面的方法也没解决，请帮帮忙，看看是什么回事
谢谢~

**Comment by fengzhidalu** [comment]
我的也提示让下载controller.asp，我用的是阿里云万网的空间。

路径是配置正确的，不知道是什么原因！
