### ISSUE TITLE
uparse给个样列啊，菜鸟看不懂你们的文档

### ISSUE THREAD

**Issue by merlin02306** [fex-team/ueditor#1481]
给点代码看看吧，都不知道咋用。（JS没精力学）
做了个简单的新闻发布系统，现在死在编辑器上了，WORD复制的表格，不是消失，IE9下就是错乱，疯了啊！

**Comment by 3xxx** [comment]
怎么解决？

**Comment by merlin02306** [comment]
已删，换ckeditor和kcfinder了
