### ISSUE TITLE
ue中enter换行的代码处理在哪里?

### ISSUE THREAD

**Issue by ryanfor** [fex-team/ueditor#1533]
我想监听按键以达到可以使用enter换行,以及切换成ctrl+enter换行.

**Comment by hendiko** [comment]
@Jinqn 使用 `editor.on('keydown', callback)` 无法阻止 Enter 键换行啊，因为它在我的 callback 之前已经完成了换行，所以怎么才能阻止原生 Enter 换行呢？

**Comment by Phinome** [comment]
在 dom 上监听 `keydown` 事件，然后在事件回调里处理。`e.preventDefault()` 即可取消事件的默认行为。[event.preventDefault](https://developer.mozilla.org/zh-CN/docs/Web/API/Event/preventDefault) 多查查 JS

**Comment by hendiko** [comment]
@Phinome 在 plugins/enterkey.js 中，作者已经先行绑定了 keyup 和 keydown 事件。于是无论我如何监听 keyup 和 keydown 事件，我的回调总是在作者的回调之后，这也导致我无法通过 e.preventDefault() 来阻止作者的 keyup 和 keydown 事件。

**Comment by hendiko** [comment]
@Phinome 好吧，刚发表上一则评论，我就在源码中找到了解决方法。

在 enterkey.js 中，监听 keydown 事件代码如下：
```
...
    me.addListener('keydown', function(type, evt) {
        var keyCode = evt.keyCode || evt.which;
        if (keyCode == 13) {//回车
            if(me.fireEvent('beforeenterkeydown')){
                domUtils.preventDefault(evt);
                return;
            }
...
```

因此在我的代码中增加一个事件绑定：

```
ueditor.on('beforeenterkeydown', function (){return true;});
```

让回调函数执行结果永远都为 `true`，则可以从作者先绑定的 `keydown` 事件中 `return` 出来。

而且，发现 `beforeenterkeydown` 事件只在 keydown.js 中被使用过，因此不用担心其他的副作用。
