### ISSUE TITLE
图片复制粘贴不支持--》从word里面复制数学公式

### ISSUE THREAD

**Issue by shenqiboy** [fex-team/ueditor#1619]
图片复制粘贴不支持--》从word里面复制数学公式
这个问题可以支持么？

![image](https://cloud.githubusercontent.com/assets/7145259/5066682/87f31bb6-6e72-11e4-964d-8293e0800cd6.png)

<p>
    <br/>好的：<img src="/ueditor/net/upload/image/20141117/6355183654986575992489886.png" title="blob.png" alt="blob.png"/>
</p>
<p>
    <br/>
</p>
<p>
    word里面复制：<span style="font-size:14px;font-family:&#39;Calibri&#39;,&#39;sans-serif&#39;"><img width="265" height="31" src="http://localhost:7957/themes/default/images/spacer.gif" word_img="file:///C:\Users\ADMINI~1\AppData\Local\Temp\msohtmlclip1\01\clip_image002.png" style="background:url(http://localhost:7957/themes/default/images/word.gif) no-repeat center center;border:1px solid #ddd"/></span>
</p>

**Comment by 472630126** [comment]
这个word里面复制公式的问题解决了吗。求带

**Comment by 472630126** [comment]
这个word里面复制公式的问题解决了吗。求带

**Comment by 472630126** [comment]
这个word里面复制公式的问题解决了吗。求带
