### ISSUE TITLE
放弃ueditor

### ISSUE THREAD

**Issue by kill2002** [fex-team/ueditor#1677]
[1.4.3 Asp 版本] UTF-8版
[1.4.3 Asp 版本] GBK版
以上版本，都下载了，花费了近两天时间在“Win 7 + IE 9 + 360安全浏览器7”中进行设置和调试，最后得出结论：浪费时间！

单是上传单张图片都需要寻找并解决那么多问题，更何况多图上传、附件上传、视频上传等其他上传功能。拿来了不仅不能直接使用，还要增加我的时间开销和精神负担。

一个半成品，一个未经严格测试的产品。

对不起，我要考虑开发一个网站的工期，我要把解决ueditor诸多Bug的时间置换成开发网站的时间、置换成网站开发的提成，没工夫去挑战你们ueditor团队设置的难关。注册这个帐号并发言，为的就是让你们知道一个ueditor用户的痛苦。

社会或因你们提供的便利而进步，或因你们设置的难关而止步。

附上其他ueditor用户的诉苦之言：

《百度团队，请尊重自己的品牌，你们是一流团队整的像个大学生作品漏洞错误百出》
https://github.com/fex-team/ueditor/issues/390

《ueditor 1.4.3 gbk asp 上传中文乱码 终极解决方法 ie6 ie8 也适用》
http://blog.163.com/fan_yishan/blog/static/47692213201492823543358/

**Comment by 3xxx** [comment]
确实难度不小，我以为只有我这个外行觉得难呢。
