### ISSUE TITLE
图片上传的后台规范问题

### ISSUE THREAD

**Issue by handsomeDDG** [fex-team/ueditor#1699]
我们这边是单独域名的图片服务器，需要将文件上传到图片服务器上，所以需要单独实现后台接受图片的程序，但是官方的api文档说的不是特别清楚，能不能有一份完整的规范，说清楚需要实现哪几个url连接，配置的，展示图片的，接受图片的等等，以及每个字段的意思，感激不尽，如开发完成，愿意开放所有代码

**Comment by wyzfzu** [comment]
@handsomeDDG  能否给一份后端实现的代码，谢谢~

**Comment by dlwin888** [comment]
@handsomeDDG
同求后端实现的代码，多谢~
