### ISSUE TITLE
requirejs共同引用会报错误

### ISSUE THREAD

**Issue by showzhi** [fex-team/ueditor#1714]
如题，当跟requirejs共同使用时，打开firebug会看到错误信息
ReferenceError: ZeroClipboard is not defined
	

...register("copy",function(){function d(){ZeroClipboard.config({debug:!1,swfPath:c...

**Comment by zhang421755327** [comment]
给力啊，就用这种人肉方法

**Comment by sm0king** [comment]
可是在最后一段代码里
有这样一段代码啊。
if (typeof define === "function" && define.amd) {
    define(function() {
      return ZeroClipboard;
    });
  } else if (typeof module === "object" && module && typeof module.exports === "object" && module.exports) {
    module.exports = ZeroClipboard;
  } else {
    window.ZeroClipboard = ZeroClipboard;
  }
