### ISSUE TITLE
UEditor在插入图片并成功显示后，复制一段文字加在图片后图片不能显示

### ISSUE THREAD

**Issue by LucenePT** [fex-team/ueditor#1811]
对比了以下添加复制文字前后的html代码，发现添加复制的文字后图片的名称变成了一张不存在的图片名称，请问这个怎么解决？

**Comment by 449684471** [comment]
没遇到这个问题啊，我试过，很正常！你是不是在粘贴的时候是将图片选中了？

**Comment by LucenePT** [comment]
我在Windows系统下上传图片是正常的，执行我的操作没有问题。但是把项目拿到Linux系统下，再执行问题操作图片src的图片名就莫名的变化了，是不是Linux下UEditor图片上传的路径有什么特别要注意的？

**Comment by saulRoy** [comment]
碰到了同样的问题，在开发服务器可以，放在线上服务器就不行，两遍的配置一样，楼主解决了吗？求教。
