### ISSUE TITLE
用编辑器发表文章，删除后怎么自动删除里面的图片？

### ISSUE THREAD

**Issue by qf19910623** [fex-team/ueditor#1860]
就是使用ueditor发表了文章，里面有图片、视频这些文件，当删除文章后，怎么自动删除文件？一直没找到完美的解决办法

**Comment by qiuqiuqiu** [comment]
同求

**Comment by a329692195** [comment]
同求

**Comment by 3xxx** [comment]
1、ue中上传图片的同时，可以将图片地址写入数据库，但，此刻，这个文章id还没产生，这个是难点。
2、删除文章时，根据文章id，找到数据库中的图片地址，删除。
3、编辑这个文章时，删除里面部分图片，此时如何删除图片文件呢？
综上，一个也做不到。

**Comment by 3xxx** [comment]
http://bbs.co188.com/
感觉这个论坛对于图片的处理很完美。
