### ISSUE TITLE
无法用visual studio community 2013打开 [1.4.3 .net版本]的源代码

### ISSUE THREAD

**Issue by YinQichao** [fex-team/ueditor#1865]
无法用visual studio community2013打开上述版本中的 net/net.sln 这个项目的解决方案的文件，会提示错误报告，错误报告内容是“http://localhost:7957 : error  : 打开 Web http://localhost:7957 时出错。无法找到网站“http://localhost:7957”。”

这是怎么回事，怎么解决

**Comment by ychaos** [comment]
直接close 哈哈
