### ISSUE TITLE
asp版我在桌面上建立目录可是无法上传图片

### ISSUE THREAD

**Issue by zhai-conan** [fex-team/ueditor#1899]
asp版我在桌面上建立目录可是无法上传图片，然后换到其他不是c盘的就可以了。

**Comment by yyposs** [comment]
找到了一个解决方法，你可以参考一下：
http://www.hiclk.com/2015/03/20/ueditoruploadimageerror/

**Comment by zhai-conan** [comment]
谢谢啦！
我试了，第三种办法是管用的，替换代码后上传到服务器图片上传就好了。前两种方法貌似不管用。
