### ISSUE TITLE
jsp 上传失败

### ISSUE THREAD

**Issue by zx159753zx** [fex-team/ueditor#1900]
我单独写了一个项目是可以的，但是我用在struts2中后台上传图片直接包一个未找到的错误
java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.getTempDirectory()Ljava/io/File;
该怎么弄
，急急急

**Comment by leongfeng** [comment]
包没导么~~~

**Comment by zpch111** [comment]
jar包冲突，里面肯定有个低版本的io包
