### ISSUE TITLE
百度真的很牛

### ISSUE THREAD

**Issue by kanglj** [fex-team/ueditor#1912]
百度真的很牛呀，说是开源的，但是对大家提的问题一直不问不顾，置之不理。作为一个开发人员，我真的很理解开发人员任务重、时间紧，但百度真么大公司，对广大用户最起码应该有个基本的态度吧。可悲！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by xinghailong** [comment]
有功夫抱怨，还不如找找折中的解决办法，或者提升js的技术
