### ISSUE TITLE
复制word里面的公式问题

### ISSUE THREAD

**Issue by shenqiboy** [fex-team/ueditor#1926]
复制word里面公式，会生成file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image002.png
本地路径图片，js没有访问权限，问一下有办法解决该问题么，有人写过类似插件么

    <span style="font-size:14px;font-family:&#39;Calibri&#39;,&#39;sans-serif&#39;"><img width="124" height="36" src="http://ueditor.baidu.com/ueditor/themes/default/images/spacer.gif" word_img="file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image002.png" style="background:url(http://ueditor.baidu.com/ueditor/themes/default/images/word.gif) no-repeat center center;border:1px solid #ddd"/></span>

**Comment by shenqiboy** [comment]
顶

**Comment by xml4cn** [comment]
最近几天在研究这个问题，基本上搞清楚了。 word的公式在复制时会存3种格式到剪切板，如下：
![clipboard](https://cloud.githubusercontent.com/assets/7858455/20336578/345f04b4-ac06-11e6-97e9-bab9956e889c.png)
**text/plain：**
(x+a)^n=∑_(k=0)^n▒〖(n¦k) x^k a^(n-k) 〗           （utn28规范）
**text/html：**
一个完整的页面，其中有用的是最后的内容，在粘贴时才会临时生成本地图片，复制时没有。
`
< img width=160 height=62 src="file:///C:/Users/administrator/AppData/Local/Temp/msohtmlclip1/01/clip_image002.png" >
`
**text/rtf：**
`{\rtf1\adeflang1025\ansi\ansicpg936\uc2\adeff31507\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi31507\deflang1033\deflangfe2052\themelang1033\themelangfe2052\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;} 。。。很多内容
`

要解决这个问题，text/html取本地文件不现实。所以只能用第一种格式，解析utn28表达式，并转成图片或者转成LaTex格式。ueditor自带的公式插件是支持LaTex的。 本来想找找有没有人做utn28转图片的实现，google了一下没什么资料。很郁闷啊！！！

**Comment by xml4cn** [comment]
@Phinome  有没有好用的开源库，可以直接把utn28转为LaTex或者图片？ [  utn28规范地址](http://unicode.org/notes/tn28/)
