### ISSUE TITLE
能不能写一个单独调用某个工具按钮的列子；为了表示感谢，已赞助100。

### ISSUE THREAD

**Issue by imsole** [fex-team/ueditor#1935]
像百度贴吧、微博、QQ空间那种，这个我不用多说，你们应该懂。
单独调用某个按钮：比如：上传图片、插入表情、插入音乐 等；编辑器可能在一个div里面，工具在另一个div里面。
希望能得到贵公司的解答。非常感谢。

**Comment by softworm** [comment]
<script type="text/javascript">

    (function (exports) {

        /*fields*/

        var ue = null,

            UEDITOR_HOME_URL = "/Scripts/ueditor/",

            options = {

                imageUrl: "/Common/ImageUp/AssetBuyFile",

                imagePath: "/Upload/Images/AssetBuyFile/",

 

                initialFrameWidth: 0,

                initialFrameHeight: 0,

 

                zIndex: 2,

                focus: false

            },

            ue_dlg = null;

 

        /*init*/

        $(document).ready(function () {

            /*init page*/

            ue = UE.getEditor('editor', options);

            ue.ready(function () {

                ue.setDisabled();

                ue.hide();

                ue.addListener('beforeInsertImage', ue_insert_img);

                ue_dlg = ue.getDialog("insertimage");

                ue_dlg.render();

            });

        });

        /*event handlers*/

        function upload_btn_click() {

            img_target = $(this);

            ue_dlg.open();

        }

        function ue_insert_img(evt, imgs) {

            var html = [];

            for (var i = 0; ci = imgs[i++]; ) {

                str = '<img width="30" height="30" class="file_img" src="' + ci.src + '" />';

                html.push(str);

            }

        }

        /*utitly*/

 

        exports.UEDITOR_HOME_URL = UEDITOR_HOME_URL;

    })(window);

**Comment by imsole** [comment]
非常感谢！已收到。

**Comment by qq645381995** [comment]
哪里写了？？

**Comment by yl1998** [comment]
可以发一份给我吗？谢谢QQ:46484089
