### ISSUE TITLE
修改了serverUrl，使用自己定义的后台上传服务（不使用ActionEnter），但是如何返回结果与UEditor进行友好交互呢？

### ISSUE THREAD

**Issue by suifengfengye** [fex-team/ueditor#1958]
查看UEditor之类的文档，都没有看到有这方面说明。说实在话，很多项目都需要根据实际情况定制化富文本web编辑器，提供的ActionEnter至多就是提供个参考，没有实在的意义，为什么不把上传的返回结果和UEditor的js的交互来个说明呢？

**Comment by nuanyang5917** [comment]
我也遇到了同样的问题，同求这个问题的解决方法

**Comment by cdefg198** [comment]
我去，我现在也遇到这个问题了，我是传到Azure上，不是服务器目录下，根本就没法用啊

**Comment by FredLliao** [comment]
同样的问题，自己有单独的图片上传借口，怎么和UEditor整合图片上传啊？

**Comment by cdefg198** [comment]
我已经搞定了，我上传图片是在一个域名下，不过查看的时候是另外一个域名。

**Comment by nuanyang5917** [comment]
贴一下代码呗，另一个域名怎么配？

**Comment by kevgithub** [comment]
直接修改编辑器代码，加了一个独立的按钮，完全放弃ueditor自己的上传功能，ueditor这块确实做的不合适
