### ISSUE TITLE
请问如何用用户ID做上传图片的路径？

### ISSUE THREAD

**Issue by shapache** [fex-team/ueditor#1972]
ueditor默认的是用日期作图片的路径，想在路径中添加用户ID这一项，这样删除某用户的图片就比较方便，如下代码所示的/{userID} 处，应该怎么写？谢谢啦
 
"imagePathFormat": "ueditor/jsp/upload/image/{userID}/{yyyy}{mm}{dd}/{time}{rand:6}", /* 上传保存路径,可以自定义保存路径和文件名格式 */

**Comment by xinghailong** [comment]
用什么模板引擎？在页面上定义一个js变量赋值成ID，然后把这个变量放到路径里
