### ISSUE TITLE
Ueditor 1.4.3预览框  不能设置成 编辑框的初始大小吗？

### ISSUE THREAD

**Issue by lihuikai** [fex-team/ueditor#1975]
Ueditor 1.4.3预览框  不能设置成 编辑框的初始大小吗？
现在的预览框效果是铺满整个窗口,
想要的效果 编辑框初始化多宽，预览窗口就多宽，高度无所谓

**Comment by atxkm** [comment]
@lihuikai 预览框大小最后怎么解决啊
