### ISSUE TITLE
如何让UEditor自适应屏幕的宽度

### ISSUE THREAD

**Issue by SimonWang2014** [fex-team/ueditor#1983]
我的网页中用了Bootstrap，我把ueditor放在bootstrap的栅格中不能自适应，怎么解决？

**Comment by focusqfb** [comment]
解决了吗？

**Comment by SimonWang2014** [comment]
解决了，修改‘ueditor.config.js’文件
```javascript
initialFrameWidth:'100%'
```
这样就可以了，默认是1000

**Comment by focusqfb** [comment]
哦，谢啦。。我刚用UEditor。。我网页用的是foundation，和bootstrap的栅格是一样的

**Comment by SimonWang2014** [comment]
我也刚用，bootstrap也刚学习   :)

**Comment by cxw2014** [comment]
为什么我改为100%就不行呢，你们用的哪个版本
