### ISSUE TITLE
jsp版 多图上传功能严重bug

### ISSUE THREAD

**Issue by chenTest2013** [fex-team/ueditor#1987]
多图上传 的在线管理任选一种浮动方式后，再打开多图上传，直接在插入图片选项卡的地址中显示真实地址

**Comment by tianmingXYXX** [comment]
可以使用的
你修改"imageUrlPrefix": "http://localhost:8081/JiHua/", /* 图片访问路径前缀 ================ 项目部署时候需要修改====================================== */
    "imagePathFormat": "/ueditor/jsp/upload/image/{yyyy}{mm}{dd}/{time}{rand:6}", /* 上传保存路径,可以自定义保存路径和文件名格式 */
这里就可以
我前两天和你遇到一样的问题
还有看看有没有被拦截器拦截
主要是看路径
