### ISSUE TITLE
UEditor 公式插件 Demo如何导入与添加图标？

### ISSUE THREAD

**Issue by wuliok** [fex-team/ueditor#1990]
想询问“UEditor 公式插件 Demo如何导入与添加图标？。麻烦具体说下：
1.如何在编辑器页面引入js文件？即在哪个文件里，代码加到何处等。
2.如何在工具栏增加 kityformula 图标.具体同上.
菜鸟询问,请给点耐心.特感谢!!

**Comment by zhangbobell** [comment]
可参考http://ueditor.baidu.com/website/kityformula.html

**Comment by wuliok** [comment]
谢谢！文中所说，本人基本不懂代码。您提供的网页看过好几篇，就是看不明白。
