### ISSUE TITLE
Umeditor  图片上传bug

### ISSUE THREAD

**Issue by pengliang159** [fex-team/ueditor#2016]
umeditor.1.2.2 中 图片上传  使用iframe  请求，209行
 $('<iframe name="up"  style="display: none"></iframe>').insertBefore(me.dialog).on('load', function(){
                    var r = this.contentWindow.document.body.innerHTML;
中如果获取HTML的话，数据是被一个 &lt;pre>&lt;/pre>的标签包住的，会导致 189行的
 var json = eval('('+r+')');  代码错误，导致显示上传失败。希望能更正过来。

**Comment by chace5** [comment]
服务器返回改成text/html;charset=utf-8就可以了，text/html格式返回不带pre标签
