### ISSUE TITLE
ueditor不打算更新了吗？

### ISSUE THREAD

**Issue by seosend** [fex-team/ueditor#2027]
ueditor不打算更新了吗？
ueditor不打算更新了吗？
ueditor不打算更新了吗？

全国各省开票网址大全，持续更新，敬请关注！！！！http://www.bzjst.com/reference/kaipiaowangzhi.html

**Comment by qiuqiuqiu** [comment]
求更新。。！！！！

**Comment by Gotoff** [comment]
太赞了，比CKEditor好用！
