### ISSUE TITLE
视频功能问题，添加优酷视频，视频加载不出来

### ISSUE THREAD

**Issue by yujiaqi** [fex-team/ueditor#2040]
视频功能问题，添加优酷视频，视频显示不出来，请问支持什么样子的视频网址格式？
用的视频链接http://v.youku.com/v_show/id_XOTUwODQ2NTY0.html?from=y1.3-idx-uhome-1519-20887.205905.3-1.1-8-1-3-0

**Comment by gaibian0823** [comment]
你的本地视频可以吗？

**Comment by yujiaqi** [comment]
没有尝试本地视频上传
即使是在线视频，有的也不能显示，好像过滤规则有问题
