### ISSUE TITLE
上传大文件出现http请求错误

### ISSUE THREAD

**Issue by tangccy** [fex-team/ueditor#2056]
php版本，上传大文件出现http请求错误。本地上传没问题，上线后则出现该问题

**Comment by annsshadow** [comment]
同遇到该问题，求指教。

**Comment by tangccy** [comment]
如果你是nginx服务器的话，除了配置php的上传大小限制，线程时间，服务器内存之外，还要配置一个client_max_body_size这个参数，这个参数很重要，小了的话，大文件传不了，才会报http请求错误，或者报找不到上传文件。你检查一些是不是小文件可以，大文件却不可以呢？如果是的话，有很大可能是我说的这种情况。
