### ISSUE TITLE
ueditor1.4.3 工具栏 “首行缩进”功能，不能每段都缩进吗？测试了只有第一段才能缩进。

### ISSUE THREAD

**Issue by Rubility** [fex-team/ueditor#2072]
ueditor1.4.3 工具栏 “首行缩进”功能，不能每段都缩进吗？测试了只有第一段才能缩进。

**Comment by SimonWang2014** [comment]
可以啊

**Comment by tongwei0071** [comment]
这个是操作段落的，一段的首行缩进，具体参见小学语文课文

**Comment by Rubility** [comment]
@tongwei0071 ，抱歉，表达有误，是指段落，已修改提问。
![qe1](https://cloud.githubusercontent.com/assets/12785045/8051986/41ffffaa-0eb5-11e5-93ba-be1733453c99.png) 在应用首行缩进后，只有第一段应用了CSS首行空2em的代码，其他没有。

**Comment by Rubility** [comment]
@SimonWang2014 ，我在IE11和CHROME浏览器上测试，均出现只有第一段缩进的问题，不知何故。

**Comment by Rubility** [comment]
找到问题了。由于我修改了autotypeset中removeEmptyNode，将其设置为了true，同时设置了 indent: true,indentValue : '2em',   则会出现上述问题。将removeEmptyNode注释掉，则OK了。
