### ISSUE TITLE
UEditor都有哪些事件？

### ISSUE THREAD

**Issue by yishou** [fex-team/ueditor#2076]
addListener(String types, Function fn)
API文档中却没有列出支持的types有哪些

其实我只是想在上传图片插入时，给图片加个max-width:100%样式，却没找到相关事件

**Comment by SimonWang2014** [comment]
请问你的上传图片是怎么做的？

**Comment by qiaocuixinzhiweini** [comment]
同问，怎么能监听到toolbar按钮的事件，我要改预览的默认样式。。。

**Comment by SimonWang2014** [comment]
ueditor 有一个execCommand这个方法

```
// 执行命令的通用接口
//该方法的第一个参数是需要执行的命令。剩下的可选的参数根据每个命令的不同而有一些差异， 具体//请参照相应的命令详情。
execCommand( String cmd, * params... )
```

它有很多可以执行的命令，我是这么使用的：

```
// 比如，撤销命令，直接在onclick()中传入execCommand命令，还自定义了font awesome 图标
<!--undo-->
<a id="undo" href="#" onclick="ue.execCommand('undo')"><span class="fa fa-undo"></span></a>
```

关于execCommand( String cmd, * params... ) ，你可以看这个http://ueditor.baidu.com/doc/#COMMAND.LIST
