### ISSUE TITLE
哥哥，基础函数都有bug啊……

### ISSUE THREAD

**Issue by icai** [fex-team/ueditor#2085]
`<div class="edui-box edui-label edui-menuitem-label edui-bootstrap">I,II,III...</div>`

	UE.dom.domUtils.hasClass($0, 'edui-menuitem')

---

	function hasClass(elem, className) {
	    return elem.className && (" " + elem.className + " ").indexOf(" " + className + " ") != -1;
	}

**Comment by sqqihao** [comment]
目测没有问题啊...

**Comment by icai** [comment]
@sqqihao 
https://github.com/fex-team/ueditor/blob/dev-1.5.0/_src/core/domUtils.js#L1696

edui-menuitem-label 
UE.dom.domUtils.hasClass($0, 'edui-menuitem')
---
new RegExp('\\b' + 'edui-menuitem' + '\\b','i').test('edui-menuitem-label ')
