### ISSUE TITLE
请问有没有办法，让上传服务器只允许指定IP可以访问。

### ISSUE THREAD

**Issue by magazine789** [fex-team/ueditor#2095]
1、ueditor在A服务器上。
2、后台php代码（接收上传的代码）在B服务器上。
3、B服务设置，仅允许A服务器的ip可以访问B服务器。
4、在任意一台非A和B的终端C上，打开A服务器上的ueditor，无法实现上传。
5、将终端C的ip，也放到B服务器的运行列表中后，终端C可以实现上传。

请问有没有办法，让B服务器只允许指定IP可以访问。

**Comment by Phinome** [comment]
百度或者 google 一下，你会得到答案
