### ISSUE TITLE
乱七八糟,不是为了表情,我才不用UE,和KIND比差远了.

### ISSUE THREAD

**Issue by cangtianweishang1** [fex-team/ueditor#2104]
你们说对不对. 
没用的东西真多, 浏览器上效果很差,就是功能比KIND多点,但水准和KIND差的不是一大截; 
还设置个z-index=900,为了通用性,每次都要改,你这是坑啊.手册写的太乱,  直接说几次AJAX, AJAX要求返回什么,返回的这些东西具体是干什么的就得了呗; 什么压缩,缩略,这管JS鸟事啊,我也是醉了.

浪费一下午,才基本研究明白. 就后台用用吧,前台绝对不用,不美观,兼容性差, 凌乱; 大多数程序员都是前台用KIND 后台用UE, 大家都懂;

**Comment by cboy868** [comment]
我也是这样认为  不知道为什么百度为啥弄一个这乱的东西 看着好头大呀

**Comment by cangtianweishang1** [comment]
就是配置多点, 关键好多在扰乱思维,.config.json, 无非就是附件上传,提前做个判定. 思想是不错;
但是: 那些垃圾配置就有点烦人,被其搞乱了.
