### ISSUE TITLE
多图上传图片顺序乱了

### ISSUE THREAD

**Issue by 545903195** [fex-team/ueditor#2107]
多图上传，上传之后图片顺序乱了，这个有没有什么好的方法处理？

**Comment by zhangshiqiu** [comment]
我这里修改了一下js，供大家参考，希望ueditor能改进这个问题：
vim dialogs/image/image.js

716 uploader.on('uploadSuccess', function (file, ret) {
717 var $file = $('#' + file.id);
718 try {
719 var responseText = (ret._raw || ret),
720 json = utils.str2json(responseText);
721 if (json.state == 'SUCCESS') {
722 _this.imageList[$file.index()] = json; // 按选择好的文件列表顺序存储
723 $file.append('');
724 } else {
725 $file.find('.error').text(json.state).show();
726 }
727 } catch (e) {
728 $file.find('.error').text(lang.errorServerUpload).show();
729 }
730 });
