### ISSUE TITLE
关于ajax直接调用Ue上传功能

### ISSUE THREAD

**Issue by popohum** [fex-team/ueditor#2126]
有些情况下，用户是不想创建编辑器的。比如直接上传一张图片，上传一个文件
又不想修改ue的核心代码。
有没有成功的例子。可以直接调用ue的文件上传接口？
不通过serverUrl。通过自己的url，在后台直接调用Controller文件

**Comment by Phinome** [comment]
https://github.com/fex-team/webuploader 如果只使用上传功能，推荐直接使用这个。ueditor 里上传也是用这个。
