### ISSUE TITLE
ueditor v 1.2.6.1  html粘贴进去会  把 span 标签 替换成很多 空格 &nbsp; 如何解决？ html粘贴的时候可以不动我的结构吗？

### ISSUE THREAD

**Issue by jennerluo822** [fex-team/ueditor#2129]
ueditor  version = "1.2.6.1"  
ueditor v 1.2.6.1  html粘贴进去会  把 span 标签 替换成很多 空格 &nbsp; 如何解决？ html粘贴的时候可以不动我的结构吗？

![Image](http://oil118.com/img/001.png)
![Image](http://oil118.com/img/003.png)

**Comment by fiture** [comment]
为什么直接就被关闭了。。。
