### ISSUE TITLE
ueditor 单页面应用中,渲染后的ueditor移除后再加载渲染失败

### ISSUE THREAD

**Issue by bu313** [fex-team/ueditor#2139]
请大神帮忙！！！
具体情况是这样的：单页面应用中，一个模块里面渲染了ueditor，加载另外一个模块时就将上面模块内容移除了，后来再切换到之前那个模块，再渲染ueditor，就没反应了。

**Comment by ziqidonglain** [comment]
我也遇到了这个问题,只有重新刷新整个网页,再打开子页面时才能加载Ueditor

**Comment by ziqidonglain** [comment]
刚刚研究了下,用如下代码可以解决这个问题,但不知道完美不,求指教.
var editor;
if(editor) {
	editor.destroy();
}
editor = UE.getEditor('content');

**Comment by bu313** [comment]
感谢楼上，能解决问题，完美不就等其他大神解答

**Comment by auslee** [comment]
吊 感谢上面的回答

**Comment by iacdingping** [comment]
可以使用 ue.render('content');  
但是不要重复render

**Comment by Phinome** [comment]
先按照 `destroy` 的方式，这个是个 bug ，离开后没有释放，不推荐使用 `render` 。后续会修复这个问题。
