### ISSUE TITLE
如何在toolbar中控制自定义插件的显隐

### ISSUE THREAD

**Issue by Double-Lv** [fex-team/ueditor#2149]
用registerUI方法自定义的插件，会自动出现在toolbar中。
我页面上有两个编辑器，一个想要自定义的插件，另一个不需在toolbar显示该插件，我分别初始化，但是toolbars参数中没写该插件，它还是会出现。
如何解决这个问题呢？

**Comment by herrdu** [comment]
upload_image

**Comment by herrdu** [comment]
这个问题没有解决直接关闭了吗？
