### ISSUE TITLE
图片上传窗口显示不完整

### ISSUE THREAD

**Issue by jifenkuaile** [fex-team/ueditor#2162]
在手机上使用ueditor时，如果分辨率为320*480，则在点击图片上传按钮后显示的窗口不完整，如图
![image](https://cloud.githubusercontent.com/assets/5698815/8771440/4a8a8e6a-2ef4-11e5-8bcf-28f8905f0078.png)
这种情况应该怎么解决？

**Comment by bmkj** [comment]
解决了吗？同问，解决了的话，麻烦Q我或给我个邮件：1163938946@qq.com

**Comment by Phinome** [comment]
目前没有适配手机，所以会有这个问题，后续会解决。
