### ISSUE TITLE
百度ueditor jsp版本 图片上传问题

### ISSUE THREAD

**Issue by qq370725567** [fex-team/ueditor#2163]
部署完后能用了,但是图片上传后 默认src地址是
<img src="/ueditor/jsp/upload/image......
   src    第一个带了/后图片就不显示了

我手动去掉/ 图片就显示了
求在哪里该源码能解决这个问题啊
或者说怎么修改图片保存路径

**Comment by cseryp** [comment]
http://blog.csdn.net/napoay/article/details/47414851

**Comment by Phinome** [comment]
http://fex.baidu.com/ueditor/#server-path 看看文档
