### ISSUE TITLE
Ueditor uParse功能Bug，生成了全局CSS: li，影响全局样式, 造成网页其它部分显示混乱,附图

### ISSUE THREAD

**Issue by greatworks** [fex-team/ueditor#2164]
Ueditor uParse功能Bug，生成了全局CSS：li，影响全局样式,造成网页其它部分显示混乱,如下图示：
![image](https://cloud.githubusercontent.com/assets/9072441/8793011/91a323f8-2fa2-11e5-8ed9-c441f21bb87e.png)

**Comment by lovepanda603** [comment]
我也遇到了，怎么解决啊？

**Comment by lovepanda603** [comment]
我也遇到了，怎么解决啊？

**Comment by greatworks** [comment]
Hi @lovepanda603 解决方法如下：
找到uParse生成的这段CSS的代码，然后把li的样式修改为局部样式。你可以直接修改你的ueditor.parse.js或者ueditor.parse.min.js方式如下：
1、ueditor.parse.js文件：查找【li{clear:both;}】，替换为【'+selector +' li{clear:both;}】；
2、ueditor.parse.min.js文件：同样查找【li{clear:both;}】，然后替换为【"+c+" li{clear:both;}】即可。
可参考如下截图，谢谢！祝你好运！
![a_](https://cloud.githubusercontent.com/assets/9072441/8827812/5086b37e-30c1-11e5-939a-d44050840f94.jpg)
