### ISSUE TITLE
怎么控制UEditor的输入

### ISSUE THREAD

**Issue by tlzzu** [fex-team/ueditor#2171]
比如我用Ueditor设置了一个元素<span> 规定其不能被修改或者删除，有没有接口去控制用户输入呐？还有关键词的输入，比如有些敏感的关键词，能否让用户不能输入呐？哪个接口可以实现（在不污染UE代码的情况下）？

**Comment by cipchk** [comment]
想要实时会不行，虽然我们可以监听 `contentchange` 事件，但是当我们强制调整HTML代码后势必还要再 `setcontent` 但此时又会触发 `contentchange` 事件，倒置循环调用。

1. 提交至服务端前过滤。
2. 污染UE代码，如果是这样子的话，那方法会很多。
