### ISSUE TITLE
有没有考虑把图片，视频，附件上传单独提取出来

### ISSUE THREAD

**Issue by whatlookingfor** [fex-team/ueditor#2191]
请问，有没有考虑把图片上传，视频上传，以及附件上传等功能单独提取出来呢？不通过文本编辑器也可以使用。
单独的上传功能没有必要提取出来，但是我觉得将上传功能与在线管理，在线搜索整合起来的功能挺好的，如果能通过某个JS单独调用的话，那就perfect了

**Comment by sdwljx** [comment]
对的，很多编辑器都有这功能 可以分离出单独的功能使用！

**Comment by Phinome** [comment]
https://github.com/fex-team/webuploader
