### ISSUE TITLE
ueditor在容器中无法宽度自适应

### ISSUE THREAD

**Issue by shuxingxingdehaizi** [fex-team/ueditor#2199]
准备把ueditor整合到项目中，但是发现了一个很棘手的问题：宽度无法自适应。
下载了ueditor1_4_3 JSP版本后，把里面的editor.jsp改为editor.html,并且把ueditor.config.js中的initialFrameWidth改为了'100%' , 这样直接用浏览器打开editor.html，编辑器是能自适应宽度的，会随着浏览器大小改变而改变。
但是把编辑器放到jboss容器中，使用如下代码引用（我把<>替换为了",不然在这里代码没法显示），ueditor.config.js文件同样做了相同的修改，访问该页面，宽度却没法自适应，改变浏览器大小，编辑器不会改变。（各种JS以及JSP引用路径正确），并且编辑器编辑区域无法编辑，鼠标移入不会变为竖线形状，编辑器上方功能菜单可以点击。
“div style="width:100%;height:500px;border:2px solid #F00;margin-left:auto;margin-right:auto;"“
test div
”div style="width:90%;height:400px;border:2px solid #F00;margin-left:auto;margin-right:auto;"“
	“jsp:include page="../../ueditor1_4_3/editor_include.jsp" flush="false"“
	“/jsp:include”
	“/div“
	“/div”

检查浏览器控制台，发现如下错误信息：
Get server config http error.
showErrorMsg()ueditor.all.js (第 8092 行)
msg = "Get server config http error."
UE.Editor.prototype.loadServerConfig/</<.onerror()ueditor.all.js (第 8083 行)
doAjax/xhr.onreadystatechange()ueditor.all.js (第 8220 行)
console && console.error(msg);

各位大神有遇到过类似情况的吗？应该怎么修改？

**Comment by shuxingxingdehaizi** [comment]
控制台JS报错的问题解决了 是因为jar包没有导入到jboss容器中，需要把ueditor1_4_3\jsp\lib下的东西拷贝到web-info/lib中，重启jboss.但是自适应的问题还是没有解决！求方法！

**Comment by shuxingxingdehaizi** [comment]
问题解决了   是自己大意了，如果需要编辑器自适应，编辑器外面所包的所有DIV（除最外层以外的） width属性都需要使用百分比设置。不能设置具体值。

**Comment by shuxingxingdehaizi** [comment]
但是编辑器无法输入文字的问题还没解决~~！

**Comment by shuxingxingdehaizi** [comment]
找到原因了，没法输入文字是因为文字输入区域宽度为0，
div id="edui1_iframeholder" class="edui-editor-iframeholder edui-default" style="width: 0px; height: 320px; z-index: 999; overflow: hidden;"
但是这个值在那里设置呢？哪位高人知道？

**Comment by shuxingxingdehaizi** [comment]
唉~~~懂了，这个网站完全没人看~~~~！宽度问题解决了，在var ue = UE.getEditor('editor');的时候传递一个宽度的参数就行：
var ue = UE.getEditor('editor',{initialFrameWidth: null});

**Comment by jacklaiu** [comment]
谁说没人看，我就遇到这个问题还有遇到你

**Comment by cxw2014** [comment]
我也遇到这个问题了
