### ISSUE TITLE
上传提示成功，但是找不到文件

### ISSUE THREAD

**Issue by qinghechaoge** [fex-team/ueditor#2200]
我上传图片遇到问题，请大家帮忙看看
http://localhost:8080/ueditor/jsp/controller.jsp?action=config&&noCache=1438758946592
这个是正常的，点击上传后，图片没有插入到文本编辑器，而是显示了图片名称，火狐控制台报错，说是找不到图片。
大家遇到过吗，怎么解决呢？

**Comment by annsshadow** [comment]
上传文件遇到同样问题了，同求

**Comment by qinghechaoge** [comment]
我这个解决了 是后台config里配置的问题
