### ISSUE TITLE
上传图片路径，自定义变量（从页面传过来的）？

### ISSUE THREAD

**Issue by fengzhiri** [fex-team/ueditor#2202]
上传图片路径，自定义变量，该变量是从页面上传来的变量。
比如：需要区分用户上传的图片，假设用变量username来区分，路径想变成http://127.0.0.1:8080/ueditor/{username}/{time}{rand:6}
请问username这个变量如何传递？？？

**Comment by shuxingxingdehaizi** [comment]
我现在还没找到1.4.3的附件上传在哪里能配置呢~~！网上查的都是上传图片的....

**Comment by Phinome** [comment]
http://fex.baidu.com/ueditor/#server-path

**Comment by shuxingxingdehaizi** [comment]
我想做的是吧文件提交给某个后台自定义的Action处理 而不是直接默认的传到某个服务器目录 能有配置的地方吗？

**Comment by shuxingxingdehaizi** [comment]
@Phinome  我想做的是吧文件提交给某个后台自定义的Action处理 而不是直接默认的传到某个服务器目录 能有配置的地方吗？

**Comment by Phinome** [comment]
http://fex.baidu.com/ueditor/#server-config

**Comment by ALEXFUNGZH** [comment]
自己写action的话就不是配置了，是二次开发了，建议你从jsp中提交的那个方法入手吧！

**Comment by ALEXFUNGZH** [comment]
http://m.blog.csdn.net/article/details?id=50482862这是我之前写的博客，你可以参考下
