### ISSUE TITLE
action参数名冲突

### ISSUE THREAD

**Issue by keepeye** [fex-team/ueditor#2211]
我用的是rails，action参数是保留值，不得不放弃ueditor了。

我想此问题不止一个框架遇到吧？

这个参数名能自定义吗？其实挺疑惑的，为什么要设计成这种单入口模式，每个功能单独配置url不好吗？

后端规范我想不应该由前端来定吧？

**Comment by dusu** [comment]
同问，但是我看到不少人在rails上用ueditor，甚至有做成gem的，看这意思应该是调整起来不太难，只怪自己太菜，还参不透。

**Comment by dusu** [comment]
http://fex.baidu.com/ueditor/#qa-customurl
