### ISSUE TITLE
怎样阻止setContent 触发contentChange 事件？

### ISSUE THREAD

**Issue by nilday** [fex-team/ueditor#2213]
var ue = UE.getEditor('editor');
ue.addListener("contentChange",formatInput);
							
function formatInput(){
	var text=ue.getPlainTxt();
	ue.setContent("<p>"+text+"</p>", false);
	UE.dom.domUtils.preventDefault(e);
}
							
ue.addListener("beforeSetContent",function (){
	ue.removeListener("contentChange",formatInput);
});
							
ue.addListener("afterSetContent",function (){
	ue.addListener("contentChange",formatInput);
});

我尝试在用户输入的同时格式化他们的输入内容（以上只是示例代码），当用户输入的同时我监听change事件，然后获取内容，修改后写回去。但是写回去的时候会再次触发contentChange事件。于是我写了以上的代码，但是并没有起作用。有没有办法阻止setContent触发contentChange事件？

**Comment by cipchk** [comment]
目测源代码没有此类开关，自己修改一个吧。
