### ISSUE TITLE
如何在设置请求的header？

### ISSUE THREAD

**Issue by Mavlarn** [fex-team/ueditor#2219]
我们的系统用的token的方式做用户验证，在发送每个请求的时候，要在request的header里面加一个token的信息。
我搜索了一下，有一个相关的问题，说是在images.js里面修改uploadBeforeSend 的方法，好像可以在这里往header里面添加请求。但是，我们的token是根据用户登录后服务器端给返回的信息，放在cookie里面临时保存，服务器端也只接收header里的token信息也做验证。

所以，有没有什么办法能在每次上传图片之前设置header呢？

谢谢。

**Comment by Mavlarn** [comment]
这个有什么解决办法吗？我们的系统的验证方式的token，token保存在header里面。

**Comment by Phinome** [comment]
http://fex.baidu.com/webuploader/doc/ 看看这个文档吧，ueditor 里的图片上传用的就是 webuploader
