### ISSUE TITLE
UEditor在模态框中的情况下，字体颜色选着框无法显示

### ISSUE THREAD

**Issue by Quesle** [fex-team/ueditor#2234]
我在页面上添加一个UEditor，给字体选择颜色，一切都能正常使用；
但是我将UEditor放到bootstrap的模态框中时，选择字体的颜色时，颜色选择框无法打开；
最后发现，颜色选择框显示在模态框的图层下面，而不是显示在模块框的图层上面，而看不到颜色选择框；
请问这有什么好的办法解决吗？

**Comment by xskill2015** [comment]
配置参数zIndex试试。 uEditor 使用了浮动的模式。这样带来一些小问题。例如。表单验证时，表单验证提示Tips 被编辑器档住。全屏也没有Body全屏。不知作者为何不解决这些的问题。

**Comment by Quesle** [comment]
非常感谢，问题已经解决了，确实是zindex的问题
