### ISSUE TITLE
只能通过id来实例化吗

### ISSUE THREAD

**Issue by mosejiang** [fex-team/ueditor#2240]

**Comment by Phinome** [comment]
```javascript
var ue = UE.getEditor('container', {
    autoHeight: false
});
```
是指这个初始化？如果是，那么 `container` 只能是元素 id。

**Comment by seancy** [comment]
如果使用dom元素来完成初始化呢，开发时能减少页面中id的冲突，因为我们是单页面程序。

**Comment by Phinome** [comment]
@seancy 不行，因为传入 `getEditor` 里的参数就是个单纯意义上的字符串作为`UEditor` 实例的 `key` ，只是它和 DOM 元素关联起来了。
