### ISSUE TITLE
请问ueditor现在有单独的图片，视频，附加上传工具吗？

### ISSUE THREAD

**Issue by wl7351391** [fex-team/ueditor#2246]
请问ueditor现在有单独的图片，视频，附件上传工具吗？就是说不掉用编辑器，只是调有js上传单个或多个图片的工具。虽然是基于ueditor但是页面上没有编辑器，就一个图片上传的按钮？

**Comment by rhtsjz** [comment]
http://fex.baidu.com/webuploader/
