### ISSUE TITLE
1.4.3 PHP版   上传视频 $_FILES 为NULL 找不到上传文件

### ISSUE THREAD

**Issue by a1141727** [fex-team/ueditor#2255]
1.4.3 PHP版   上传视频 $_FILES 为NULL 找不到上传文件

**Comment by annsshadow** [comment]
同遇到该问题，若解决了，求指教。

**Comment by Phinome** [comment]
看看文档 PHP 的配置：http://fex.baidu.com/ueditor/#server-php
