### ISSUE TITLE
建议jar包放到maven仓库里去

### ISSUE THREAD

**Issue by houzw** [fex-team/ueditor#2258]
如题，用maven管理多方便啊

**Comment by zhou7707** [comment]
我真的不想说建议个毛呀，就JAR包COPY多好，找不到的包我还能百度下，不知道祖国是多民族大家庭吗？不知道什么百度网盘很多地方都访问不了？不知道上GITHUB是要先内地找服务器做代理的？我用MAVEN九成可能下不来我要的东西
