### ISSUE TITLE
Ueditor (JSP版) 上传图片的时候 ，如何将图片存放在指定的磁盘上？？？？感谢指导！！！

### ISSUE THREAD

**Issue by tianweiqi** [fex-team/ueditor#2268]
1.UEDitor 图片上传的时候，如何将图片的路径指定到任意一个磁盘下？

**Comment by fengzhi71488** [comment]
Java版的需要改源码，我有改过的你要吗？

**Comment by tianweiqi** [comment]
您好，如果方便的话，还请帮忙提供一下，我现在系统用的是EASYUI+SPRING+MYBATIS，非常感谢！

**Comment by fengzhi71488** [comment]
有邮箱吗？ 我把我改了的发给你，你看看

**Comment by tianweiqi** [comment]
好的 ，谢谢。1085776063@qq.com; 方便加个QQ吗？

**Comment by ebert-chan** [comment]
我已经改了java源码，可以将文件存到指定磁盘目录下，但是，上传的文件默认是在服务器部署目录下，如何修改它的下载地址？

**Comment by wslpeter** [comment]
.net的同求

**Comment by fengzhi71488** [comment]
不会.net，不过可以告诉你思路去改。你去看源码里面，文件保存的路径获取的地方。修改下就可以了
----- 原始邮件 -----
发件人：王世磊 <notifications@github.com>
收件人：fex-team/ueditor <ueditor@noreply.github.com>
抄送人：fengzhi71488 <fengzhi714@sina.cn>
主题：Re:_[ueditor]_Ueditor_(JSP版)_上传图片的时候_，如何将图片存放在指定的磁盘上？？？？感谢指导！！！_(#2268)
日期：2015年10月15日 09点22分

.net的同求

&mdash;

**Comment by lvjing** [comment]
java源码求。。。。不会改图片上传那边的

**Comment by fengzhi71488** [comment]
邮箱
----- 原始邮件 -----
发件人：lvjing <notifications@github.com>
收件人：fex-team/ueditor <ueditor@noreply.github.com>
抄送人：fengzhi71488 <fengzhi714@sina.cn>,  Comment <comment@noreply.github.com>
主题：Re:_[fex-team/ueditor]_Ueditor_(JSP版)_上传图片的时候_，如何将图片存放在指定的磁盘上？？？？感谢指导！！！_(#2268)
日期：2016年04月28日 16点33分

java源码求。。。。不会改图片上传那边的

&mdash;
