### ISSUE TITLE
使用JSP 去搭建UEDitor 浏览器 报net::ERR_ACCESS_DENIED这个错误

### ISSUE THREAD

**Issue by JonkMing** [fex-team/ueditor#2273]
上传100KB一下的图片或者文件都没有问题， 但是只要大于100KB 就会报net::ERR_ACCESS_DENIED 这个错误。 求工程师解答一下。

**Comment by longchaoqun** [comment]
我刚刚也遇到这个问题，查了一上午，结果发现是公司监控软件的原因。设置了不能上传大文件，防止资料外泄。

**Comment by JonkMing** [comment]
我好像在本地调试也不可以，～～～
