### ISSUE TITLE
关于Ueditor 1.4.3 NET 版本图片在线管理的问题

### ISSUE THREAD

**Issue by freeksy** [fex-team/ueditor#2281]
图片管理效果还不错，就是排序方式不行，在.NET版本中都是从最初的开始读取，如果图片过多则找最近几天的很难找到，如果能按最新的来排列，对图片的管理非常好，至少可以减少重复上传图片。
哪位高手知道怎么改，不防告诉一下小弟。。。

**Comment by focusqfb** [comment]
是啊，我也纳闷，，，，你解决了吗
