### ISSUE TITLE
UEditor 上传图片action是否可以修改？

### ISSUE THREAD

**Issue by Gxbye** [fex-team/ueditor#2297]
UEditor中config.json里面默认配置的"imageActionName": "uploadimage"，值是 “uploadimage” 这个上传的action是否可以改成自己写的上传的方法？比如 "imageActionName": "projName/xx/kk/myUploadTools".

**Comment by MaMaFish** [comment]
同问~

**Comment by tangniyuqi** [comment]
可以啊
