### ISSUE TITLE
官网和github的ueditor源 我应该用哪个？

### ISSUE THREAD

**Issue by atmjs** [fex-team/ueditor#2313]
我的项目需要兼容IE6，我看git上貌似是1.5.0了，官网是1.4.3 
想知道生产环境应该用哪个版本去编译？求解答！

**Comment by soakit** [comment]
![image](https://cloud.githubusercontent.com/assets/11240668/10154806/8da732c0-669e-11e5-93a7-813617f9b4e3.png)

**Comment by atmjs** [comment]
嗯 现在用的是官网上的1.4.3.1 版本

**Comment by Phinome** [comment]
官网
