### ISSUE TITLE
go语言

### ISSUE THREAD

**Issue by GaryDai2013** [fex-team/ueditor#2317]
对于后端是go语言的开发，是否支持呢？

**Comment by xiangshouding** [comment]
后端代码应该不难实现吧，你都开始 Go 语言了，完全可以照抄 php 等的后端逻辑实现一套，并把它贡献出来。

**Comment by GaryDai2013** [comment]
好的，因为目前没有go的文档说明，我搭建个demo测试一下，谢谢。

**Comment by GaryDai2013** [comment]
可惜的是，ueditor无法响应式。

**Comment by Phinome** [comment]
暂时不支持，你可以自行修改
