### ISSUE TITLE
IE edge Permission Denied

### ISSUE THREAD

**Issue by Edota** [fex-team/ueditor#2318]
UE 在IE Edge 下不能使用呀

**Comment by Phinome** [comment]
什么版本？ 我的 windows 10 下能够正常使用。

**Comment by jun-luo-changsha** [comment]
UEditor 1.4.3.2  在spartan里面多次创建编辑器的时候就会报错 SCRIPT70: Permission denied

**Comment by Phinome** [comment]
找机会看看

**Comment by playermaker** [comment]
我也发现了这个问题，根本无法使用

**Comment by zikezi** [comment]
求问，UEditor 1.4.3.3版本 在 Edge上报错 SCRIPT70: Permission denied的bug有人解决么？求方案……
