### ISSUE TITLE
如何自定义按钮

### ISSUE THREAD

**Issue by phevose** [fex-team/ueditor#2319]
addCustomizeButton.js 中如何使用自己的按钮图片？

**Comment by LaughingMeMe** [comment]
我是在渲染文件的css中找到对应的css，直接给了背景图
.edui-for-dialogbuttondialog,.edui-for-dialogbuttondialog :hover {background:url(图片地址) ;	-webkit-background-size: contain;-moz-background-size: contain;background-size: contain;}
