### ISSUE TITLE
上传的图片，手机上显示时，超出屏幕，如何对应

### ISSUE THREAD

**Issue by liqi198591** [fex-team/ueditor#2321]
如题。
上传的图片，如果有文字和图片同时存在，会出现图片超出手机屏幕的问题，但文字可以自动换行。
是否可以让上传的图片，在手机上也能适应手机屏幕大小自动缩放。

**Comment by yanxiaochuan** [comment]
解决了没，同问

**Comment by terminatorheart** [comment]
这个只要在手机网页上使用max-width:100%来限定就可以了的

**Comment by liqi198591** [comment]
由于富文本中，自动的会加入max-width属性，外部增加该属性，可能不一定会起到效果。
最后通过判断屏幕宽度，动态调整图片宽度，解决该问题。

**Comment by terminatorheart** [comment]
@liqi198591 我使用了多次，并没有发现会自动添加max-width属性到富文本中的情况，你看看是不是有属性继承呢
