### ISSUE TITLE
自定义按钮

### ISSUE THREAD

**Issue by LaughingMeMe** [fex-team/ueditor#2330]
addCustomizeButton.js 中如何使用自己的按钮图片？

**Comment by Kingkongzmc** [comment]
按钮的图片一般是在“themes/default/images/icons.png”然后background-position: -500px 0;
就是获取那张图片上的500px 0px 这个坐标截取到的图片座位按钮图标，不想要他们的就要自己加图片

**Comment by LaughingMeMe** [comment]
ok，多谢楼上，我自定义按钮将position移到不可见的地方，然后在页面中给它加了个背景
