### ISSUE TITLE
TypeError: holder is null

### ISSUE THREAD

**Issue by paynepang** [fex-team/ueditor#2348]
哪位大神麻烦解释一下。
用的是jsp utf-8版本上传。
在调用过程使用spring mvc，自定义一个上传方法，修改了config.js的路径
![image](https://cloud.githubusercontent.com/assets/6223402/10600610/8094e018-773e-11e5-9c72-906959ec84bd.png)

![image](https://cloud.githubusercontent.com/assets/6223402/10600596/6c38d57a-773e-11e5-8be8-f2ff6cf8544e.png)

**Comment by OneNewLife** [comment]
请问你解决了么？ @paynepang
