### ISSUE TITLE
请问有没有形如：<textarea   id="elm1" class="uEditor"> </textarea>的使用方式？

### ISSUE THREAD

**Issue by ynioba** [fex-team/ueditor#2373]
很想从xheditor转过来，但是，看了技术手册，发现貌似没有这种使用方式，我们子系统有10来个，每套代码都要改，比较麻烦。。。

主要是有没有$("#elm1").text()这样的取值方法？？虽然textarea可以初始化！！

**Comment by cuihom** [comment]
var editor = new UE.ui.Editor();
editor.render("elm1");
保存提交时可以将编辑器内容放入textarea中：
$("#elm1").text(editor.getContent());
