### ISSUE TITLE
Word图片转存问题 Uncaught Error: Error: An invalid exception was thrown.

### ISSUE THREAD

**Issue by aichaoguy** [fex-team/ueditor#2377]
在将从Word中复制的图文粘贴至编辑框，随后点击“开始上传”时，发现tangram.js报错

word图片转存时，报JavaScript错误
```
Uncaught Error: Error: An invalid exception was thrown.
```

![image](https://cloud.githubusercontent.com/assets/11695765/10938670/fb23401e-8336-11e5-8c1a-97015a1c7d2b.png)

![image](https://cloud.githubusercontent.com/assets/11695765/10938656/e640b85c-8336-11e5-8c11-8e4d1383fb0d.png)

**Comment by aichaoguy** [comment]
通过修改config.json中的配置项"imageCompressEnable"，由false改为默认的true后，word图片转存功能正常了。

查错过程一波三折，发现自己的word图片转存不可用，就去翻官网的例子，仔细找与官网例子不同的地方，还比较了imageuploader.swf的md5值！最后没有办法，才将官网的所有配置一一覆盖，然后看配置有哪里不同。

提个建议：官方文档将配置项的意义交代清楚，谁知道这项关于“启用压缩”的配置会影响word图片上传？！

**Comment by xiaodongyuan177** [comment]
哥们你用的什么版本啊，我现在用ueditor1_4_3_2-utf8-jsp  根本就不能直接粘贴上传，蛋疼
