### ISSUE TITLE
怎么去掉多图上传里的“在线管理”？把其他用户上传的图完全暴露了啊

### ISSUE THREAD

**Issue by MukuroSama** [fex-team/ueditor#2387]
![qq 20151110083126](https://cloud.githubusercontent.com/assets/6258294/11050927/78075410-8785-11e5-8980-050ad769f933.png)

**Comment by MaMaFish** [comment]
image.html 直接注释掉就行了,eg:
 <div class="wrapper">
        <div id="tabhead" class="tabhead">
        
            <span class="tab focus" data-content-id="upload"><var id="lang_tab_upload"></var></span>
         
        </div>

**Comment by Phinome** [comment]
应该在后端做判断的，而不是前端编辑器来做，前端的方法是可以跳过的。
