### ISSUE TITLE
视频<video>, 音频<audio>

### ISSUE THREAD

**Issue by virtuecai** [fex-team/ueditor#239]
视频有指定视频网站地址, 也有上传生成<video>
但音频只有一个百度搜索, 应该也提供也提供一个音频上传.

期望视频与音频的功能中均有上传与插入文件地址链接, 生成视频<video>, 音频<audio>.功能.

**Comment by duxiaolong** [comment]
确实需要加一个可以上传本地音频文件的功能啊！
