### ISSUE TITLE
scaleEnabled设置为true之后 滚动条位置有问题 

### ISSUE THREAD

**Issue by zzq900503** [fex-team/ueditor#2394]
scaleEnabled设置为true之后 滚动条位置有问题，无论是否设置初始宽度，都会有一个默认的宽度值,导致滚动条位置不对。
![qq 20151113122910](https://cloud.githubusercontent.com/assets/15810569/11138844/95296ab8-8a02-11e5-8efb-0bdd9856275c.png)

**Comment by mjbin** [comment]
设置默认宽度为100%，然后最外围再用样式设置宽度大小。这样应该就可以拉伸不会有滚动条

**Comment by zzq900503** [comment]
thanks
