### ISSUE TITLE
老提示有两段JS错误，请问怎么回事

### ISSUE THREAD

**Issue by mabelp** [fex-team/ueditor#2398]
我直接输入地址是可以的：http://localhost:51472/Scripts/UEditor/net/controller.ashx
后台配置:var URL = "/Scripts/UEditor/";

1> Failed to load resource: the server responded with a status of 404 (Not Found)

http://localhost:51472/Scripts/UEditor//Scripts/UEditor?action=config&&noCache=1447586191175 

2> 请求后台配置项http错误，上传功能将不能正常使用！  ueditor.all.min.js:124 

![3](https://cloud.githubusercontent.com/assets/15152037/11168541/a122499e-8bcd-11e5-85ad-2684ebb10f25.png)

![4](https://cloud.githubusercontent.com/assets/15152037/11168555/7091248e-8bce-11e5-9ea3-cf3c0155a7b7.png)

**Comment by yelikang** [comment]
你的文件路径不对吧
![image](https://cloud.githubusercontent.com/assets/11992275/11371496/c4dada3a-9303-11e5-9ecb-61f2e048ab9b.png)
