### ISSUE TITLE
最近百度UMeditor编辑器插入地图的功能用不了，报错如下，是什么原因？

### ISSUE THREAD

**Issue by dreamapplehappy** [fex-team/ueditor#2400]
```
Uncaught TypeError: me.marker.setPoint is not a functionBMap.LocalSearch.onSearchComplete 
map.js:243 Uncaught TypeError: Cannot read property 'lng' of undefined
```

**Comment by shaosihaozi** [comment]
ueditor/dialogs/mapmap.js
第233行 point = widget.marker.P 获取对象未定义，将244和246行的涉及到point.lng和point.lat的地方注释掉就行了，只是不能标注marker了。
关于widget.marker这个对象未定义还在研究中。

**Comment by shaosihaozi** [comment]
OK了，
ueditor/dialogs/mapmap.js
第233行 point = widget.marker.P 改成point = widget.marker.point

**Comment by dreamapplehappy** [comment]
OK，我试试，谢谢啦。
