### ISSUE TITLE
1.4.3 jsp版 上传本地图片出现：后端配置项没有正常加载，上传插件不能正常使用

### ISSUE THREAD

**Issue by Gooooodman** [fex-team/ueditor#2413]
![Uploading QQ图片20151124200252.png…]()

百度搜不到jsp的版本，还请提供解决方案，谢谢。

**Comment by Phinome** [comment]
http://fex.baidu.com/ueditor/#server-jsp

**Comment by Gooooodman** [comment]
@Phinome 谢谢
