### ISSUE TITLE
UEditor初始化内容异常

### ISSUE THREAD

**Issue by 20915551** [fex-team/ueditor#2427]
从后台获取的内容为一段html字符串，其中有图片的标签和地址，给UEditor初始化的时候

<script type="text/javascript">
$(document).ready(function(){
    var content = $("#ditorDefault").val();
    var ue = UE.getEditor('editor');
    ue.addListener("ready", function () {
        ue.setContent(content,false);
    });
});
</script>

图片不能显示，而且内容部分在UEditor编辑器之外，求大神帮忙解答

**Comment by zhoubhin** [comment]
@20915551  借楼问一下，按照官网上的教程引入了相关JS文件，chrome运行调试时，提示UE.getEditor is not function，这个如何解决？
