### ISSUE TITLE
Firefox 43版本下 加粗标题 编辑器内部的滚动条会自动跳会顶部

### ISSUE THREAD

**Issue by kzwr** [fex-team/ueditor#2429]
Firefox 43版本下，一篇长文章往下拉动一定长度，然后加粗标题，编辑器内部的滚动条会自动跳回顶部。

**Comment by Jio168** [comment]
我也是

**Comment by Phinome** [comment]
ueditor版本？

**Comment by Jio168** [comment]
1.4.3.1

**Comment by Jio168** [comment]
只要设置了autoHeightEnabled: false，就会这样。不设置就没事。但是有时候需要关闭自动增高，又不想让他跳，怎么解决？

**Comment by tammylights** [comment]
@Phinome 我也遇到了这个问题，火狐浏览器47版本没问题，但是48版本就是如此，ue版本是1.4.3.3
