### ISSUE TITLE
怎么将后台取到的&ldquo;&rdquo;转义为“”和前台的“”提交到后台转换为&ldquo;&rdquo;

### ISSUE THREAD

**Issue by quickbird** [fex-team/ueditor#2432]
用Java后台也可以做相关转换，但是我想直接修改ueditor.all.js代码，大致看了下可以修改这个方法实现：
    unhtml:function (str, reg) {
        return str ? str.replace(reg || /[&<">'“”](?:%28amp|lt|quot|ldquo|rdquo|gt|#39|nbsp|#d+%29;)?/g, function (a, b) {
            if (b) {
                return a;
            } else {
                return {
                    '<':'&lt;',
                    '&':'&amp;',
                    '"':'&quot;',
                    '>':'&gt;',
                    "'":'&#39;',
                    '“':'&ldquo;',
                    '”':'&rdquo;'
                }[a]
            }

```
    }) : '';
}
```

可是修改后，怎么压缩啊？，另外这里有个正则表达式参数意思是可以配置的么？具体在那里配置？

**Comment by Phinome** [comment]
http://fex.baidu.com/ueditor/#dev-bale_width_grunt 请看文档
