### ISSUE TITLE
关于上传图片时，img标签的width属性和height属性的问题

### ISSUE THREAD

**Issue by wzsxlh** [fex-team/ueditor#2434]
默认上传图片的时候，对应的html代码是这样的
<//img src="/ueditor/php/upload/image/20140722/1406040023503428.jpg" alt="1406040023503428.jpg"///>

我想让它这样，
<//img src="/ueditor/php/upload/image/20140722/1406040023503428.jpg" alt="1406040023503428.jpg" width="291" height="164" style="width: 291px; height: 164px;"///>

就是宽度和高度的属性我想它自动加上，怎么做啊？

**Comment by huayangmeng** [comment]
用正则表达式添加就好了

**Comment by wzsxlh** [comment]
能给我一个例子吗？谢谢
