### ISSUE TITLE
IE下 输入一段文字，全选复制再粘贴后，会自动换行

### ISSUE THREAD

**Issue by stwilsonanny** [fex-team/ueditor#2439]
IE下 输入一段文字，全选复制再粘贴后，会自动换行

**Comment by Phinome** [comment]
IE什么版本，ueditor什么版本？

**Comment by tofdragon** [comment]
测试环境：
IE10及以下
ueditor  4.3.1   
win7 64位电脑  会出现此问题，是否需要进行什么特殊的配置？



测试环境：
IE10及以下
ueditor  4.3.1   
win7 64位电脑  会出现此问题，是否需要进行什么特殊的配置？
