### ISSUE TITLE
ASP.NET , 确认后端配置与文档一致。但是最后检查一步不能通过？

### ISSUE THREAD

**Issue by xmwgp8** [fex-team/ueditor#2440]
ASP.NET 

后端配置与文档说明的一致，而且步骤也都成功。到最后一步，在浏览器输入检查地址后，不能通过？
下载的是 1.4.3.1 的最新版本。

操作系统是阿里云上的 windows server 2008 R2 .

**Comment by Phinome** [comment]
http://fex.baidu.com/ueditor/#server-asp 看看文档是不是哪一步操作有错误。
