### ISSUE TITLE
自动排版中的清除格式为何不生效

### ISSUE THREAD

**Issue by zhangxiaoyu1** [fex-team/ueditor#2443]
![default](https://cloud.githubusercontent.com/assets/16249467/11735030/a67c2016-9ff7-11e5-980e-d25f1865edd0.PNG)

自动排版里的清除格式，只清楚Class，是特殊的设计还是个问题？
个人理解是不是应该和toolbar里的清除格式是一样的呢？ 哪位大神可以帮忙解答一下呢？

**Comment by Phinome** [comment]
自动排版里的清除格式，准确的说应该是清除冗余的 css class，而 toolbar 里的橡皮擦其实才是清除样式。具体可以参考：http://fex.baidu.com/ueditor/#start-config 中的：removeFormatTags，removeFormatAttributes 以及 autotypeset 。
