### ISSUE TITLE
取消使用ueditor后的bug提示，但不影响使用。

### ISSUE THREAD

**Issue by openvast** [fex-team/ueditor#2452]
就是不爽控制台错误提示：
![image](https://cloud.githubusercontent.com/assets/9793122/11803870/e1da1f7e-a339-11e5-80f6-64b2267d9ab3.png)

**Comment by Phinome** [comment]
什么版本的浏览器，什么版本的ueditor ？

**Comment by openvast** [comment]
逗我，现在才回复，早就忘了。
