### ISSUE TITLE
动态上传目录能否请大神给一个后台接收参数并设置imagePathFormat的实例

### ISSUE THREAD

**Issue by jerryluvip** [fex-team/ueditor#2459]
有大神知道ueditor上传时如何根据用户ID生成上传目录？官方说在页面实例化时设置上传参数
ue.execCommand('serverparam', {
        'uid': '123',
    });
然后后台是在controller.jsp里接收参数，是request.getParameter("uid")吗？
如果接受到值，又是如何修改config.json文件中的imagePathFormat?

**Comment by Lingdu0** [comment]
jsp不清楚，PHP的话可以在控制器里面修改$CONFIG['imagePathFormat']的值来实现

**Comment by jerryluvip** [comment]
那你修改imagePathFormat时可以传入变量参数吗？如果单纯更改固定的某个地址，确实只要改一下config.json中imagePathFormat的路径名称就可以了。
我的问题是不能让网站所有用户的上传图片都放入某个固定的目录下，而应该根据用户ID，动态生成每个用户自己的存放路径。
BTW， 谢谢你的关注。

**Comment by Lingdu0** [comment]
就是修改$CONFIG的值实现啊

**Comment by jerryluvip** [comment]
PHP是在controller.php文件里吗？JSP版的controller.jsp里没有关于imagePathFormat的变量定义呢

**Comment by Lingdu0** [comment]
自己在controller里面写啊。

**Comment by Lingdu0** [comment]
不过我是把ueditor的配置文件改成php array 形式的，直接程序可惜动态修改。

**Comment by Lingdu0** [comment]
$CONFIG['imagePathFormat'] = $uid;

**Comment by jerryluvip** [comment]
这个uid是在UE实例化时按官网文档
ue.execCommand('serverparam', {
 'uid': '123',
 });
发送吗

**Comment by Lingdu0** [comment]
服务端根据session动态改就可以了啊

**Comment by jerryluvip** [comment]
好，不过用session的话，按官网的说法，低版本IE里用flash上传不能带session的，看样子用serverparam是最保险的用法

**Comment by Lingdu0** [comment]
不知道，但是我觉得直接淘汰掉低版本IE吧。

**Comment by jerryluvip** [comment]
能简单示例一下config.json改成数组如何与controller.php调用的过程吗？谢谢你的思路的启发

**Comment by Lingdu0** [comment]
$CONFIG = json_decode(preg_replace("/\/\*[\s\S]+?\*\//", "", file_get_contents("config.json")), true);
foreach($CONFIG as $name => $value){
    if(!is_array($value)) {
        echo "'{$name}' => \"{$value}\"," . nl2br(PHP_EOL);
    }else{
        echo "'{$name}' => array(".nl2br(PHP_EOL);
        foreach($value as $name2 => $value2){
            echo "'{$name2}' => \"{$value2}\",".nl2br(PHP_EOL);
        }
        echo "),".nl2br(PHP_EOL);
    }
}

把生成的复制一下自己稍稍修改下，可能会有错的地方，毕竟顺便写的。然后粘贴到 <?php return array(粘贴到这里面)?>

$config = require 'config.php')//congfig为刚刚生成的并粘贴的
这时你在config.php里面怎么动态配置是你的事了，但是我觉得读取出来后重新复制$config[‘imagePathFormat']里的值更好，这样配置文件更清晰，不过这得看你具体的。

**Comment by jerryluvip** [comment]
PHP看不懂哎。不过再次谢谢Lingdu0的帮助！
让人难解的是1.4.3版中controller.jsp是如何调用了config.json文件的，看controller.jsp中也根本没有关于config.json中的相关元素，只是处理了一下rootPath路径,难道跟com.baidu.ueditor.ActionEnter有关系，这个ActionEnter是什么东东？

**Comment by isszz** [comment]
这个我实现了,主要是要改官的上传类,其他的都用不到,

    protected $bhv;
    private $app;
    private $ifthumb = 0;
    private $width = 0;
    private $height = 0;

    /**
     * 构造函数
     * @param object $bhv 上传动作
     */
    public function __construct(UploaderAction $bhv) {
		$this->bhv = $bhv;
        $this->fileField = $bhv->fileField;
        $this->config = $bhv->config;
        $this->type = $bhv->type;
        $this->app = $bhv->app;
    }
这个我传入进来的是一个上传动作类,所以官方这个类不是入口,上传动作才是入口,比如PathFormat就是在动作类里面处理的,还有配置信息
    /**
     * 按类型执行上传
     */
    public function upload() {
        if ($this->type == 'remote') {
            $this->saveRemote();
        } else if($this->type == 'base64') {
            $this->upBase64();
        } else {
            $this->upFile();
        }
        return true;
    }

在本来的上传方法成功后 增加


        return $this->operate($this->filePath, $this->fullName);
这个是用来处理上传成功后的图片相关方法比如抛出一个接口出去让他处理比如上传到qiniu什么的
还有主要是处理水印缩略图

	 */
	public function operate($source = '', $filePath = '') {
//这里处理你的缩略图啊水印相关的动作


		return $this->bhv->update($this->getFileInfo()); //抛出上传成功后的图片信息给上传的动作类
}

    /**
     * 重命名文件
     * @return string
     */
    public function getFullName() {
        // 替换日期事件
        $t = Helper::time();
        $d = explode('-', Helper::time2str($t, "Y-y-m-d-H-i-s"));
        $format = $this->bhv->getPathFormat();
}主要还是这里从上传动作类提取PathFormat设置





上传入口是这样的
$bhv = new AdminImageUpload($userid, 'image');
if ($result = $bhv->upload() and $result !== true) {
	UeditorSrv::message(array('state' => $result), true);
}
// AdminImageUpload就是上传的动作类
大概逻辑是这样0 0...

**Comment by isszz** [comment]
传自定义参数我是通过 editor.setOpt({formData:{uid:1}});这样传递的,然后修改image.js在WebUploader初始化的参数里面加上formData: editor.getOpt('formData'),

**Comment by isszz** [comment]
原谅我,你说的是jsp我发了一堆php- -还是删除 - -

**Comment by jerryluvip** [comment]
PHP的也可以给需要的用户参考一下，同时也谢谢您的分享

**Comment by chenwj1979** [comment]
if(isset($_SESSION['userinfo'])){
    $CONFIG['imagePathFormat']="/Public/uploads/".$_SESSION['userinfo']['id']."/image/{yyyy}{mm}{dd}/{time}{rand:6}";
}else{
    $CONFIG['imagePathFormat']="/Public/uploads/200/image/{yyyy}{mm}{dd}/{time}{rand:6}";
}
我在controller.php文件中的“$CONFIG = json_decode(preg_replace("/\/\*[\s\S]+?\*\//", "", file_get_contents("config.json")), true);”下面增加了上面的语句，调用ueditor的页面中其他控件能正常显示$_SESSION['userinfo']['id']，可是上面的判断语句却显示$_SESSION['userinfo']['id']为空，判断语句进入了else部分，请问哪位大神能回复下

**Comment by Lingdu0** [comment]
是不是没有session_start()

**Comment by chenwj1979** [comment]
用的thinkphp框架，框架中启动了session了的，然后这个调用ueditor的页面跟session设置页面是不同的，这个页面显示正常，理论上session是设置成功的啊

**Comment by Lingdu0** [comment]
你的ueditor没在thinkPHP里，没有自动继承session_start。你要使用session函数及$_SESSION变量必须自己先打开session_start。。。多看看手册

**Comment by chenwj1979** [comment]
那大神能告诉下我该如何设置不？看手册没找到答案……刚开始学

**Comment by chenwj1979** [comment]
知道了，确实如您所说，在controller.php文件中增加session_start()就好……谢谢
