### ISSUE TITLE
utils.cssRuls 方法的参数bug

### ISSUE THREAD

**Issue by foreverglory** [fex-team/ueditor#2461]
所有使用到 utils.cssRule 方法，第一个参数，请面请加上.(点)，名称为 className。
如：
1、
utils.cssRule('loading',
                    '.loadingclass{display:inline-block;cursor:default;background: url(\''
                    + this.options.themePath
                    + this.options.theme +'/images/loading.gif\') no-repeat center center transparent;border:1px solid #cccccc;margin-right:1px;height: 22px;width: 22px;}\n' +
                    '.loaderrorclass{display:inline-block;cursor:default;background: url(\''
                    + this.options.themePath
                    + this.options.theme +'/images/loaderror.png\') no-repeat center center transparent;border:1px solid #cccccc;margin-right:1px;height: 22px;width: 22px;' +
                    '}',
                    this.document);
=>
utils.cssRule('.loading',
                    '.loadingclass{display:inline-block;cursor:default;background: url(\''
                    + this.options.themePath
                    + this.options.theme +'/images/loading.gif\') no-repeat center center transparent;border:1px solid #cccccc;margin-right:1px;height: 22px;width: 22px;}\n' +
                    '.loaderrorclass{display:inline-block;cursor:default;background: url(\''
                    + this.options.themePath
                    + this.options.theme +'/images/loaderror.png\') no-repeat center center transparent;border:1px solid #cccccc;margin-right:1px;height: 22px;width: 22px;' +
                    '}',
                    this.document);
2、
utils.cssRule('edui-customize-'+this.name+'-style',this.cssRules);
=>
utils.cssRule('.edui-customize-'+this.name+'-style',this.cssRules);
3、等～～～

**Comment by ForeverGlory** [comment]
还有传递ID的 utils.cssRule(cssRuleId, '', me.document)，请加上 #
