### ISSUE TITLE
如何自己写图片上传程序

### ISSUE THREAD

**Issue by jackcaicn** [fex-team/ueditor#2463]
关于图片上传，你们就不能定义一个标准接口吗，不公开文档？
用户用什么平台，什么办法处理上传，那是人家的事，你丢几个php, .net的sample别人不一定用那些平台，就算用，人家可能有别的方法呢。

**Comment by zhangx3000** [comment]
事实上大苏打

**Comment by isszz** [comment]
你只要把官方提供的上传类作为基类,稍做改动,自己写动作类
