### ISSUE TITLE
ueditor无法初始化格式化过的文本内容

### ISSUE THREAD

**Issue by cocoonyun** [fex-team/ueditor#2471]
文章内容用ueditor改好格式保存到数据库后，当再次用ueditor初始化读出来时，无法显示，ueditor控件也消失，而保存在数据库的没有格式的txt文本内容可以正常显示，怎么解决？？？

**Comment by wangguanquan** [comment]
同样的问题, aotuSave开启, 自动保存后无法恢复到保存之前的格式.
比如我改了字号和颜色.localstorage保存为{"http_localhost_ueditor_js_editor-drafts-data":"<p>fd<span style=\"font-size: 20px;\">safdsae</span></p>"}, 恢复之后格式全部不见,变为<p>fd<span>safdsae</span></p>. **求解决方案**.
