### ISSUE TITLE
不能单独调用单图上传功能

### ISSUE THREAD

**Issue by comandowang** [fex-team/ueditor#2482]
单独调用简单图片上传功能，我是这么写的，可是调用不了
$(".edui-for-simpleupload .edui-button-body")[0].click();
可是还是这么写，多图上传是可以的
$(".edui-for-insertimage .edui-button-body")[0].click();

**Comment by Phinome** [comment]
单独使用图片上传，建议使用单独的图片上传工具，例如：webuploader.https://github.com/fex-team/webuploader
