### ISSUE TITLE
图片上传iconv

### ISSUE THREAD

**Issue by yinxiongfeng** [fex-team/ueditor#2486]
在upload.class.php里 $this->stateMap['ERROR_TYPE_NOT_ALLOWED'] = iconv('unicode', 'utf-8', $this->stateMap['ERROR_TYPE_NOT_ALLOWED']); 这一段 注释掉就OK 不注释掉的话，编辑器显示上传错误 ，文件夹里已经存在上传的文件，不知道是什么问题

**Comment by rockwxy** [comment]
我也是这个问题

**Comment by amUni** [comment]
controller 里的error_reporting(E_ERROR)是不是被你注释掉了

**Comment by yinxiongfeng** [comment]
@amUni 没有注释掉额
