### ISSUE TITLE
怎么设置ueditor只删除文本不删除包围它的标签

### ISSUE THREAD

**Issue by youkelike** [fex-team/ueditor#2488]
编辑视图里看到是这样的：其它文字要删除的文字
源代码视图里看到是这样的：其它文字<div class='my' style=''>要删除的文字</div>
在编辑视图里用删除键删除文字的时候，如果把“要删除的文字”全删了，包围它的div标签也会被自动删了，怎么能让它别把那个div也删掉？因为div里面关联了一些特殊样式，如果把它们全删了再换其它文字，原来的样式就全没了。

**Comment by wangjgweb** [comment]
将文字用p标签包起来试试。如：<section><p>文字，文字</p></section>
