### ISSUE TITLE
 重金求给我目前的ueditor加个小功能并升级到最新版本

### ISSUE THREAD

**Issue by yongzeng0415** [fex-team/ueditor#2491]
目前我们的ueditor插入图片后  鼠标点一下图片   没有缩放功能，而ueditor本身是有这功能的，这说明我们以前二次开发的时候把这功能屏蔽掉了，现在又急需这个功能，以前的程序员无法联系，所以才来这里请大神给我加上这个该有的功能，
第二：一个页面2个ueditor 只能用一个，请给我调试成2个都可以使用。
一共2个需求，能帮我完成一个也行 ，如果全部完成就更好。
可以做的给我报价或联系我。 Q 252 -2084-73

**Comment by yongzeng0415** [comment]
一共三个需求，能帮我完成一个也行  ，如果全部完成就更好。

**Comment by focusqfb** [comment]
可以
