### ISSUE TITLE
下载资源包的时候报错

### ISSUE THREAD

**Issue by zhu353071655** [fex-team/ueditor#2498]
UBuilder Error!
create temporary directory error!

求大神指导

**Comment by hale1106** [comment]
这么久了，有没有人看看。。。

**Comment by SkyeTang** [comment]
同样的问题路过....

**Comment by hioop** [comment]
somebody else?
看来真没官方人员来解决这个问题了。。。

**Comment by Phinome** [comment]
统一回复各位，git clone 仓库到本地，grunt 构建。
