### ISSUE TITLE
编辑器内点击图片不能正确选择图片

### ISSUE THREAD

**Issue by dostone** [fex-team/ueditor#2500]
大家有试过吗，我把2张图片放在编辑器内，我第一次点的那张图片可以正确选择。当我再去点击其它图片的时候都不能正确的选择对应的图片

**Comment by earclink** [comment]
看来这个问题很多人反映，但是官方好像没有修复的意愿，不晓得这个软件有没有人在维护中，呵呵。

**Comment by Phinome** [comment]
这个是个 bug ，后续会修复。
