### ISSUE TITLE
{"state":"action 参数为空或者 action 不被支持。"} 已经出现

### ISSUE THREAD

**Issue by lcsoftware** [fex-team/ueditor#2502]
{"state":"action 参数为空或者 action 不被支持。"} 已经出现，但上传本地图片还是提示：后端配置项没有正常加载，上传插件不能正常使用！，

后台的.net程序我是直接配置在网站的根目录下的。app_code目录的内容，controller.ashx及config.json文件都放在了网站根目录下，修改ueditor.config.js : 
// 服务器统一请求接口路径
 serverUrl: "http://172.30.2.132:8020/controller.ashx"

但上传本地图片还是会提示：后端配置项没有正常加载，上传插件不能正常使用！
浏览器是显示无任何错误，也没有任何请求不到的地址

**Comment by Phinome** [comment]
参考文档：http://fex.baidu.com/ueditor/#server-deploy php的配置和访问方式，访问：serverUrl: "http://172.30.2.132:8020/controller.ashx?action=config" 看是否成功。如果没有成功，按照文档配置即可。
