### ISSUE TITLE
ueditor外层div宽高调整到100%后，toolbar总是居右显示

### ISSUE THREAD

**Issue by sunhe8848** [fex-team/ueditor#2504]
用的1.4.3版ueditor，调整宽高为100%，工具栏居右显示，请问如何让工具栏居左显示？
代码如下：
    <div style="width:100%;height:100%;">
    <script id="editor" type="text/plain" style="width:100%;height:100%;"></script>
 </div>

**Comment by Phinome** [comment]
没有代码额
