### ISSUE TITLE
想问一下UEditor的清除格式都可以清除什么

### ISSUE THREAD

**Issue by chensamuelhe** [fex-team/ueditor#2512]
我在UEditor里使用了‘自动排版“中的“清除格式”，但是从其他网页copy过来的内容还是带有各种样式，比如margin-top之类的。

想问一下，有没有什么办法可以把所有个样式都清除掉，只保留文本信息？

**Comment by Phinome** [comment]
格式刷旁边的清除格式，清除格式时可以删除的标签和属性:
标签默认值：
'b,big,code,del,dfn,em,font,i,ins,kbd,q,samp,small,span,strike,strong,sub,sup,tt,u,var'
属性默认值：
'class,style,lang,width,height,align,hspace,valign'
而自动排版里的清除格式，准确的说应该是清除冗余的 css class 。
所以，如果你只需要清除样式，那么直接点击清除格式就好了，如果还需要过滤一些特殊的 html 标签，那么在 editor 初始化或者 editor.configer.js 中配置，removeFormatTags 来实现。
具体可以看文档：http://fex.baidu.com/ueditor/#start-config
