### ISSUE TITLE
清除格式和冗余代码是做什么用的？

### ISSUE THREAD

**Issue by chensamuelhe** [fex-team/ueditor#2515]
UEditor“自动排版”中的“清除格式”和“清除冗余html代码”以及“粘贴过滤”的作用是什么？我使用之后网站带过来的样式都还在。如果要清除所有的样式，应该怎么做？

**Comment by Phinome** [comment]
自动排版中的清除格式准确的说是清除冗余的 css class ，而你要清除样式，点击橡皮擦（清除格式）即可。具体，可以参考文档：http://fex.baidu.com/ueditor/#start-config
