### ISSUE TITLE
语言包例如zh-cn 能够关闭自动加载而是自己手动引入吗

### ISSUE THREAD

**Issue by pcazheng** [fex-team/ueditor#2516]
情景是这样的 我使用的是MVC.NET 的Bundle功能 压缩js文件 但是这种压缩会造成路径的重写 
所以当Ueditor在js加载文件的时候找不到改语言文件 请问能否关闭自动加载 而改成手动引用语言文件

**Comment by Phinome** [comment]
参考文档：http://fex.baidu.com/ueditor/#start-config  属性：lang 一项
