### ISSUE TITLE
反馈一个bug

### ISSUE THREAD

**Issue by lifetin** [fex-team/ueditor#2526]
在编辑器中插件链接时
如果是插入描点(以#开头).则会在描点前加上http://
需要修改一下文件,加个检查

umeditor.js中的6054行左右原来是
if(!/^(ftp|https?|\/|file)/.test(_href)){
需要改成以下就完美解决
if(!/^(ftp|https?|\/|file)/.test(_href) && _href.charAt(0)!='#'){

**Comment by Phinome** [comment]
看到了，谢谢
