### ISSUE TITLE
不能将编辑器嵌套在JQuery easyUI页面作为window对象打开……

### ISSUE THREAD

**Issue by ren-liang** [fex-team/ueditor#2529]
将UEditor嵌套在页面中一个Div中，该div被初始化为一个jQuery easyui 的window对象，适当的时候打开这个window，UEditor所有的功能可以使用但是，所有的dialog弹出时都跑到这个window的后面去了……

**Comment by Phinome** [comment]
将 Dialog 的 zIndex 设置高一点。
