### ISSUE TITLE
UMeditor 如何禁止拖拽内容进入编辑框

### ISSUE THREAD

**Issue by TheYoungFatty** [fex-team/ueditor#2532]
UMeditor 如何禁止拖拽内容进入编辑框

**Comment by TheYoungFatty** [comment]
没人回

**Comment by yanlong8436** [comment]
在umeditor.config.js里面设置

**Comment by julabs** [comment]
在umeditor.config.js里面，只有禁止**拖放图片到编辑区域**的设置。而这里的意思应该是选取页面上的一块区域，直接拖曳到编辑器里面。
我也遇到了这个问题

**Comment by Phinome** [comment]
目前貌似不支持这个功能，后续有时间再说吧。
