### ISSUE TITLE
关于文件上传至数据库的问题

### ISSUE THREAD

**Issue by ganpanlin** [fex-team/ueditor#2536]
对于文件类型，是否可以添加保存方式，目前默认是保存在所配置的文件夹中。看了下源代码，在State StorageManager.saveFileByInputStream(InputStream is, String path, long maxSize)基本返回了显示信息，路径查看信息等一系列前台可用信息，那么此处是否可以增加一个通用接口，用于用户通过配置直接调用接口保存is中的信息至其他文件或者数据库呢？

**Comment by Phinome** [comment]
没有人力支持了
