### ISSUE TITLE
ue1.4.3 asp 单图上传累计许多无用图片

### ISSUE THREAD

**Issue by hh65109523** [fex-team/ueditor#2538]
请教大牛：在整个ue提交前，单图上传直接保存到了相应文件内，后面一些图片不想要了在ue中删除了，然而那部分图片已经保存到了某个图片文件夹中，如何处理这部分前期操作最后又不用的图片？只保留最后整个ue提交时内容里面的图片
如何有人说先放在一个临时文件夹，然后根据最后提交的内容来遍历出有用的将之拷贝到新的目录，然后把临时文件夹删除，这个就不用说了，因为当上传文件很多的时候这个效率太低，不好用，我想问有没有其他好的方案

**Comment by Tyraan** [comment]
PHP 后台也同样出现了同一个问题。原因是 UE没有删除功能，这个在帮助文档里 讲了，所以需要自己去写删除图片的接口。
