### ISSUE TITLE
ueditor.all.min.js是采用什么工具压缩的

### ISSUE THREAD

**Issue by dhcn** [fex-team/ueditor#2539]
有个需求要把字体颜色的可选集合做修改，已经找到ueditor.all.js修改位置，但是不知道改完用什么工具及配置做压缩成ueditor.all.min.js
怕自己压的和全局不兼容。

**Comment by Phinome** [comment]
google 的 closurecompiler，不过推荐你用 [UglifyJS](https://github.com/mishoo/UglifyJS) ，closurecompiler 下不了，而且后续会废弃。

**Comment by dhcn** [comment]
3kS,反正别压缩完不可用就行了。
