### ISSUE TITLE
UE 目前有这几个BUG，很好奇你们有没有做过测试就发布了

### ISSUE THREAD

**Issue by rockwxy** [fex-team/ueditor#2543]
1、单图上传 在跨域的情况下上传成功后在console下也能看到数据回传了，结果就是死都插不进图片
2、多图批量在线管理，在跨域的情况下没有使用imageUrlPrefix，显示不了图片

**Comment by wudgaby** [comment]
多图上传 怎么解决的?

**Comment by Tao-Cui** [comment]
单图上传图片传到服务器，但是显示上传失败，多图解决了跨域之后倒是没有问题
