### ISSUE TITLE
ueditor初始化问题

### ISSUE THREAD

**Issue by FlashSayToRain** [fex-team/ueditor#2544]
老师  我想初始化一个带格式的内容  该如何操作呢？
例如： 我想初始化一个  <p>aaaaa</p>  这个语句 
该如何操作呢？

**Comment by Phinome** [comment]
ueditor 初始化的时候 `setContent("你要的内容")` ，具体的参考文档：[http://fex.baidu.com/ueditor/](http://fex.baidu.com/ueditor/)
