### ISSUE TITLE
终于解决了图片上传跨域的问题了

### ISSUE THREAD

**Issue by yahon** [fex-team/ueditor#2545]
1 首先 UEditor 必须部署在当前域名下面 如果为不同的子域名则需要添加 `document.domain` 但是不能跨域名如：UEditor 在静态服务器 `a.com` 然后在 `b.com` 使用则不可以 因为 `iframe` 不能跨域。

2 单个图片上传不支持跨域 只有多图上传才支持

3 修改 `ueditor.config.js` 文件中的 `serverUrl` 修改成上传服务器的上传地址 

4 修改 `dialog/image/image.html` 中 `webuploader` 的引用文件为：`webuploader.flashonly.js`(未测试HTML5)

5 修改上传接口返回值中`url`为全路径
```
{
    "state": "SUCCESS", 
    "url": "http://192.168.0.222:8080//ueditor/php/upload/image/20160126/1453783598560445.png", 
    "title": "1453783598560445.png", 
    "original": "2.png", 
    "type": ".png", 
    "size": 213562
}
```

**Comment by Phinome** [comment]
还可以看看文档 [跨域支持说明](http://fex.baidu.com/ueditor/#dev-crossdomain)

**Comment by IsResultXaL** [comment]
666

**Comment by wudgaby** [comment]
这叫解决跨域问题?
只是逃避了跨域问题而已
1.单图iframe无法跨域 获取不到iframe的内容
2.多图只是用了flash上传.

单图和多图上传 都存在跨域无法用的问题.
官方没解决办法吗?
