### ISSUE TITLE
打开ueditor的功能按钮，出现X-Frame-Options' to 'DENY'，ifream里面的东西打不开~

### ISSUE THREAD

**Issue by mytestlife** [fex-team/ueditor#2546]
打开ueditor的功能按钮，比如上传图片，百度地图等功能
在使用按钮中，出现Refused to display '.../assets/ueditor/dialogs/image/image.html' in a frame because it set 'X-Frame-Options' to 'DENY'的错误
查了一遍代码，没有任何发现，
求解决，求思路

**Comment by Phinome** [comment]
看看 nginx 或者 apache 的响应头是否设置了 X-Frame-Options: DENY 。具体参考：[https://developer.mozilla.org/zh-CN/docs/Web/HTTP/X-Frame-Options?redirectlocale=en-US&redirectslug=The_X-FRAME-OPTIONS_response_header](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/X-Frame-Options?redirectlocale=en-US&redirectslug=The_X-FRAME-OPTIONS_response_header)
