### ISSUE TITLE
java疑问：文件上传，增加multipartResolver，FileItemIterator 获取不到文件流的问题。

### ISSUE THREAD

**Issue by mytestlife** [fex-team/ueditor#2547]
环境:
①SpringMVC+Security+Freemarker， 
②更改controller.jsp变更为controller.htm，通过后台@Controller，实现的controller.jsp中的所有功能。（这个应该不影响，）
③Spring配置中增加
```
	<bean id="multipartResolver"
		class="org.springframework.web.multipart.commons.CommonsMultipartResolver">
		<property name="maxUploadSize" value="209715200" />
		<property name="resolveLazily" value="true" />
	</bean>
```
(Spring 文件上传功能)
④Security 中增加
`        <http pattern="/**/controller.htm" security="none"/>`
(设置过滤器不进行拦截，要不各种405 403 禁止访问，禁止跨域)
⑤Security 中增加
```
        <http auto-config="true">
	    <headers>
	          <frame-options policy="SAMEORIGIN"/>
	    </headers>
        </http>
```
(如果④中设置后仍出现打不开面板，请加入Http头，允许x-frame-options，为SAMEORIGIN ，SpringSecurity 默认x-frame-options 为deny)

问题来了：
UEditor 在加入	③的配置以后，FileItemIterator 获取不到文件流的问题，这是为什么呢？

尝试自行解决：
经过debug发现
```
	currentItem	null	   -> 这个值里获取不到上传的文件(对比没有配置③)
	eof	true	                   -> 这个值应为false (对比没有配置③)
	itemValid	false           -> 这个值应为true(对比没有配置③)
```
同时检查了request 里的文件内容也发生了变化...
下面这个是加入③配置后
```
multipartFiles	                                            LinkedMultiValueMap<K,V>  (id=118)	
multipartParameterContentTypes	            HashMap<K,V>  (id=121)	
multipartParameters	                            HashMap<K,V>  (id=122)	
request	                                                    RequestWrapper  (id=123)	
this$0	                                                    CommonsMultipartResolver  (id=126)	
val$request	                                            ReqppuestWraer  (id=123)	
```
下面这个是未加入③配置
```
request	                                                    RequestFacade  (id=107)	
stripPaths                                               	    false	
strippedPathInfo	                                    "/upload/ueditor.htm" (id=109)	
strippedServletPath	                                    "" (id=113)	
```

疑问：应该是Spring③配置的问题，将上传请求request的封装改变了....

问题变更：
1. 如何配置Spring MVC 才能正常使用ueditor 上传问题？
2. 如果使用③配置，要进行哪些修改？（已解决，修改源码，使用			MultipartHttpServletRequest multipartRequest = (MultipartHttpServletRequest) request;
MultipartFile file = multipartRequest.getFile("upfile");来替代 ）
3.有没有折中的办法？

**Comment by Phinome** [comment]
涉及 Java 的问题，目前只有依仗各位自行解决了，这边暂时没有人力支持 Java 了。
