### ISSUE TITLE
为什么我的umditor整合springmvc中上传的图片地址在后台会出现2个

### ISSUE THREAD

**Issue by yanlong8436** [fex-team/ueditor#2549]
编辑器上传图片时，在后台获取内容是，内容中有2个路径，一个是src=“” 一个是 _src=""  图片地址是一样的，我想知道这是为什么

**Comment by Phinome** [comment]
看了一下代码，两个值取得是一致的，建议你取 `src` ，至于为啥要有两个，历史因素，我也不清楚了。
