### ISSUE TITLE
关于传递动态自定义请求参数

### ISSUE THREAD

**Issue by 3xxx** [fex-team/ueditor#2550]
请问我如何在上传图片前，先填写页面上其他表单的值。然后点击UE的上传图片按钮，此时，希望能获取页面上的表单值，作为自定义请求参数传递出去？
代码类似下面，结果像http://*******/controller?action=uploadimage&number=156&name=label
```
      a = document.getElementsByName("number");
      a=a[0].value;
      var b = document.getElementsByName("name");
      b=b[0].value; 
    ue.execCommand('serverparam', {
        'name': a,
        'number': b,
    `});```
```
我想在点击上传图片的时候，触发 ue.execCommand('serverparam'，从而取得页面表单值。
有这个方法吗？谢谢。

**Comment by Phinome** [comment]
看看文档 [自定义请求参数](http://fex.baidu.com/ueditor/#dev-serverparam)

**Comment by 3xxx** [comment]
谢谢您的回答，官网中的例子都是固定值，我想在UE加载完成 后，用户填完表单，在获取到表单值后，将这个值传递给后台。比如在beforeuploadimage事件时触发ue.execCommand('serverparam', {……

请问，您在https://github.com/fex-team/ueditor/issues/1047中答复
“好，这个作为后续需求。”是不是目前还没此功能？

**Comment by Phinome** [comment]
我在那个里面说的意思是支持 POST 传递，不是指你的问题。你这个功能，我再看看代码，后续回复你。

**Comment by Phinome** [comment]
编辑器里插入图片的时候会触发 `beforeinsertimage` 这个方法，你可以 `ue.addListener('beforeinsertimage', callback)` ，在 `callback` 里执行 `ue.execCommand('serverparam')`

**Comment by 3xxx** [comment]
谢谢您的回答。请教：
1、官网api中似乎没有看到beforeinsertimage这个方法？请问写在哪里了？百度倒是可以搜到一些。
2、当上传图片的时候，路径已经传出去了，如http://****/controller?action=uploadimage&encode=utf-8，我想在上传图片的这个请求中带上表单中参数，如何触发呢？像http://*******/controller?action=uploadimage&number=156&name=label

**Comment by 3xxx** [comment]
是不是应该有个像uploadify中的方法onUploadStar，在开始上传之前的瞬间会触发该事件。
uploadify代码：
```
$(function() {
    $("#file_upload").uploadify({
        'swf'           : '/uploadify/uploadify.swf',
        'uploader'      : '/uploadify/uploadify.php',
        'onUploadStart' : function(file) {
            alert('开始上传 ' + file.name);
        }
    });
});
```

**Comment by Phinome** [comment]
那应该在 webuploader 里定义，编辑器作为调用者不应该关心这个。

**Comment by 3xxx** [comment]
用ue.addListener('focus'勉强解决。
ueditor.all.js24518行左右，增加

```
/* 添加额外的GET参数 */
                var params = utils.serializeParam(me.queryCommandValue('serverparam')) || '';
                form.action = utils.formatUrl(imageActionUrl + (imageActionUrl.indexOf('?') == -1 ? '?':'&')  + params);
```
页面中用下面这段：

```
var ue = UE.getEditor('editor');
ue.ready(function () {
ue.addListener('focus', function () {//要是有个能在上传图片之前触发的事件就完美了
     var name = $('#name').val();
      //  if (name.length==0){
      //   alert("请输入项目名称");
      //   return false;
      // }    
     var number = $('#number').val();
      //  if (name==""){
      //   alert("请输入项目编号");
      //   return false;
      // }    
      // alert(name)
    ue.execCommand('serverparam', {
        "number":number,
        'name': name,
    });
});
});
```
