### ISSUE TITLE
图片上传时，服务端正确反馈仍然显示上传错误

### ISSUE THREAD

**Issue by luoyjx** [fex-team/ueditor#2552]
现在是angularjs中集成ueditor

使用的是这个库
https://github.com/zqjimlove/angular-ueditor

Ueditor文档显示

![image](https://cloud.githubusercontent.com/assets/4217102/12667378/b66ccf0c-c685-11e5-9ac7-a7b63871f7b8.png)

按文档要求服务端已经返回了如下json字符串，但是编辑器仍然显示`上传错误`
```
{"state":"SUCCESS","url":"http://xxxxx.com/xxxx/eBQh4WvIY2HSyPx0OZCHdN4Uuzvg94Ye.jpg","title":"demo.jpg","original":"demo.jpg"}

**Comment by Phinome** [comment]
那个还不是官方的额，不知道作者是怎样结合的，你可以去他的仓库里提一个 issue。

**Comment by youokabc** [comment]
我也是这个错误  有解决方案么

**Comment by lifeizhaopaopao** [comment]
我也是

**Comment by kissshot** [comment]
我看了代码，是用的form上传的，target指向一个name="up"的iframe，iframe里的内容就是返回的JSON字符串，但是被一个pre标签包裹起来了，而代码里取的是body.innerHTML，所以解析JSON出错的，我觉得改成body.innerText应该就可以了

**Comment by zhiyangLau** [comment]
解决了吗？ 我也遇到这个问题了
