### ISSUE TITLE
如何取消一个到controller.php的请求

### ISSUE THREAD

**Issue by kevgithub** [fex-team/ueditor#2555]
网站配置上传等功能时并没有使用ueditor自带的方式，而是直接扩展一套自己的上传图片/视频的入口，每次打开却会有如下请求：

controller.php?action=config&&noCache=1454294775883	GET	(canceled）  ueditor.all.min.js:128

以及一条console的提示：

请求后台配置项http错误，上传功能将不能正常使用！

在不改动源码的前提下，如何去掉这两个碍眼的东西！

**Comment by Phinome** [comment]
将 `serverUrl` 和 `imageUrl` 这两个值置为空。
