### ISSUE TITLE
请教在UE中怎样触发webupload事件？

### ISSUE THREAD

**Issue by 3xxx** [fex-team/ueditor#2560]
UE是使用webupload上传多文件。而webupload有不少好用的事件，比如startUpload……当开始上传流程时触发。
UE所提供的事件比较少，ready等，
我想在startUpload开始上传图片前，触发这个：ue.execCommand('serverparam', function(editor)
而不是在ready时触发。请问可以达到目的吗？谢谢。

**Comment by Phinome** [comment]
试试 `fireEvent` 。
