### ISSUE TITLE
工具栏不显示

### ISSUE THREAD

**Issue by hualidepiaoguo** [fex-team/ueditor#2563]
使用了bootstrap的一个模板，插入ueditor后工具栏不见了，但是可以输入文字，也可以看到元素路径和字数提示，右击文本框在最左面出现了工具栏的一些描述比如贴上、全选等等，但不能按也没反应，求解决方法。
![qq 20160204001113](https://cloud.githubusercontent.com/assets/17049190/12788283/ead7f42c-cad3-11e5-8137-911c056e3b58.jpg)

**Comment by Phinome** [comment]
看一下控制台是否报错，如果有报错，贴一下报错信息。
