### ISSUE TITLE
图片上传路径是否可保存到其他盘符？如何为编辑器设置不同的图片保存路径？

### ISSUE THREAD

**Issue by DevilXiao** [fex-team/ueditor#2564]
项目在C盘，如何将图片上传路径设置到D盘？
我目前是按下面配置，保存在C盘中。
"imageUrlPrefix": "http://172.17.136.8/project/ueditor/net/",
"imagePathFormat": "upload/Notice/images/{yyyy}{mm}{dd}/{time}{rand:6}",

项目里创建了2个Ueditor编辑器，如何设置起图片存放目录不在一个目录下，如何针对每一个Ueditor实例设置图片存放路径

**Comment by 3xxx** [comment]
https://github.com/fex-team/ueditor/issues/2561

**Comment by Phinome** [comment]
.net 的没法通过UEditor 的配置来修改上传路径的盘符，具体可以参考这个：[http://fex.baidu.com/ueditor/#server-net](http://fex.baidu.com/ueditor/#server-net)。
有两个建议：

1. 将不同的站点放在不同的位置，这样配置 .net 的网站根目录就可；
2. 自行修改 UEditor .net 的程序，参考上面给出的链接。
