### ISSUE TITLE
用了ueditor后还需要对编辑器的数据进行过滤和转义吗？

### ISSUE THREAD

**Issue by sml2h3** [fex-team/ueditor#2569]
用了ueditor后还需要对编辑器的数据进行过滤和转义吗？我对ueditor的理解是前端过滤的，但是提交表单的时候，用brupsuite可以截断修改数据啊！
最主要的是，还可以模拟发包，但是我在后台设了转义后，ueditor的标签也会被转义啊，再传到前台就没什么用了，该怎么解决这一问题呢？

**Comment by Phinome** [comment]
后端一定要转义的，不论前端是否转义。后端转义后，再传到前端之前，需要反转一次。

**Comment by sml2h3** [comment]
可是ueditor不是前端转义了一次吗？如果后台再转义的话，那自动生成的富文本标签就没用了啊。

**Comment by Phinome** [comment]
我之前没有描述清楚我的意思，我的意思是对表单提交的字段需要后端过滤，因为据我了解，UEditor 只对编辑区域的内容进行了转义，并没有对表单的字段进行转义。然后，针对内容的展现的问题，可以参考这个文档[编辑内容展示](http://fex.baidu.com/ueditor/#start-uparse)
