### ISSUE TITLE
safari下拖拽选择编辑器内容，会触发浏览器异常滚动

### ISSUE THREAD

**Issue by wangfupeng1988** [fex-team/ueditor#2570]
**复现步骤如下：**

第一，用 safari 访问：http://ueditor.baidu.com/website/onlinedemo.html
第二，手动调整一下编辑器容器的上边距，因为编辑器如果离着页面顶部太近，该问题复现不了。如下图

![](http://images2015.cnblogs.com/blog/138012/201602/138012-20160215141927048-1837300724.png)

第三，点击编辑器下面的『设置编辑器的高度为300』按钮，以固定编辑器的高度。
第四，滚动页面到编辑器的位置，输入足够多的内容（让编辑区域出现滚动条），如下图

![](http://images2015.cnblogs.com/blog/138012/201602/138012-20160215142114798-843149970.png)

第五，在编辑区域用鼠标拖拽选择文字内容，就能复现问题。

**Comment by Phinome** [comment]
排查过后，发现可能是 Safari 的 bug。

**Comment by xukaifu** [comment]
回答好官方啊。

**Comment by Phinome** [comment]
@xukaifu 经过单步调试，发现在鼠标选中的时候，只触发了 `mousedown` 事件，就直接滚动到了页面的底部，没有触发 `scroll` 事件，且同类的编辑器中 `kindeditor` 也是一样的复现步骤。因此，才排除编辑器自身的问题。推测可能是 `Safari` 的 bug。

**Comment by wangfupeng1988** [comment]
突然发现了一个问题，我用自己的编辑器做了一个demo，如下：
http://wangeditor.github.io/wangEditor/test/test-safari-scroll-bug.html

用safari打开，写入若干内容，进行拖拽选择，是没有发现上述问题的。可见也不是safari下的bug吧。

我觉得还是再查证一下比较好。

**Comment by Phinome** [comment]
UEditor 为了最大的兼容性，采用的是 iframe 作为编辑区载体。UM和你的编辑器都是采用 Div 作为编辑区载体，就目前调试的结果来看，同样的步骤在 UM 和你的编辑器下都不会出现问题，结合上面说的单步调试，因此，推测可能是 Safari 自身的 `bug`。

**Comment by xukaifu** [comment]
@Phinome 好的， 非常感谢你的解答。 懂了。
