### ISSUE TITLE
期待单纯JS版本的

### ISSUE THREAD

**Issue by shimne** [fex-team/ueditor#2571]
由于项目用到了其它js库与jquery冲突，所以不得不放弃这个编辑器的使用。这么好的编辑器遗憾啊。

**Comment by Phinome** [comment]
当初使用 jQuery 主要有两个方面的考虑：
1. jQ本身存在的意义，良好的 API 和抹平浏览器DOM API 之间的差异；
2. 向下兼容低版本浏览器。

你所建议的，也是我们后续会考虑跟进的。多谢！
