### ISSUE TITLE
上传音频的问题

### ISSUE THREAD

**Issue by onlyShadow** [fex-team/ueditor#2572]
我在demo中看到，在上传视频的格式里定义了MP3的格式，但是我上传了一个mp3格式的音频时，在展示页面却不能播放，依旧是一个video标签，我想请问，如何上传一个音频

**Comment by Phinome** [comment]
按照文档部署在你本地的环境吧。[http://fex.baidu.com/ueditor/](http://fex.baidu.com/ueditor/)，线上的demo 不允许上传视频和音频文件，上传后会处理掉。所以你啥也看不到。

**Comment by onlyShadow** [comment]
我已经在项目中部署好了

**Comment by onlyShadow** [comment]
@Phinome 我已经在项目中部署好了

**Comment by Phinome** [comment]
嗯，还有啥问题么？
