### ISSUE TITLE
ie9及以下 ueditor选择图片导致浏览器崩溃

### ISSUE THREAD

**Issue by NovaYuan** [fex-team/ueditor#2573]
ie9及以下 ueditor上传图片浏览器崩溃，不知道什么问题？

![image](https://cloud.githubusercontent.com/assets/13275775/13066418/9ae3337e-d4a0-11e5-9578-baf31a658f75.png)

**Comment by Phinome** [comment]
多谢反馈，我看看

**Comment by tofdragon** [comment]
在IE9中测试，可以正常上传图片，浏览器没有奔溃，问题场景需要描述的更清楚

**Comment by tofdragon** [comment]
在IE9中测试，可以正常上传图片，浏览器没有奔溃，问题场景需要描述的更清楚

**Comment by tofdragon** [comment]
在IE9中测试，可以正常上传图片，浏览器没有奔溃，问题场景需要描述的更清楚

**Comment by tofdragon** [comment]
在IE9中测试，可以正常上传图片，浏览器没有奔溃，问题场景需要描述的更清楚

**Comment by tofdragon** [comment]
在IE9中测试，可以正常上传图片，浏览器没有奔溃，问题场景需要描述的更清楚

**Comment by tofdragon** [comment]
在IE9中测试，可以正常上传图片，浏览器没有奔溃，问题场景需要描述的更清楚

**Comment by tofdragon** [comment]
在IE9中测试，可以正常上传图片，浏览器没有奔溃，问题场景需要描述的更清楚

**Comment by tofdragon** [comment]
在IE9中测试，可以正常上传图片，浏览器没有奔溃，问题场景需要描述的更清楚

**Comment by tofdragon** [comment]
在IE9中测试，可以正常上传图片，浏览器没有奔溃，问题场景需要描述的更清楚

**Comment by tofdragon** [comment]
在IE9中测试，可以正常上传图片，浏览器没有奔溃，问题场景需要描述的更清楚

**Comment by tofdragon** [comment]
在IE9中测试，可以正常上传图片，浏览器没有奔溃，问题场景需要描述的更清楚

**Comment by tofdragon** [comment]
在IE9中测试，可以正常上传图片，浏览器没有奔溃，问题场景需要描述的更清楚

**Comment by NovaYuan** [comment]
在bootstrap modal上面使用的ueditor, 然后代码如下所示，
`$.getScript('../../assets/js/ueditor1_4_3/ueditorAdd2.config.js', function () {
            $.getScript('../../assets/js/ueditor1_4_3/ueditor.all.min.js', function () {
                $.getScript('../../assets/js/ueditor1_4_3/lang/zh-cn/zh-cn.js', function () {
                    UE.Editor.prototype.loadServerConfig = function () {
                        this._serverConfigLoaded = true;
                    };
                    //fue = UE.getEditor('feedback-container');
                    reformEditor();
                });
            });
        });
function reformEditor(){
    var uploadImageExtension = settingData.uploadImageExtension.split(',');
    for ( var i in uploadImageExtension) {
        uploadImageExtension[i] = '.' + uploadImageExtension[i];
    }
    var uploadMediaExtension = settingData.uploadMediaExtension.split(',');
    for ( var i in uploadImageExtension) {
        uploadMediaExtension[i] = '.' + uploadMediaExtension[i];
    }
    var uploadFileExtension = settingData.uploadFileExtension.split(',');
    for ( var i in uploadImageExtension) {
        uploadFileExtension[i] = '.' + uploadFileExtension[i];
    }
    var uploadImageMaxSize = settingData.uploadImageMaxSize * 1024 * 1024;
    var uploadMediaMaxSize = settingData.uploadMediaMaxSize * 1024 * 1024;
    var uploadFileMaxSize = settingData.uploadFileMaxSize * 1024 * 1024;

    var url;
    if(location.pathname.match('/i/')){
        url = '../assets/js/ueditor1_4_3/'
    }else{
        url = 'assets/js/ueditor1_4_3/'
    }

    fue = UE.getEditor('feedback-container', {
        toolbars : [ [ 'undo', 'redo', '|',
            'bold',  '|', 'forecolor',
            'cleardoc', '|', 'insertimage', '|'] ],
        wordCount: true, 
        maximumWords: 1000,
        UEDITOR_HOME_URL : url,
        imageActionName : "uploadImage",
        imageFieldName : "file",
        imageMaxSize : uploadImageMaxSize,
        imageAllowFiles : uploadImageExtension,
        imageUrlPrefix : "",
        imagePathFormat : "",
        imageCompressEnable : false,
        imageCompressBorder : 1600,
        imageInsertAlign : "none",
        videoActionName : "uploadMedia",
        videoFieldName : "file",
        videoMaxSize : uploadMediaMaxSize,
        videoAllowFiles : uploadMediaExtension,
        videoUrlPrefix : "",
        videoPathFormat : "",
        fileActionName : "uploadFile",
        fileFieldName : "file",
        fileMaxSize : uploadFileMaxSize,
        fileAllowFiles : uploadFileExtension,
        fileUrlPrefix : "",
        filePathFormat : ""
    });
}`

不知道是不是我使用的问题，因为看不出问题在哪儿，所以求各位大神指点指点

**Comment by NovaYuan** [comment]
在bootstrap modal 上面使用的ueditor, 代码使用如下

**Comment by NovaYuan** [comment]
在bootstrap modal 上面使用的ueditor, 不知道是不是我路径配置问题，求各位大神指导，代码使用如下
`$.getScript('../../assets/js/ueditor1_4_3/ueditorAdd2.config.js', function () {
            $.getScript('../../assets/js/ueditor1_4_3/ueditor.all.min.js', function () {
                $.getScript('../../assets/js/ueditor1_4_3/lang/zh-cn/zh-cn.js', function () {
                    UE.Editor.prototype.loadServerConfig = function () {
                        this._serverConfigLoaded = true;
                    };
                    fue = UE.getEditor('feedback-container', {
                         toolbars : [ [ 'undo', 'redo', '|', 'bold',  '|', 'forecolor','cleardoc', '|', 'insertimage', '|'] ],
                         UEDITOR_HOME_URL : 'assets/js/ueditor1_4_3/',
                });
            });
        });`
