### ISSUE TITLE
ueditor可以取json格式内容吗？

### ISSUE THREAD

**Issue by gaodengwu** [fex-team/ueditor#2574]
@Phinome  ueditor可以取json格式内容吗？我想取json格式内容提交到后台，ue有直接的方法吗？

**Comment by Phinome** [comment]
直接在内容区域内传输 `JSON` 是不行的，据我了解。如果一定要传输，那据我目前的了解，只有自定义参数了。[自定义参数](http://fex.baidu.com/ueditor/#dev-serverparam)
