### ISSUE TITLE
工具栏上添加的UE.ui.Button设置的label的字体大小不正确

### ISSUE THREAD

**Issue by xjfnet** [fex-team/ueditor#2577]
空白页面，仅有一个编辑器实例，工具栏上列表框，如自定义标题，段落格式等部分的文字大小为12px，通过UE.registerUI添加了一个UE.ui.Button，设置了label属性，文字显示出来了，没问题，左边是图标，右边是文字，但大小显示不是12px，通过cssRules设置也没有用，貌似cssRules没有作用在文字上。

**Comment by Phinome** [comment]
最好能给个demo
