### ISSUE TITLE
mac safari下， 某些情况无法选中文本

### ISSUE THREAD

**Issue by xukaifu** [fex-team/ueditor#2578]
如果editor的container距离页面top有一定距离，如600px时， 在Mac Safari中， 选中editor内的文本， 页面会快速滑动到页面底部，造成无法选中正在编辑的文本。 

在官网提供的demo基础上， <body> 后加几十个<br>就能复现此问题。

**Comment by Phinome** [comment]
看 #2570 ，这个可能是 Safari 的 bug。
