### ISSUE TITLE
关于video上传的问题。

### ISSUE THREAD

**Issue by onlyShadow** [fex-team/ueditor#2579]
`UE.plugins['video'] = function (){
    var me =this;

    /**
     * 创建插入视频字符窜
     * @param url 视频地址
     * @param width 视频宽度
     * @param height 视频高度
     * @param align 视频对齐
     * @param toEmbed 是否以flash代替显示
     * @param addParagraph  是否需要添加P 标签
     */
    function creatInsertStr(url,width,height,id,align,classname,type){
        var str;
        switch (type){
            case 'image':
                str = '<img ' + (id ? 'id="' + id+'"' : '') + ' width="'+ width +'" height="' + height + '" _url="'+url+'" class="' + classname.replace(/\bvideo-js\b/, '') + '"'  +
                    ' src="' + me.options.UEDITOR_HOME_URL+'themes/default/images/spacer.gif" style="background:url('+me.options.UEDITOR_HOME_URL+'themes/default/images/videologo.gif) no-repeat center center; border:1px solid gray;'+(align ? 'float:' + align + ';': '')+'" />'
                break;
            case 'embed':
                str = '<embed type="application/x-shockwave-flash" class="' + classname + '" pluginspage="http://www.macromedia.com/go/getflashplayer"' +
                    ' src="' +  utils.html(url) + '" width="' + width  + '" height="' + height  + '"'  + (align ? ' style="float:' + align + '"': '') +
                    ' wmode="transparent" play="true" loop="false" menu="false" allowscriptaccess="never" allowfullscreen="true" >';
                break;
            case 'video':
                var ext = url.substr(url.lastIndexOf('.') + 1);
                if(ext == 'ogv') ext = 'ogg';
               // str = '<embed src="http://www.ckplayer.com/ckplayer6.1/ckplayer.swf" flashvars="f=http://' + localhostPaht + url + '" quality="high" width="480" height="400" align="middle" allowScriptAccess="always" allowFullscreen="true" wmode="transparent" type="application/x-shockwave-flash">' + '</embed>'; 
                str = '<video' + (id ? ' id="' + id + '"' : '') + ' class="' + classname + ' video-js" ' + (align ? ' style="float:' + align + '"': '') +
                    ' controls preload="none" width="' + width + '" height="' + height + '" src="' + url + '" data-setup="{}">' +
                    '<source src="' + url + '" type="video/' + ext + '" /></video>';
                break;
        }
        return str;
    }`
以上代码是我从ueditor中看到的，我有个疑问，toEmbed 这个参数，是在什么情况下才能触发呢？要修改video.js中的代码吗？

**Comment by Phinome** [comment]
应该是参数没有更新导致的错误，`toEmbed` 是为了使用 `Flash` ，如果你要使用，将 `type` 的类型设置为 `embed` 即可。
