### ISSUE TITLE
simpleupload 能否支持选择多张图片上传？

### ISSUE THREAD

**Issue by xukaifu** [fex-team/ueditor#2580]
目前simpleupload只支持一张一张上传， 而多图上传的界面一下子又复杂了很多， 不想用。 有没有什么配置， 可以直接使用simpleupload选择多个文件上传呢？

**Comment by Phinome** [comment]
据我目前的了解，暂时没有方法，除非更改源代码，但当初`simpleupload`出现的目的就是简单、快速完成图片上传，并没有考虑到多图，这种比较复杂的操作。所以，如果你想多图上传，只能建议你自行修改代码了。
