### ISSUE TITLE
当本页面设了document.domain="xxx.com"时，会显示不了图片

### ISSUE THREAD

**Issue by bingbin** [fex-team/ueditor#2581]
域名为www.xxxx.com
页面设了基域名

```
document.domain="xxxx.com";
```

ueditor.config.js里也设置了
customDomain:true

但，上传图片时会提示“上传错误”

而图片实际上已经上传到了服务器了，只是插入不了编辑器。

细查了一下，是类似于垮域问题。
编辑器源码中，var body = (iframe.contentDocument || iframe.contentWindow.document).body;
这段取不到子框架iframe的对象，监控得知iframe.contentWindow.document发生错误Error: Permission denied to access property "document"

**Comment by bingbin** [comment]
类似问题好像一直存在，且不能得到解决
https://github.com/fex-team/ueditor/issues/205

**Comment by huash** [comment]
我现在也是这样的情况 设置过了document.domain单图上传就不行,现在暂时用多图的

**Comment by hanang128** [comment]
我也是这种情况，多图和单图都无法上传，请问多图是怎么解决的？ @huash

**Comment by huash** [comment]
修改dialogs/image里面的弹出页面里面设置一下document.domain就不会出错了 @hanang128

**Comment by jeremylzy** [comment]
@huash @bingbin  请问你们现在找到解决方法了吗，我遇到的问题跟你们一摸一样
