### ISSUE TITLE
 限制上传图片长宽问题

### ISSUE THREAD

**Issue by 0722jing** [fex-team/ueditor#2583]
如何对上传的图片的长宽作统一设置

**Comment by 0722jing** [comment]
我的想法是，我们在上传一张图片后，点击工具栏那上的HTML切换到源码时会看到<img src='...' alt='..' title='....'/> 这句源代码 如果在生成的时候 加上 width=‘100’ height=‘100’ 这样一个属性，就可以实现图片长宽的限制。可是我找不到生成这个<img 代码的相关源码，我猜想是js动态生成。另外我也不确定我这个限制上传图片长宽的思路对不对

**Comment by Phinome** [comment]
目前来看，没有提供这种限制。至于你添加宽高属性这个思路，不行，因为上传时的文件是读取文件的尺寸，而不是HTML 中的宽高。如果你只是想上传时限制，那就没法；而如果你是展现的时候限制，这个解决方法用 CSS 控制图片的宽高就行了。
