### ISSUE TITLE
在装了迅雷插件的safari中， 会被自动插入一段迅雷的代码， 有办法去掉吗？

### ISSUE THREAD

**Issue by xukaifu** [fex-team/ueditor#2587]
即便什么都不输入， 内容也会变成如下：
```html
<p>
<embed 
id="xunlei_com_thunder_helper_plugin_d462f475-c18e-46be-bd10-327458d045bd" 
type="application/thunder_download_plugin" 
height="0" 
width="0"/>
</p>
```

有办法能避免这个情况吗？

**Comment by Phinome** [comment]
试试禁用迅雷插件

**Comment by xukaifu** [comment]
禁用了就好了。 但是这个编辑器提供给用户使用， 没办法让所有用户都禁掉吧。 

可以在提交的时候自动过滤embed标签吗？

**Comment by Phinome** [comment]
不是所有用户都有迅雷插件吧？`embed` 标签 `flash` 要用啊，有些富媒体也需要 `embed` 标签。

**Comment by xukaifu** [comment]
@Phinome 你好。 我的意思是， 我的场景不需要flash和富媒体， 有什么方法提交时可以过滤embed吗？
即便是需要flash的， 有什么方法能在哪里加一段代码， 我自己写个方法过滤呢？
