### ISSUE TITLE
从外部复制进来的文本，当字体大小和编辑器默认字体大小相同时，字体大小格式就会无法保存

### ISSUE THREAD

**Issue by yanzi920403** [fex-team/ueditor#2588]
从外部复制进来的文本，当字体大小和编辑器默认字体大小相同时，字体大小格式就会无法保存。而当复制的文本字体大小和编辑器默认字体大小不相同时，就可以保存字体大小格式，希望尽快解决

**Comment by Phinome** [comment]
请先描述清楚你的问题，最好配上问题复现的步骤和截图。
