### ISSUE TITLE
UEditor -UBuilder 无法下载资源包

### ISSUE THREAD

**Issue by yifeiyuann** [fex-team/ueditor#2595]
提示如下，请帮解决：
UBuilder Error!
create temporary directory error!

**Comment by Phinome** [comment]
多谢反馈，这个问题后续会解决，目前没有时间来处理。

**Comment by GULW2010** [comment]
请问解决了吗？如果不ubuilder个小的，原始的js太大了。严重影响响应速度啊。

**Comment by Stuben** [comment]
同上，原js太大了

**Comment by Phinome** [comment]
近期会找时间来解决的，目前着急的用户，可以`git clone` UEditor 的仓库，然后在本地使用 `Grunt` 自行构建一份。

**Comment by sxlifeng** [comment]
http://ueditor.baidu.com/website/download.html#ubuilder 这里的builder现在还用不了么，记得很久之前是能用的，这次过来就不能用了

**Comment by Stuben** [comment]
是的   还不能用
