### ISSUE TITLE
公式编辑器不能输入

### ISSUE THREAD

**Issue by fuchun** [fex-team/ueditor#2596]
chrome浏览器，公式编辑器http://ueditor.baidu.com/website/kityformula.html
无法输入内容，错误：
Uncaught TypeError: target.node.getTransformToElement is not a function
Uncaught TypeError: Cannot read property 'mapping' of null
Uncaught TypeError: Cannot read property 'mapping' of null
Uncaught TypeError: Cannot read property 'mapping' of null
Uncaught TypeError: Cannot read property 'mapping' of null
Uncaught TypeError: Cannot read property 'mapping' of null
Uncaught TypeError: Cannot read property 'mapping' of null
Uncaught TypeError: Cannot read property 'mapping' of null
Uncaught TypeError: Cannot read property 'mapping' of null

**Comment by Phinome** [comment]
多谢反馈，这个好久没更新了，后续找时间更新一下应该就好了。

**Comment by fuchun** [comment]
现在还没更新，囧

**Comment by zxc7928932** [comment]
在kityformula-plugin\kityformula\js目录下的jquery-1.11.0.min.js的最后添加
SVGElement.prototype.getTransformToElement = SVGElement.prototype.getTransformToElement || function(elem) {
    return elem.getScreenCTM().inverse().multiply(this.getScreenCTM());
};这几行代码就好了

**Comment by zxc7928932** [comment]
在kityformula-plugin\kityformula\js目录下的jquery-1.11.0.min.js的最后添加
`SVGElement.prototype.getTransformToElement = SVGElement.prototype.getTransformToElement || function(elem) {
return elem.getScreenCTM().inverse().multiply(this.getScreenCTM());
};`
这几行代码就好了

**Comment by fuchun** [comment]
@zxc7928932 感谢 可以了
