### ISSUE TITLE
使用UMEditor时，拖拽缩放图片大小与bootsrtap.css（3.0.0和3.3.0）冲突

### ISSUE THREAD

**Issue by hk9039579** [fex-team/ueditor#2600]
问题如题，上传图片后，进行拖拽缩放，当仅调整宽或高时，另外一边(高或宽)会发生缩小，直至缩小到0。 经排查，当页面不引入bootstrap.css时，无此问题。 但是我方系统前端完全依赖bootstrap。。。该如何处理？

**Comment by Phinome** [comment]
能给个DEMO 么

**Comment by linda8167** [comment]
me too！！我也遇到了。这个问题真让人头疼！
