### ISSUE TITLE
word 导入功能在哪儿？

### ISSUE THREAD

**Issue by akene** [fex-team/ueditor#2601]
网站上写着2014年就有了，但我没找到类似ckeditor那样的按钮，粘贴进去后表格也是乱的。

**Comment by jiang79** [comment]
同样期待中

**Comment by Phinome** [comment]
之前开放的是功能是一个接口，但后来随着百度 doc 的上线，将功能转移至百度 doc 了，若有需求，欢迎使用[百度 doc](http://word.baidu.com/)

**Comment by web5** [comment]
感觉这个doc 导入 跟百度doc不冲突啊

**Comment by whucj** [comment]
上传word这么好的功能，怎么取消了？
