### ISSUE TITLE
图片搜索功能根本用不了，官网的deom也是报错的

### ISSUE THREAD

**Issue by ioriandy4** [fex-team/ueditor#2603]
![01](https://cloud.githubusercontent.com/assets/7553775/13345171/b7941034-dc97-11e5-9513-69a8621c1b4d.jpg)
如图，这个bug没人发现么？

**Comment by Phinome** [comment]
有人反馈了，多谢提出，后续会修复的。

**Comment by Phinome** [comment]
图片搜索的接口没有对外的了，所以暂时无解
