### ISSUE TITLE
前端解析无效

### ISSUE THREAD

**Issue by mengkeys** [fex-team/ueditor#2604]
# 前端解析无效

使用的是Node.js开发的网站, 前端引入ueditor.parse.min.js后，解析代码如下所示：

```
<script type="text/javascript" src="/ueditor/ueditor.parse.min.js"></script>
<script type="text/javascript">
$(function(){
   uParse('#content',{
       rootPath : '/ueditor'
   });
});
</script>
```

* 网站的所有静态资源都在public下，直接读取其下的文件或目录即可。
* 以上代码，在浏览器中打开前端页面时，无任何效果。

## 猜测可能：

*   rootPath错误（排除）

     浏览器没有报请求资源错误的提示

*   uparse.js没有引入（排除）

     如果没有引入的话，在页面加载完成后执行的代码中，应该要报uParse undefined，然而没有出现任何东西

就不知道是啥子原因了，请各位提点一下，小弟感激不尽

**Comment by Phinome** [comment]
能给个地址看看么？

**Comment by mengkeys** [comment]
目前没有放到公网，使用utils做了简单的处理，先将就着了
