### ISSUE TITLE
在排版编辑时，内容滚动条跳至顶，导致很不方便？

### ISSUE THREAD

**Issue by mx3000** [fex-team/ueditor#2608]
在排版编辑时，点击工具栏上功能按钮，编辑内容框中滚动条跳转至顶，致编辑时很不方便，每次都要找到刚编辑的地方，求解？求解决方案？

**Comment by naatgit** [comment]
在FF下也碰到这个问题，调试了下，是this.document.body.focuse()导致的，
     //FF下关闭自动长高时滚动条在关闭dialog时会跳
     //ff下如果不body.focus将不能定位闭合光标到编辑器内
     browser.gecko ? this.document.body.focus() : win.focus();
也不知道当时是为了fix什么bug加的，不对ff做特殊处理，就不会跳了。
