### ISSUE TITLE
恼人的多图上传（2）

### ISSUE THREAD

**Issue by Coca-code** [fex-team/ueditor#2613]
首先，本人是在一个小公司打工，薪水薄薄，那是用秋分瑟瑟来形容我的状况不为过，老板要求这个富文本编辑，于是搞，被一个多图上传的卡死了，提示“后端配置项目没有正常加载，上传加载没有正常使用！”
      于是各种大小写，路劲配置的帮助都试过，然，还是一样。
       在官方QQ群求帮助，需要银子，真有点百度公司的一向作风，于是，现在在等寻求在线帮助，或这换个其他的富文本编辑器了。

**Comment by Phinome** [comment]
目前问题很多，人力很少，所以，如果很着急，建议使用其它富文本编辑器，都是很优秀的。不然又要怪我厂作风了。

**Comment by iamfoxuriel** [comment]
单图片上传 是不是跨域的问题 现在似乎不支持

**Comment by gmood1985** [comment]
百度其他产品不清楚  但是ueditor的产品 俨然一副死猪不怕开水烫的模样
