### ISSUE TITLE
上传图片后怎么给图片加样式，或者更改图片显示的大小

### ISSUE THREAD

**Issue by czf910725** [fex-team/ueditor#2617]
上传图片后如果图片太大总是会超出，现在我想控制上传后图片的显示大小或者给图片加个样式（class），谢谢！！我的是ASP.NET的

**Comment by Phinome** [comment]
可以试试 `setStyle` 这个 API。具体文档参看：(http://ueditor.baidu.com/doc/#UE.dom.domUtils)[http://ueditor.baidu.com/doc/#UE.dom.domUtils]
