### ISSUE TITLE
二次开发时怎样创建和调用自己提供的icon图片？

### ISSUE THREAD

**Issue by wolf8210137** [fex-team/ueditor#2623]
今天做了一个小小的二次开发尝试，想定义自己的icon按钮，好像只有一个地方可以定义：
cssRules :'background-position: -747px 43px;', 
这里的CSS是使用默认的icons.png，我试了这样改background样式，但无效：
cssRules :'background:url("/js/ueditor/themes/default/images/memberflag.png") no-repeat 0 0;',
这里的memberflag.png是我自己为这个插件做的按钮，想引入但没效果。

后来只能把这个memberflag.png图标加入到UE默认的icons.png中，然后调整这里的定位才搞定。
请问在哪或什么参数可以指定自定义的插件按钮icon。
谢谢。

**Comment by lomotony** [comment]
同问
