### ISSUE TITLE
编辑器内容，图片文字点击选中，浏览器兼容问题

### ISSUE THREAD

**Issue by 12cm** [fex-team/ueditor#2635]
官网线上demo，在火狐，猎豹等浏览器上测试，并在编辑器上面编辑文字，然后点击上传图片到编辑器里，这时候，点击选中图片，然后再点击文字，会出现，一直是选中当前图片，却很难选中文字。

**Comment by Phinome** [comment]
嗯嗯，这是个问题，后续会修复的
