### ISSUE TITLE
ueditor 在线多图片上传时，搜索图片功能不能正常使用了，什么解决呢？

### ISSUE THREAD

**Issue by itsky365** [fex-team/ueditor#2637]
在使用ueditor多图片上传时，发现以前可以使用的百度图片搜索的功能，现在发现不能正常用了，提示301重定向的，针对此问题，能不能解决的？？

**Comment by Phinome** [comment]
应该是图片搜索的接口变化了，后续要看图片搜搜是否还提供了对外的接口。
