### ISSUE TITLE
是否有这样的一个API ，在编辑器插入图片只是一个预览效果，保存的时候在上传

### ISSUE THREAD

**Issue by lemonwlong** [fex-team/ueditor#2640]
编辑器插入图片，是否能不上传，只是一个预览效果，保存的时候在上传
是否已经有这个API？

**Comment by 3xxx** [comment]
对啊，本来就应该这样才对。支持。

**Comment by Phinome** [comment]
webuploader 应该有这个功能了，近期在做计划升级插件，后续应该会支持。
