### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by pangwa** [fex-team/ueditor#2642]
这个问题是在使用angular-ueditor中的过程中发现的, 就是如果动态的移除ueditor的instance的话, ueditor使用的内存是不会被释放的. 

这里有一些问题比如:
UE.instats 存的uedtior的实例不会被清空,
每一个编辑控件(e.g. button, toolbar)在销毁ue时不会被销毁, 同时因为这些控件一般也引用了ueditor的实例, 导致ueditor的内存也不会被释放.

另外我在尝试做一些fix, 等做好了发出来...

**Comment by Phinome** [comment]
加油~
