### ISSUE TITLE
如何在编辑里追加自己的控件按钮？

### ISSUE THREAD

**Issue by pshaoyi** [fex-team/ueditor#2647]
例：我在控件里面追加一个签名按钮事件，点击按钮会出现一下比较个性的签名内容，如百度贴吧的小尾巴一样。现在已把控件页面和控件按钮追加完成，遇到一个问题，如何把一段HTML内容插入到实例化后的编辑器里面，是否还需要追加其他JS事件和配置。

请告知一下，谢谢！

**Comment by Phinome** [comment]
这个 API 可能会帮助你[setContent](http://ueditor.baidu.com/doc/#UE.Editor:setContent(String,Boolean))
