### ISSUE TITLE
急！请问下，上传图片或文件时，怎么设置headers自定义参数呢？谢谢

### ISSUE THREAD

**Issue by wangcj10086** [fex-team/ueditor#2648]
急！请问下，上传图片或文件时(提交到后台时)，怎么设置headers自定义参数传到后台？谢谢

**Comment by Phinome** [comment]
看文档[自定义参数](http://fex.baidu.com/ueditor/#dev-serverparam)

**Comment by wangcj10086** [comment]
谢谢

发自我的 iPhone
