### ISSUE TITLE
百度统计代码阻塞ueditor初始化

### ISSUE THREAD

**Issue by kevgithub** [fex-team/ueditor#2649]
异步加载的百度统计代码会往header标签insertBefore一个script标签的方式加载统计脚本~/hm.js，而这个js文件貌似不会缓存，经常加载非常缓慢，有时甚至pendding很久不响应，不过由于是异步加载，倒也不影响页面其他脚本，唯独ueditor会受其牵连，一定要等到~/hm.js请求完成后ueditor才会初始化，严重影响功能使用，我测试了随便异步往页面写入一个script请求www.google.com，ueditor也会坚挺的等到这个请求失败才初始化，这真的是一个非常痛心疾首的问题！

**Comment by Phinome** [comment]
给个事例
