### ISSUE TITLE
推荐增加功能FC就有，只留下一个长传图片按钮，带进度条的图片上传

### ISSUE THREAD

**Issue by ymfqyd** [fex-team/ueditor#2661]
我是一个青岛的开发者，最近正再找网上所有的文本编辑器，进行比对和测试，从中选出最优的
发现以下问题
1.当我准备做一个评论框时，把所有的工具栏都取消掉，但是工具栏仍然是存在着，比较难看
2.上传图片过程中有时候会出现上传成功却提示错误的问题
3.文本编辑器到移动端大小自适应的问题

推荐功能，图片上传可以单独拿出来，作为一个单独的功能

**Comment by Phinome** [comment]
感谢使用，你要单独使用评论的话，推荐使用一些社会化的评论程序，至于说到上传图片的这个，如果仅仅是评论框，貌似有些评论框程序已经支持，直接使用就好了，如果单独需要上传功能，直接使用 webuploader 就好了。[传送门](http://fex.baidu.com/webuploader/)
