### ISSUE TITLE
修改编辑器回显数据之后加载不出来也不报错

### ISSUE THREAD

**Issue by xieqiujin** [fex-team/ueditor#2662]
要在编辑器内set内容  是要先set内容还是先加载编辑器，有时候从数据库查出来的数据set进去之后就加载不出编辑器，但是也不会报错

**Comment by Phinome** [comment]
在 `ready function` 中去执行 `set`

**Comment by xieqiujin** [comment]
@Phinome  我就是在ready function里面执行的set啊
