### ISSUE TITLE
UBuilder自定义下载报错！UBuilder Error! create temporary directory error!

### ISSUE THREAD

**Issue by a137160017** [fex-team/ueditor#2664]
UBuilder自定义下载报错！UBuilder Error! create temporary directory error!
请问下这个该怎么解决啊

**Comment by cherrieLu** [comment]
自定义下载确实报错UBuilder Error!
create temporary directory error!。
可是这里好像没有人回答。。。

**Comment by a137160017** [comment]
网上也没有解决方法。。

**Comment by Phinome** [comment]
目前建议 git clone 这个仓库，然后在本地 npm install , grunt 自行构建。后续会有个大的改版计划。
