### ISSUE TITLE
我要在链接里加电话链接tel:xxx-xxxxxxxx

### ISSUE THREAD

**Issue by machao1989** [fex-team/ueditor#2665]
总是给我加http: 这个真是自作聪明

**Comment by Phinome** [comment]
以前做的时候应该是没有考虑到这些特殊的协议的，所以默认把不识别的协议都转换成 http 协议了，你要着急，你可以把代码 clone 到本地，安装好 npm 和 grunt ，自行修改一下源代码。https://github.com/fex-team/ueditor/blob/dev-1.5.0/_src/plugins/link.js#L81，增加一个排除条件就行，最后，grunt 构建一下，就行了。
