### ISSUE TITLE
如何取消对 window 注册的 resize 方法?

### ISSUE THREAD

**Issue by tedpenk** [fex-team/ueditor#2666]
首先感谢 FEX 团队的辛勤工作！
以下是问题：

![image](https://cloud.githubusercontent.com/assets/7235487/13837689/c1aac368-ec48-11e5-88eb-93b57e958111.png)
这里给 window 注册了一个 resize 方法，还有一些地方也注册了 resize 方法。

问题是：我们的项目是放在 iframe 中的单页面程序，外部有菜单，在切换菜单时，iframe 长度会由 JS 自动计算，这时就会触发 resize 方法，并报一个错误：
![image](https://cloud.githubusercontent.com/assets/7235487/13837769/7275a1cc-ec49-11e5-800e-ca05f39400c6.png)
意思就是，在 isHidden() 方法中：
![image](https://cloud.githubusercontent.com/assets/7235487/13837791/a794a48e-ec49-11e5-978e-8cc3fdf57b94.png)
this.getDom() 由于此时 dom 节点已消失，所以获取为空，报了错，而 UE.dom.domUtils.un 方法中需要传入 handle 才能实现事件取消，但这个 handle 我没有办法获得，getListener 方法也没有像 API 文档所说提供给外部（这一点很不解）。

请问我该怎样取消 window 的 resize 方法，或通过其他方式解决该问题？

再次感谢！

**Comment by Phinome** [comment]
这个暂时无解，只有修改源代码，增加判断条件。这是个 bug，在后续的版本中会修复这种问题。

**Comment by tedpenk** [comment]
好的。
