### ISSUE TITLE
关于多图上传里的 在线管理问题

### ISSUE THREAD

**Issue by mr-yound** [fex-team/ueditor#2671]
![image](https://cloud.githubusercontent.com/assets/17938816/13895969/03bd1dc2-edb7-11e5-9872-a24b88953f70.png)

![image](https://cloud.githubusercontent.com/assets/17938816/13895974/1fd53094-edb7-11e5-9115-4617b63a420f.png)

![image](https://cloud.githubusercontent.com/assets/17938816/13895979/4165679c-edb7-11e5-98b2-88536308be5a.png)

地址在浏览器上可以加载到图片，为什么代码里却无法加载到图像？？？是我配置有问题吗？

**Comment by xfy217** [comment]
通过修改ueditor-1.1.2.jar包中FileManager类的getPath函数，因为路径分割符在linux和window不一样，导致返回路径是服务器上的物理路径。
修改前的getPath函数
 private String getPath(File file)
  {
    String path = file.getAbsolutePath();

    return path.replace(rootPath, "/");
  }
修改后的getPath函数
  private String getPath(File file)
  {
    String path = file.getAbsolutePath(); 
    path= path.replace("\\", "/");//云南零到一科技 add20160320
    rootPath=rootPath.replace("\\", "/");//云南零到一科技 add20160320 
    return path.replace(rootPath, "/");
  }

**Comment by mr-yound** [comment]
目前已解决，希望能在配置文件里配置下  不同系统不同参数

**Comment by Phinome** [comment]
后续版本里修复。
