### ISSUE TITLE
请问可以做到工具栏和编辑框分离的效果吗？

### ISSUE THREAD

**Issue by MonKong** [fex-team/ueditor#2673]
请问可以做到工具栏和编辑框分离的效果吗，效果如下。
![image](https://cloud.githubusercontent.com/assets/10125679/13902774/242c52da-ee93-11e5-9b66-1c42244b9bb6.png)

如果不可以，有其他富文本编辑器可以做到吗，求指点~

**Comment by Phinome** [comment]
目前不行，至于其它的，不太清楚。
