### ISSUE TITLE
给编辑器set数据时有时候不能正常加载

### ISSUE THREAD

**Issue by xieqiujin** [fex-team/ueditor#2674]
给编辑器set数据时有时候不能正常加载，有时候可以加载成功，有时候只是显示set到编辑器的数据，但是也不回报错 
代码如下

$(document).ready(function(e) {
	ue = UE.getEditor('container');
	getNewsTypes();
	GetNews();
	
	
	//GetNews();
	$(".return-gd").mouseenter(function(){
	$(this).css("color","#999999");
	})
	$(".return-gd").mouseleave(function(){
		$(this).css("color","#b4b4b4");
	})
	
	//返回 newsManage
	$(".return-gd").click(function(){
		window.location.href = "?func=newsManage";
	})
		
});	
	//查询单个新闻信息
	function GetNews(){
		 
		var args = [];
		args.push("newsId="+newsId+"");
		VeloCity.scriptDo(args,'site/news/GetNews.html', function(data){
				dwr.util.setValues({"title":data.Result.Title,"newsId":data.Result.Id,"newsType":data.Result.typeName,"container":data.Result.Context});
			});
	}

**Comment by Phinome** [comment]
在 UE.ready 的时候执行，而不是 dom ready 。[文档](http://fex.baidu.com/ueditor/)

**Comment by xieqiujin** [comment]
editor.addListener( 'ready', function( editor ) {
	 ue = UE.getEditor('container');
    
	GetNews();
 } );

可以这样吗

**Comment by Phinome** [comment]
```javascript
var ue = UE.getContent();
//对编辑器的操作最好在编辑器ready之后再做
ue.ready(function() {
    //设置编辑器的内容
    ue.setContent('hello');
    //获取html内容，返回: <p>hello</p>
    var html = ue.getContent();
    //获取纯文本内容，返回: hello
    var txt = ue.getContentTxt();
});
```
建议多看看文档。
