### ISSUE TITLE
本地自动保存关闭不了

### ISSUE THREAD

**Issue by buyue** [fex-team/ueditor#2677]
本地自动保存关闭不了
在ueditor.config.js设置enableAutoSave为false无效

**Comment by e2ghost** [comment]
我也遇到相同的问题，只好暂将自动保存时间调得很大

**Comment by Phinome** [comment]
你的意思其实是将 enableAutoSave 设置为 false 后，还会执行 autoSave.js 是么？目前调试来看就是这样，[代码](https://github.com/fex-team/ueditor/blob/dev-1.5.0/_src/plugins/autosave.js#L70)。如果是这个，那暂时没法，如果不是，请你描述清楚你的问题，最好图文。

**Comment by zengzhan** [comment]
1：禁止提示
UE.registerUI("autosave", function (a) {       
        if (a.options.enableAutoSave) { //加上
            var b = null, c = null;
2：屏蔽掉
 UE.plugin.register("autosave", function() {
 contentchange: function() {
                    //e && (b._saveFlag && window.clearTimeout(b._saveFlag),
                    //b.options.saveInterval > 0 ? b._saveFlag = window.setTimeout(function() {
                    //    a(b)
                    //}, b.options.saveInterval) : a(b))
                }
