### ISSUE TITLE
通过inserthtml插入的内容，怎么禁止在编辑器里再编辑？

### ISSUE THREAD

**Issue by hj007jacky** [fex-team/ueditor#2678]
通过inserthtml插入一个标准格式的内容，不想用户再次编辑该内容，如何设置禁止编辑

**Comment by Phinome** [comment]
[文档](http://ueditor.baidu.com/doc/#UE.Editor:setDisabled())

**Comment by hj007jacky** [comment]
文档中的内容是禁止某种类型（比如加粗，插入图片，修改文字样式）的编辑。我的意思是比如插入一个模版，禁止对模版的div进行编辑，只允许整体的删除这个模版。 @Phinome

**Comment by shy2850** [comment]
![image](https://cloud.githubusercontent.com/assets/2581100/14136211/2dc593e8-f694-11e5-870e-6581f338e46b.png)

**Comment by Phinome** [comment]
这样虽然不能编辑内容，但同时也不能删除。只能说目前 UEditor 没有提供方法去解决这个问题，需要你自行解决了。

**Comment by ustccjw** [comment]
测试：只要模块不是第一个插入的元素 contenteditable: false 是可以一起删除的（如果模块是 a 的元素话总是可以删除）。
ps. insertHtml + notNeedFilter
