### ISSUE TITLE
1.4.3.2  自动排版  bug

### ISSUE THREAD

**Issue by LB-DotFish** [fex-team/ueditor#2685]
使用自动排版   后直接提交  传递给后台的表单数据  仍是排版前的。。。
使用自动排版后  继续编辑内容  或者使用其他按钮 如草稿箱恢复、加粗、插入表情  等  提交数据是排版后的
可见自动排版未修改隐藏域

**Comment by shy2850** [comment]
我用ueditor也有几年了，发现官方好像没有RD维护了，所以最近我个人搞了一个版本准备带人维护， 是基于这里提交的1.5.0开发源码版本修改的。

github地址 [https://github.com/xhFE/XUeditor](https://github.com/xhFE/XUeditor)

你反馈的这个问题我刚刚加了一下，如果感兴趣可以试用一下我的版本，也欢迎直接issue给过来

demo 地址 [http://xueditor.webfuture.cn/_examples/completeDemo.html](http://xueditor.webfuture.cn/_examples/completeDemo.html)

**Comment by lvsenlin** [comment]
一键排版后，点一下正文就好了

**Comment by lvsenlin** [comment]
在ueditor.all.js大概10961行后加一行：
me.focus();
