### ISSUE TITLE
ueditor1.4.3视频上传成功后无法播放

### ISSUE THREAD

**Issue by hotpc001** [fex-team/ueditor#2691]
在ueditor1.4.3里视频上传成功，但是预览播放视时提示：
![image](https://cloud.githubusercontent.com/assets/16316419/14057832/0c8b6b6c-f347-11e5-8402-5a138a376a32.png)
用工具调试，提示
![image](https://cloud.githubusercontent.com/assets/16316419/14057837/2aa0296c-f347-11e5-9203-ea33e2b6329e.png)
请问怎么解决这个问题。谢谢！

**Comment by Phinome** [comment]
看第一个截图，可能是 Flash 版本的问题，换个浏览器或者 Flash Player 试试

**Comment by hotpc001** [comment]
我已经按网上baidu的方法，换了好几个 Flash 版本，并且在多台电脑上试用，还是一样的问题。

**Comment by hotpc001** [comment]
或者能不能给个正确的 Flash 版本下载地址。谢谢！

**Comment by hotpc001** [comment]
问题解决了，是上传的视频文件格式不对。建议组件做些验证，不能播放的格式就不让上传，能上传的就能播放，并把错误信息处理合理。

**Comment by Phinome** [comment]
校验只能保证文件类型是否是视频文件，只有在具体播放的时候才能知道该文件是否正常。
