### ISSUE TITLE
1.4.3 jsp版本，本地配置没有问题，部署在服务器上显示后端配置不正确加载配置文件错误

### ISSUE THREAD

**Issue by zoud** [fex-team/ueditor#2692]
1.4.3 jsp版本，本地配置没有问题，部署在服务器上显示后端配置不正确加载配置文件错误

**Comment by Phinome** [comment]
看看是不是路径的问题，java的那段代码对 windows 和 linux 的路径处理分割有点问题，没有处理 windows 的 '\' 路径分割。
