### ISSUE TITLE
图片上传的问题，不是路径配置问题

### ISSUE THREAD

**Issue by kissshot** [fex-team/ueditor#2693]
我用的是umeditor

我用node做后台接收图片res.json({ state: 'success', url: imgDir + '/' + file.name});这是上传成功后返回的数据.

在chrome控制台可以看到响应报文{"state":"success","url":"./resources/img/2016-03-28/45631376.png"}

我看了dialogs里的image.js，知道是用form  target="up" 做的提交，但是在name=“up”的ifram里显示的是

```
<html>
   <head>
      <style type="text/css"></style>
   </head>
   <body>
      <pre style="word-wrap: break-word; white-space: pre-wrap;">      {"state":"success","url":"./resources/img/2016-03-28/45931661.jpg"}
      </pre>
   </body>
</html>
```
然后下面做JSON解析的代码就抛出异常了
      var r = this.contentWindow.document.body.innerHTML;
         try{
                var json = eval('('+r+')');
                Base.callback(me.editor, me.dialog, json.url, json.state);
            }catch (e){
                var lang = me.editor.getLang('image');
                Base.callback(me.editor, me.dialog, '', (lang && lang.uploadError) || 'Error!');
            }

**Comment by kissshot** [comment]
我觉得改成var r = this.contentWindow.document.body.innerText;是不是就不会出错了

**Comment by Phinome** [comment]
做个正则匹配一下提取 `<pre>` 的内容，或者采用 body.textContent
