### ISSUE TITLE
ue.execCommand('insertHtml','<img id="img_index_1" style="max-width:500px;max-height:500px" src="base64的图片数据">');

### ISSUE THREAD

**Issue by OLSUN** [fex-team/ueditor#2694]
ue.execCommand('insertHtml','<img id="img_index_1" style="max-width:500px;max-height:500px" src="base64的图片数据">');
不显示任何内容呢？

**Comment by Phinome** [comment]
可能是转义掉了。[文档](http://ueditor.baidu.com/doc/#COMMAND::inserthtml)

**Comment by NightFullMoon** [comment]
该去掉的代码没有去掉，参考#2384
