### ISSUE TITLE
UMEditor编辑器添加图片地址怎么去掉域名

### ISSUE THREAD

**Issue by sijinglei** [fex-team/ueditor#2698]
UMEditor编辑器添加图片地址怎么去掉域名。。。。。。。。。。。。。。。。。。。。。

**Comment by Phinome** [comment]
自行修改代码吧。[https://github.com/fex-team/umeditor/blob/dev/dialogs/image/image.js#L12](https://github.com/fex-team/umeditor/blob/dev/dialogs/image/image.js#L12)，还有UM 的问题，去UM 的仓库提吧。
