### ISSUE TITLE
ueditor1.4.3 net版本，如何在点击“修改”-->"确定"  操作的时候，将远程图片下载到本地，“确定”按钮触发的是哪个方法

### ISSUE THREAD

**Issue by fengli2016** [fex-team/ueditor#2699]
ueditor1.4.3 net版本，如何在点击“修改”-->"确定"  操作的时候，将远程图片下载到本地，“确定”按钮触发的是哪个方法，我操作的时候进行监控也没找到调用的是哪个方法。请大师给予指点，谢谢！！！
!
![qq 20160331170903](https://cloud.githubusercontent.com/assets/18114236/14171235/7152af30-f764-11e5-9e15-2be19456b78a.png)
![qq 20160331170357](https://cloud.githubusercontent.com/assets/18114236/14171283/addd2bd8-f764-11e5-906b-f1389b48cbfe.png)

**Comment by Phinome** [comment]
参考[https://github.com/fex-team/ueditor/blob/dev-1.5.0/dialogs/image/image.js](https://github.com/fex-team/ueditor/blob/dev-1.5.0/dialogs/image/image.js)

**Comment by fengli2016** [comment]
能具体标注一下，点“确定” 按钮，触发的是dialogs/image/image.js  里的哪个方法吗？ 我找了好久都没找到，希望大神指引。谢谢啦！

**Comment by Phinome** [comment]
[https://github.com/fex-team/ueditor/blob/dev-1.5.0/dialogs/image/image.js#L87](https://github.com/fex-team/ueditor/blob/dev-1.5.0/dialogs/image/image.js#L87)
