### ISSUE TITLE
UEditor-1.4.3.2-JSP-UTF-8-如何把图片上传到指定的服务器，或者把图片直接存入数据库-并且要正确回显

### ISSUE THREAD

**Issue by qk1107899648** [fex-team/ueditor#2700]
如题，这个问题我看好多人都遇到了，但是没有好的解决方案，可能会面临如下问题
1，当我们的项目很大的时候，如果把图片都放在网站的项目目录下，到时候项目会很大，很难维护。
2，当有多台服务器部署项目的时候，不同主机间图片访问会有问题。

我现在有成熟的图片长传的方法，但是不知道如何代替UE的图片上传。

有会的大神还望指教，

**Comment by qk1107899648** [comment]
这个问题是好多人都遇到的问题，但是都没能很好的解决，希望能在这里得到答案。

**Comment by Phinome** [comment]
可以参看一下文档的配置[http://fex.baidu.com/ueditor/#server-jsp](http://fex.baidu.com/ueditor/#server-jsp)，至于具体的实现，应该是具体业务来实现。
