### ISSUE TITLE
与jqgrid使用时的问题

### ISSUE THREAD

**Issue by dtueditor** [fex-team/ueditor#2702]
已在jqgrid中成功应用，但有个问题，首次加载时加当前行内容，关闭编缉表单后，定位其它行，再打开编缉表单，能加载当前行，但会被初始内容履盖。如何处理?

**Comment by Phinome** [comment]
图文描述一下吧

**Comment by dtueditor** [comment]
官网实例。多个编辑区使用一个编辑器实例在ie11下，切换编辑区时不能更新编揖内容。

**Comment by dtueditor** [comment]
jqgrid的问题与此类似

**Comment by dtueditor** [comment]
已完美解决；不是ueditor的问题
if (rowid !== "_empty") {
                    $.each($t.p.colModel, function () {
                        if (this.edittype === "editor") {
                            var name = this.name;
                            var ready = function () {
                                this.setContent($($t).jqGrid("getCell", rowid, name))
                                this.removeListener('ready', ready)
                            }
                            UE.getEditor(name).addListener('ready', ready)
                        }
                    });
                }

**Comment by dtueditor** [comment]
先立后破！
