### ISSUE TITLE
https2.0 多图上传和上传文件时，cookie丢失

### ISSUE THREAD

**Issue by lvsenlin** [fex-team/ueditor#2720]
打印服务器上收到的headers，user-agent和cookie都是Null
关闭https2.0或者换到不支持htpps2.0的浏览器，cookie就不会丢失了

**Comment by Phinome** [comment]
http2 ，都这么快了。。。后续看看怎么针对 http2 调整

**Comment by lvsenlin** [comment]
http2的header稍有不同，header name都是小写。
web服务器是nginx，打印的时候发起user-agent是null，cookie直接没有

**Comment by Phinome** [comment]
UA 都没有，那是不是你 Nginx 配置的问题？

**Comment by lvsenlin** [comment]
不会的，其它请求都没掉
我们现在换成插件上传了，不麻烦了
