### ISSUE TITLE
ueditor 插入input标签,type='text',文本框中输入内容，获取编辑器html内容时没有取到输入的input中的内容

### ISSUE THREAD

**Issue by mzzd08113** [fex-team/ueditor#2724]
ueditor 插入input标签,type='text',文本框中输入内容，获取编辑器html内容时没有取到输入的input中的内容

**Comment by Phinome** [comment]
获取编辑器的内容都是获取 html ，而要获取 input 的内容，要取其 value 。所以获取不到。
