### ISSUE TITLE
umeditor上传图片问题

### ISSUE THREAD

**Issue by fred1653** [fex-team/ueditor#273]
后台已经上传图片，并且按照格式向前台输出了json。
{"name":"13820688966832.jpg","state":"SUCCESS","original":"13820688966832.jpg","type":".jpg","url":"image\/13820688966832.jpg","size":132532}

但是前台一直显示上传出错，
config.js修改的地方:
        ,imageUrl:"/topic/imageUP"             //图片上传提交地址
        ,imagePath:URL                     //图片修正地址，引用了fixedImagePath,如有特殊需求，可自行配置
        ,imageFieldName:"upfile"

**Comment by zhangrm** [comment]
查看 http://blog.csdn.net/dreamerframework/article/details/22392151

**Comment by overtrue** [comment]
@zhangrm 谢谢，后来换了其它开源组件，感觉这太不标准了用起来别扭。感谢！

**Comment by csjc008** [comment]
bug 这么久了在umeditor里面还是没有解决...百度前端这开发质量啊...基础功能都留大bug...无语

**Comment by ShylockGou** [comment]
@csjc008 就靠你来提pull request 了

**Comment by csjc008** [comment]
@ShylockGou 网上随便一搜都是ok的解决方案...我提无非copy测一下而已,已经fix掉用在自己工程里了, 身为一个后端rd被逼改这种前端组件的bug是怎样一种体验啊. 我奇怪的是官网上最新版本还是这个bug, 为什么这个issue被close掉了? 标记为历史版本? 历史个毛啊? 标题是umeditor不是ueditor
