### ISSUE TITLE
ueditor没有直接支持图片上传到外部服务器？

### ISSUE THREAD

**Issue by Fourwenwen** [fex-team/ueditor#2734]
各路大神好，公司项目用的是ueditor。因初始项目都没有弄图片上传这个需求。现在产品让加上。我是刚到这家公司，也是第一次接触ueditor，现发现图片我们是放在外部服务器。貌似ueditor原没有直接支持上传图片到外部服务器。
后来我重新了部分方法实现了这个功能。是不是本来就没有设计这个上传图片到外部服务器呢？

**Comment by hechaos** [comment]
你好，想请教下，这个是怎么实现的？我这边也要把图片传到外部服务器，可是一直没搞出来。图片是传过去了，可是输入框里显示 上传失败，也没有图片。能分享下你的经验么？

**Comment by Fourwenwen** [comment]
因为项目中已有其他页面也用了ueditor，所以我不能直接吸怪ueditor的代码。好让我难做。
最后我复写了一些方法：
//复写UEDITOR的getActionUrl 方法,定义自己的Action
	UE.Editor.prototype._bkGetActionUrl = UE.Editor.prototype.getActionUrl;
	UE.Editor.prototype.getActionUrl = function(action) {
	    if (action == 'uploadimage' || action == 'uploadfile') {
	    	   return '${ctx }/pic/uploadPicByUe';   //图片上传路径
	    } else {
	        return this._bkGetActionUrl.call(this, action);
	    }
	};
返回的数据是json格式：
result.put("state", "SUCCESS");// UEDITOR的规则:不为SUCCESS则显示state的内容
result.put("url",imgUrlPath);
result.put("title", originalFilename);
result.put("original", originalFilename);
return JSON.toJSONString(result);
主要是这个方法，放在你实例出var ue = UE.getEditor(...);后面就可以了。
希望能帮到你。

**Comment by sirtener** [comment]
请问，问题解决与否？我也有同样的疑问：内容图片或其他附件存放位置不在web应用机器，而是存放在局域网中的其他单独的文件机器上，这个是否支持？如果请求通过nginx转发到内部局域网，这又该如何处理？谢谢。

**Comment by Fourwenwen** [comment]
按照我上面所写的，然后在后端返回json数据中url返回连带上域名，一个完整http连接返回去。这样不可以？

**Comment by sirtener** [comment]
但是，ueditor初始化的时候就要填写这个存储路径的（完整的访问路径前部分）

**Comment by IsResultXaL** [comment]
我现在也要解决这个问题，试试楼主的方法

**Comment by ElysionK** [comment]
我也和楼主一样重写了action方法, 图片是上传到服务器去了, 但是返回值一直是服务器返回错误.
`result.put("state", "SUCCESS");// UEDITOR的规则:不为SUCCESS则显示state的内容
            result.put("url",savePath);
            result.put("title", fileNames[0]);
            result.put("original", fileNames[0]);`

我是直接返回了这个hashmap   哪里出问题了 ,

**Comment by Fourwenwen** [comment]
要返回json数据。上面只是我的一种封装json数据写法而已，因为懒，所以直接把代码截出来。

**Comment by ElysionK** [comment]
已经搞定了 ,~   转了json还不行后来发现是还没有返回框架支持的格式 ,  现在可以了 ,谢谢楼主

**Comment by tinkerJ** [comment]
@ElysionK 请问一下,框架支持的格式是指什么?

**Comment by ElysionK** [comment]
@tinkerJ  重写的action应该返回json就可以了 , 我说的框架只是我的项目里需要再做些处理,

**Comment by tinkerJ** [comment]
@ElysionK 谢谢,不知道有没有遇到过上传图片400错误的问题

**Comment by ElysionK** [comment]
@tinkerJ 没有哦,

**Comment by Fourwenwen** [comment]
@tinkerJ 你会不会后台设置了必传参数，但是前台没有传过去。你看看是不是这个原因导致400错误。

**Comment by andyzty** [comment]
我现在也出现了这个问题，上传一直会出现报错？
还有如果上向后台url传图片时，还需要传入别的参数，但这个参数是个变值，我改怎么配置？？
