### ISSUE TITLE
ueditor自动保存

### ISSUE THREAD

**Issue by lqzt** [fex-team/ueditor#2737]
求助：UE编辑器怎么实现自动保存功能？（备注：自动提交到指定的url、或者执行自己写的方法）

**Comment by lqzt** [comment]
自动保存

**Comment by Phinome** [comment]
UEditor 对外暴露了两个 event ： `beforeautosave` 和 `afterautosave` ，如果觉得不够，可以自行扩展`autosave.js` [文件](https://github.com/fex-team/ueditor/blob/dev-1.5.0/_src/plugins/autosave.js)
