### ISSUE TITLE
重写多图上传服务器方法的返回格式问题

### ISSUE THREAD

**Issue by ElysionK** [fex-team/ueditor#2747]
用官网的方法重写了getActionUrl方法,图片已成功上传服务器
但是有个问题, 不管在本地测试还是上传服务器, 上传完后都出现服务器返回错误的提示

![image](https://cloud.githubusercontent.com/assets/16201947/14874686/5d649466-0d35-11e6-894f-3719bfbf28dc.png)

方法的返回值如下
`{"title":"nopicbg.jpg","state":"SUCCESS","original":"nopicbg.jpg","url":"D://ykpfImg/product/supplementImg/20160428/007059_nopicbg.jpg"}`

源码执行到这里就报错了,
![image](https://cloud.githubusercontent.com/assets/16201947/14874716/9abf3190-0d35-11e6-8f3d-d42990f57024.png)

请问如何解决

**Comment by ElysionK** [comment]
已经搞定了 ,

**Comment by bigxu** [comment]
@ElysionK 一样重写了。一样的错误。单个图片上图正常，多图上传出错。请兄台示下？
