### ISSUE TITLE
右键菜单 contextMenu 增加一个item

### ISSUE THREAD

**Issue by h0730303779** [fex-team/ueditor#2752]
请问谁知道怎么在原来的基础上怎么家一个item??? 自己直接操作 contextMenu:[....] 里面只有我写的那个了

**Comment by Phinome** [comment]
参看文档[contextMenu](http://fex.baidu.com/ueditor/#start-config) ，可以参考 `可以参考plugins/contextmenu.js里边的默认菜单的例子`
