### ISSUE TITLE
使用pjax 后ueditor无法显示

### ISSUE THREAD

**Issue by Messilimeng** [fex-team/ueditor#2755]
用pajx点击 <a> 后页面editor 不显示 也不报错

**Comment by mingbai2006** [comment]
我遇到了同样的情况，后来是解决的
`
if(ue){
  ue.destroy();
}
var ue = UE.getEditor('myEditor');`

**Comment by Messilimeng** [comment]
@mingbai2006  非常感谢

**Comment by Messilimeng** [comment]
@mingbai2006  然后js报错  UE is not defined 是什么情况 有可以有你qq吗

**Comment by mingbai2006** [comment]
你得在pjax的影响范围之外引入ueditor的js

**Comment by Messilimeng** [comment]
@mingbai2006 配置好了乱点 还是会报错ueditor.all.js:6829 Cannot read property 'parentNode' of undefined

**Comment by Phinome** [comment]
把控制台的报错信息截个图来看看。 @Messilimeng

**Comment by Messilimeng** [comment]
我的asp.net mvc4 框架  用了模板页 结构如下
![a623 tmp](https://cloud.githubusercontent.com/assets/12272166/15201338/a7856f64-1822-11e6-8b44-b01cbcb42564.jpg)
在子页面 引用
@{
    if (Request.Headers["X-PJAX"] != null && bool.Parse(Request.Headers["X-PJAX"]))
    {
        Layout = null;
    }
    else {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
} 

报错信息 会变化 点击了几次编辑器就不见了
![b4ac tmp](https://cloud.githubusercontent.com/assets/12272166/15201362/d94eab8c-1822-11e6-8f62-f08ade0fbec0.jpg)
![b4ac tmp](https://cloud.githubusercontent.com/assets/12272166/15201373/e61d769a-1822-11e6-986c-3ed4c4c196be.jpg)

**Comment by Phinome** [comment]
你的 `UEditor` 的 container 是在 `#container` 里么？如果是的话，依照你目前给出的信息来判断：那么有可能是UEditor 创建的时候所需要的节点还未挂载到 DOM 中去。有如下两个建议：

1. 看一下 `me.container` 是那个元素，是否已经挂载到 DOM 里；
2. 查一下 Pjax 是否有 ready 事件，将 UEditor 的初始化放到 ready 中；

**Comment by Messilimeng** [comment]
@Phinome  不好意思 我也不太了解pjax  的原理 还在学习中 这是他的 github 地址https://github.com/defunkt/jquery-pjax  我的 UEditor  是放在 #container 里的  第一次点击是没有问题的 但是多次连击这个页面 就会出现那些问题

**Comment by dryyun** [comment]
@Messilimeng ，你这个问题，最后解决了么，我的现象是，pjax 第一次加载 ueditor 的时候，是可以显示的，以后的操作就不显示了。

**Comment by Messilimeng** [comment]
@dryyun 是的呢 就是这样的情况

**Comment by dryyun** [comment]
@Messilimeng  然后就没有解决么 ？

**Comment by mingbai2006** [comment]
@dryyun @Messilimeng 我解决了，方法就是把UEditor的加载放在pjax的影响范围之外，比如放在head里，然后用这段代码在pjax中初始化ueditor
```
 if(ue){ 
     ue.destroy(); 
 }
 var ue = UE.getEditor('myEditor');
```

这个问题不是ueditor引起的，而是pjax，在pjax中用<script src="...">这种方式引入JS代码会被缓存，只有第一次生效，再次打开就无效了，所以只能把UEditor的加载放在pjax之外

**Comment by Messilimeng** [comment]
@mingbai2006 有空我试试  这个太好了

**Comment by Messilimeng** [comment]
@mingbai2006 有没有demo可以看一下啊？
