### ISSUE TITLE
14px 字号切换无效

### ISSUE THREAD

**Issue by kaizhuQin** [fex-team/ueditor#2761]
下拉选择的字号有 10, 11, 12, 14, 16, 18, 20, 24

但是无效切换到 14号字体。

如果当前字号为12 选择文字切换到14 会自动切换到12
如果当前字号为16 选择文字切换到14 会自动切换到16

其他字号正常，就是无法切换到14号字体。

**Comment by Phinome** [comment]
并没有发现你说的现象

**Comment by ArvinRong** [comment]
我用的版本也发现了这个问题，me.addOutputRule方法中增加14的定义后才可用，0位置的字号不可选，因为用不到，暂时没去查。
` case 'size':
 var val =  node.attrs[p];
                            $.each({
                            	 '9':'0',
                                 '12':'1',
                                 '14':'2',
                                 '16':'3',
                                 '18':'4',
                                 '24':'5',
                                 '32':'6',
                                 '48':'7'
                            }`
