### ISSUE TITLE
话说, 汇报bug有厂商的人认领吗, 发现了几只bug

### ISSUE THREAD

**Issue by dailinyuan** [fex-team/ueditor#2762]
ueditor 是我前几年都一直关注的一个富文本编辑器, 同时 echarts,脑图等也都使用过, 百度的技术一向是非常不错的 .
ueditor 比起其他的编辑器, 功能更多, 效果也很不错, 每个版本都在做的更加完善和优秀, 然而, 总有那么一些令人不悦的bug, 而且这些bug并不难以发现 .
就想问问, 在这里提出的bug会被修正吗 , 如果没人管的话就不提了 = = ,

**Comment by code4funlnyx** [comment]
先提出来再说嘛

**Comment by seancheer** [comment]
对啊，如果官方不解决的话，我们民间人士可以研究研究，说不定就给修复了。

**Comment by Phinome** [comment]
有问题，就提吧，欢迎~

**Comment by jingpinsj** [comment]
有些民间人士却无法修改，比如图片、音尔的搜索功能用不了。

**Comment by lomotony** [comment]
@Phinome 你是百度团队的？

**Comment by Phinome** [comment]
@jingpinsj 那些接口都发生变化了，没有对外的API提供了，所以没法修改。后续会下掉。欢迎提其它的问题。
