### ISSUE TITLE
UE, 在firefox浏览器中, 附件-在线附件的文件名称显示不全

### ISSUE THREAD

**Issue by dailinyuan** [fex-team/ueditor#2769]
firefox 46.0.1
官方示例 http://ueditor.baidu.com/website/onlinedemo.html
点击附件->在线附件, 发现文件名称下半部分被截断

在ie11中未发现此问题 

有人遇到这个问题吗 ?

**Comment by Phinome** [comment]
排查了一下，浏览器兼容性的问题，多谢反馈。
