### ISSUE TITLE
UE, 在firefox浏览器中, 图片上传焦点获取问题

### ISSUE THREAD

**Issue by dailinyuan** [fex-team/ueditor#2770]
firefox 46 , 在官方示例中发现
上传单张/批量图片之后, 点击某张图片时该图片无法获得焦点
例如, 上传了2张图片, 点第二张图片时, 该图片会获得焦点, 显示快捷操作, 但是单击第一张图片时, 还是第二张图片获得了焦点, 显示快捷操作 .
在ie11中未发现此问题
在UM中未发现此问题

有人遇到和我一样的问题吗 ?

**Comment by Phinome** [comment]
这个是一个bug，一直还没有时间来修复。
