### ISSUE TITLE
关于 UMeditor 插入地图的bug解决方案

### ISSUE THREAD

**Issue by xiaoerbao** [fex-team/ueditor#2771]
1.4.3.2版本的umeditor 无法插入地图，官方演示也是如此。
会报一个错误：

> Uncaught TypeError: Cannot read property 'lng' of undefined

解决方案，找到dialogs/map/map.js
拉到最下面234行。button->ok->exec方法中，定义的point

> var widget = editor.getWidgetData(widgetName),
>                         center = widget.map.getCenter(),
>                         zoom = widget.map.getZoom(),
>                         size = widget.map.getSize(),
>                         point = widget.marker.P;//此行存在错误，P不存在

将point改成如下：

> point = widget.marker.point;//这样即可解决该bug

**Comment by maxwelltan** [comment]
非常感谢！改了过后好使了
