### ISSUE TITLE
addlistener以后无法再次之行回调

### ISSUE THREAD

**Issue by sixersun** [fex-team/ueditor#2775]
//seajs.use 方法引入ueditor后执行
$(this).click(function(){
                        var content = $("#text-content").val();//会发生改变
                        editor.addListener('ready',function(){
                            editor.setContent(content, false);//设置编译器的内容值
                        });
});
第二次click之后editor.setContent没有执行

**Comment by Phinome** [comment]
ready 只有一次，不会触发两次，所以你这样写有问题。
