### ISSUE TITLE
listImage操作的url配置，只能通过默认的controller.php吗?

### ISSUE THREAD

**Issue by nick198205** [fex-team/ueditor#2777]
周末使用了下Ueditor，各方面都很不错。只是有一个小问题，我现在的需求是**通过php接口动态生成各个用户要拉取的在线图片管理列表，而不是一个同样的目录所有人在一个目录下拉取**，我尝试在`conf.js`里配置`imageManagerListPath`为我的接口地址，但在chrome里调试发现ue还是请求默认的`controller.php`.     
现在，我已经在`controller.php`中单独写了根据用户id实现只拉取自己的imageList的方法，但本着好奇心，想知道到底能否直接配置listImage的请求url为自定义的动态接口地址。     
我已经详细阅读了官方文档，没有找到，用google没有搜到，在Issues里也没有翻到，所以才问一下。    
Thanks!!!

**Comment by Phinome** [comment]
修改 serverUrl，参看[https://github.com/fex-team/ueditor/blob/dev-1.5.0/ueditor.config.js#L33](https://github.com/fex-team/ueditor/blob/dev-1.5.0/ueditor.config.js#L33)
