### ISSUE TITLE
如何给粘贴到ueditor编辑框里面的图片自动加上长和宽

### ISSUE THREAD

**Issue by 1021382311** [fex-team/ueditor#2782]
默认上传图片的时候，对应的html代码是这样的
img src="/ueditor/php/upload/image/20140722/1406040023503428.jpg" alt="1406040023503428.jpg"/

我想让它这样，
img src="/ueditor/php/upload/image/20140722/1406040023503428.jpg" alt="1406040023503428.jpg" width="291" height="164" style="width: 291px; height: 164px;"/

就是宽度和高度的属性我想它自动加上，怎么做啊？文档没看到

**Comment by Phinome** [comment]
自己写获取宽高的方法，然后修改这里[https://github.com/fex-team/ueditor/blob/dev-1.5.0/_src/plugins/simpleupload.js#L71](https://github.com/fex-team/ueditor/blob/dev-1.5.0/_src/plugins/simpleupload.js#L71)
