### ISSUE TITLE
Hi,团队的各位大佬能不能为 Mantis 开发一个插件？

### ISSUE THREAD

**Issue by mullerlxl** [fex-team/ueditor#2791]
现在 Mantis 富文本插件只有 BBCode。ueditor 比 BBCode 强大多了。但是部署太费事了。到现在依然存在问题。

恳请肯为大佬帮忙封装成 MANTIS 插件可以吗？

**Comment by Phinome** [comment]
什么鬼？

**Comment by mullerlxl** [comment]
额~Mantis是个BUG管理工具。PHP开发的预留了二次开发插件接口。苦于自己不了解拍黄片所以跪求各位老大~~

这玩意，虽说丑了点。但是还算好用！原生版本不支持富文本编辑。仅有的第三方插件BBCode，可以让Mantis支持富文本编辑。可是太难用了。

所以希望老大如果有时间可以用ueditor 给Mantis 开发一个富文本插件。

下面这个地址是Mantis目前开源插件Git库
https://github.com/mantisbt-plugins
希望老大能帮忙添砖加瓦~~

**Comment by Phinome** [comment]
无解，我先不关这个，看社区有没有人愿意来做吧。
