### ISSUE TITLE
通过word导入方式的图片设置问题

### ISSUE THREAD

**Issue by marsch99** [fex-team/ueditor#2807]
在word中插入的图片分辨率都比较大，比如有15.96cm*10.56CM（这是word里的图片大小尺寸），通过导入word的方式导入后，这个图片的宽度和高度就变成了604*403px。大致的宽高比是没有变，问题是：如何配置能使，导入到编辑框中的图片按照指定的分辨率压缩呢？是要在word中就调整好吗？ 谢谢

**Comment by Phinome** [comment]
word 推荐使用[百度doc](http://word.baidu.com/)
