### ISSUE TITLE
弹窗问题能否设置成该弹窗以外区域不能点击？

### ISSUE THREAD

**Issue by riyunzhu** [fex-team/ueditor#2808]
弹窗问题能否设置成该弹窗以外区域不能点击？如上传视频的的弹窗对话框，特别是对于视频之类的大文件，上传需要较长时间，如果在等待上传的过程中鼠标不小心点击了弹窗的区域，上传弹窗就被关闭，文件就需要重新上传。

**Comment by niunan** [comment]
同求。

**Comment by Phinome** [comment]
把这行注释掉就可以了。[https://github.com/fex-team/ueditor/blob/dev-1.4.3.3/_src/ui/dialog.js#L53](https://github.com/fex-team/ueditor/blob/dev-1.4.3.3/_src/ui/dialog.js#L53)
