### ISSUE TITLE
Ueditor插入视频无法在微信和移动端的浏览器播放吗？

### ISSUE THREAD

**Issue by SeanPass** [fex-team/ueditor#2811]
插入后的代码如下：
    `<embed type="application/x-shockwave-flash" class="edui-faked-video" pluginspage="http://www.macromedia.com/go/getflashplayer" src="http://test-resources.dorlor.com/20160521_161759_23690_L2_1920_3_25.mp4" width="420" height="280" wmode="transparent" play="true" loop="false" menu="false" allowscriptaccess="never" allowfullscreen="true"/>`
请问使用UEditor编辑器，如何在移动端和微信下面播放呢？

**Comment by riyunzhu** [comment]
可以看下html5的video标签，你这种代码是需要flash插件的。手机浏览器现在基本上不支持flash插件了

**Comment by zuihou** [comment]
好像微信会屏蔽掉

**Comment by 811239386** [comment]
同上怎么解决的？

**Comment by linsiming** [comment]
同上，有人解决了么？
