### ISSUE TITLE
beego 框架下，编辑器内容会多出引号

### ISSUE THREAD

**Issue by QiiSyhx** [fex-team/ueditor#2813]
页面代码

<script  type="text/plain" id="contents" name="contents" style="height:300px;">{{.info.Contents|html2str}}</script>

我在后台打印出内容：

<p>asdfsdfsdf</p>

前台输出：

<p>
    &quot;asdfsdfsdf&quot;
</p>

编辑器显示内容：
"asdfsdfsdf"
在页面其他地方输出，比如我输出到div里面：

<p>asdfsdfsdf</p>

会多出来一对引号，没有找到问题所在。
编辑器代码，我整合到require里面，我在tp框架下使用，都没有这个问题，我移植到beego框架下，只是改过配置文件里面的上传文件的url，其余相同。

**Comment by 3xxx** [comment]
https://github.com/3xxx/UEditor-golang
我的似乎没这个问题。

**Comment by QiiSyhx** [comment]
很奇怪，不知道是什么原因导致的，我现在是这样解决这个问题的。
`var ue = UE.getEditor("contents");
										ue.ready(function(){
											ue.setContent('{{.info.Contents|html2str}}')
										})`
