### ISSUE TITLE
这是ueditor内存泄露么？我是小白，轻喷

### ISSUE THREAD

**Issue by No2015** [fex-team/ueditor#2816]
ueditor编辑器执行删除destroy的时候，似乎有一个iframe没有删除，结果是每次执行了destroy之后再实例化新的UE的时候，会保留一个iframe，结果是页面的子window对象会越来越多。感觉似乎造成了内存的...泄露？

**Comment by Phinome** [comment]
可以这么说，但这个的影响也没有那么夸张。因为如果不停地 GC ，本身也是种浪费。
