### ISSUE TITLE
UE编辑器BUg

### ISSUE THREAD

**Issue by TheBirdies** [fex-team/ueditor#2818]
(火狐浏览器)
1.富文本编辑器 文字和图片对齐的时候每次都自动跳到顶部 （全屏的时候出现）
2.选择完图片 想编辑文字时候，光标切不回来，一直停留在操作图片的位置

**Comment by TheBirdies** [comment]
火狐浏览器出现此问题

**Comment by YFengFly** [comment]
第一点问题 +1
版本：1.4.3
即使在Demo页面也有这个问题...233....
http://ueditor.baidu.com/website/onlinedemo.html
