### ISSUE TITLE
在任意标签前回车都会自动复制回车该标签，包括属性

### ISSUE THREAD

**Issue by regboy** [fex-team/ueditor#2819]
例如，我的编辑器内容为：
`<h1 id="test">
    我是H1
</h1>`
我把光标放在我前回，然后回车，编辑器会生成以下内容：
`<h1 id="test">
    <br/>
</h1>
<h1 id="test">
    我是H1
</h1>`
这个是BUG么？ 如果我只是想在回车后生成一个P标签，如下面这样：
`<p>
    <br/>
</p>
<h1 id="test">
    我是内容
</h1>`
请问要如何做？

**Comment by Phinome** [comment]
先换行，在将内容变成 h1 吧。至于这个算不算 bug ，这个还有待商榷。
