### ISSUE TITLE
图片居中报错，官方的列子也一样

### ISSUE THREAD

**Issue by ct-sliver** [fex-team/ueditor#2820]
官网和我做的列子都出现了图片居中的时候报错 Uncaught TypeError: Cannot read property 'removeAttribute' of null，图片的左对齐和右对齐都没有问题，就是居中的时候报错，并且居中不了，官方网站的列子也是一样

**Comment by Phinome** [comment]
可能是之前修复 Bug 的时候引起的，已经修复了。你再试试。
