### ISSUE TITLE
xss过滤完全是一大坑啊

### ISSUE THREAD

**Issue by aiezu** [fex-team/ueditor#2824]
配置好了ueditor后测试发现：ol,ul列表的样式，p元素缩进等凡是用到元素class,style属性才能完成的功能都是无效功能，因为加的style,class属性都会自动删除，ueditor简直废了。找了很久的原因都没找到，最后经过几个小时的断点调试，才发现xss过滤把凡是不在配置文件xss过滤白名单中的class,style属性自动删除了，真是天大的坑。
开发的大哥不知道怎么想的，像是文本对齐，缩进都需要style属性支持，竟然不放到白名单里，那还摆那些功能按钮在上面干嘛。

**Comment by liux** [comment]
我是真的无力吐槽了，浪费我大量时间！！！！！！！！！！！！！！！

**Comment by Phinome** [comment]
没做好测试工作，着急上线，是我的问题，给给位道歉~ 反馈的问题已修复，参考： #2817
