### ISSUE TITLE
现在基本不更新了吧没问题也没人回答了，官方在线demo也出现很明显的bug

### ISSUE THREAD

**Issue by wpp5354** [fex-team/ueditor#2827]
现在基本不更新了吧没问题也没人回答了
官方在线demo也有很明显的bug
编辑完样式后切换下源代码，编辑的 样式就消失了

**Comment by Dafrok** [comment]
切换源代码是怎么个切换法？

**Comment by yuzhigang1** [comment]
感觉是的,我下的最新版很明显的BUG,点下字体加粗什么的,都会报错,.感觉这论坛也没人了

**Comment by wpp5354** [comment]
![1](https://cloud.githubusercontent.com/assets/9841553/15732969/ff8f56ce-28b3-11e6-91f9-69b638812179.png)
![2](https://cloud.githubusercontent.com/assets/9841553/15732972/0881fa3e-28b4-11e6-87c8-8c2bbc5d4c18.png)
![3](https://cloud.githubusercontent.com/assets/9841553/15732973/0b55cd26-28b4-11e6-8f8f-275b25cc3f53.png)
切换HTML后编辑好的样式消失了，浏览器为以下
![4](https://cloud.githubusercontent.com/assets/9841553/15732974/0e3bc0b8-28b4-11e6-9cff-9156f3d1695b.png)

**Comment by wpp5354** [comment]
不知道官方的DEMO为什么会出现如此明显的问题

**Comment by ceroot** [comment]
也同样遇到这样的问题，无解呀

**Comment by Phinome** [comment]
之前 xss 修复的时候引起的问题，问题已修复。
