### ISSUE TITLE
1.4.2controller.jsp编译报错 请帮我看一下  十分感谢

### ISSUE THREAD

**Issue by bluePotato1** [fex-team/ueditor#283]
controller.jsp:3:36: Package com.baidu.ueditor contains no member type of this name.
<%@ page import="com.baidu.ueditor.ActionEnter" %>

                                   ^---------^
controller.jsp:11:13: No match was found for method exec() in type <error>.
	out.write( new ActionEnter( request, rootPath ).exec() );

                   ^-----------------------------------------^
controller.jsp:11:17: No type with this name could be found at this location.
	out.write( new ActionEnter( request, rootPath ).exec() );

                       ^---------^

**Comment by kanglj** [comment]
我也遇到这个问题，应该是com.baidu.ueditor.ActionEnter的问题，就是不知道该怎么处理，请求解决！
