### ISSUE TITLE
我用的是jsp技术开发的博客，请问如何使用ueditor？

### ISSUE THREAD

**Issue by bbsuperman** [fex-team/ueditor#2831]
第一次开发自己的博客，知道ueditor这么一个富文本编辑器之后，就下载了，发现不会使用。请各位大神指点指点，小弟不胜感激。

**Comment by Phinome** [comment]
参考文档[http://fex.baidu.com/ueditor/](http://fex.baidu.com/ueditor/)

**Comment by bbsuperman** [comment]
为何我创建的Demo.html打开是空白的呢？

**Comment by bbsuperman** [comment]
description The server encountered an internal error () that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: An exception occurred processing JSP page /controller.jsp at line 12

9: 	
10: 	String rootPath = application.getRealPath( "/" );
11: 	
12: 	out.write( new ActionEnter( request, rootPath ).exec() );
13: 	
14: %>
