### ISSUE TITLE
关于UEditor1.4.3预览时代码高亮无效

### ISSUE THREAD

**Issue by 15036900300** [fex-team/ueditor#2833]
将UEditor1.4.3（[1.4.3.3 Jsp 版本]）下载到本地以tomcat1.6运行后，插入代码后，点击预览，无代码高亮效果，但是UEditor官网的UE演示就可以高亮，始终找不到原因

**Comment by Itgaogao** [comment]
百度下就解决了,我昨天刚解决。
先引入2个文件
<link href="ueditor/third-party/SyntaxHighlighter/shCoreDefault.css" type="text/css" rel="stylesheet">
		<script type="text/javascript" charset="utf-8" src="ueditor/third-party/SyntaxHighlighter/shCore.js"> </script>
$(function(){
				//代码高亮
				SyntaxHighlighter.all();
});

**Comment by Itgaogao** [comment]
<link href="ueditor/third-party/SyntaxHighlighter/shCoreDefault.css" type="text/css" rel="stylesheet">
		<script type="text/javascript" charset="utf-8" src="ueditor/third-party/SyntaxHighlighter/shCore.js"> </script>

**Comment by Itgaogao** [comment]
<!<link href="ueditor/third-party/SyntaxHighlighter/shCoreDefault.css" type="text/css" rel="stylesheet">-
		<script type="text/javascript" charset="utf-8" src="ueditor/third-party/SyntaxHighlighter/shCore.js"> </script>->

**Comment by 15036900300** [comment]
@Itgaogao 2个文件显示已经引入，我将你发的这段代码加上也是不起作用的，所以才提问了一下，我看UE在线演示是没有哥们你发的这行代码，他都可以正常高亮显示，实在找不到原因了

**Comment by pengweifu** [comment]
需要引用uParse.js

**Comment by 15036900300** [comment]
@pengweifu 已经找到原因了，jsp-uft8这个下载的版本中，UEditor.all.js这个获取编辑器内容（getContent()）这个方法有问题，获取的内容把高亮的class='brush:js'给过滤掉了，我把官网的js下载下来就OK了

**Comment by Phinome** [comment]
官网的包还没更新，之前有个 bug 引起的过滤问题，最新的代码可以 clone dev-1.4.3.3 这个版本。
