### ISSUE TITLE
我发现一个大问题，图片功能可以取消，干脆让用户自己做图片上传功能。

### ISSUE THREAD

**Issue by huangkuan123** [fex-team/ueditor#2834]
要么你把图片的增删改查功能给做好了，增做了，查有了，改不需要，删呢？如果从服务器端直接删除图片，发布过的文章有图片的话就会出现图片引用地址。

**Comment by Phinome** [comment]
可以自行实现上传功能啊，扩展或者更改图片上传的代码就行了。

**Comment by 3xxx** [comment]
麻烦给个思路：如何删除文章中的图片后也把服务器上存储的图片给删了。

**Comment by 3xxx** [comment]
http://bbs.co188.com/
感觉这个论坛对于图片的处理很完美
