### ISSUE TITLE
ueditor1.4.3.3在dedecms5.7下编辑样式无法生效

### ISSUE THREAD

**Issue by fx949494fx** [fex-team/ueditor#2836]
例如编辑一段文字“欢迎光临！”的样式，选择字体：微软雅黑，字号：16px。切换到到源代码模式，发现`<p>`标签里没有加入style，切回编辑模式后，文字变回默认样式。
该问题导致发布的内容无法自定义样式，求问什么原因？

**Comment by l306287405** [comment]
我也遇到同样的问题 包括pre代码高亮也是无效的

**Comment by xxpurple** [comment]
me too,when content change to html,css lost.bug in v1.4??

**Comment by xiaodongyuan177** [comment]
ueditor1.4.3.3  这个版本有问题，降个版本吧，ueditor1.4.3.2 这个版本的没有问题
