### ISSUE TITLE
图片上传成功在IE8下的问题显示上传失败

### ISSUE THREAD

**Issue by songshch** [fex-team/ueditor#2838]
**首先**，请问现在还支持IE8吗？

**其次**，如果支持请在IE8下面各个功能坐下测试

单图片上传功能在上传完成图片后插入编辑器显示失败，**后端返回结果正常**，经过排查是
` 
loader = me.document.getElementById(loadingId);

  loader.setAttribute('src', link);
  loader.setAttribute('_src', link);
  loader.setAttribute('title', json.title || '');
  loader.setAttribute('alt', json.original || '');
  loader.removeAttribute('id');
  domUtils.removeClasses(loader, 'loadingclass');`

这获取loader 为null

` me.execCommand('inserthtml', '<img class="loadingclass" id="' + loadingId + '" src="' + me.options.themePath + me.options.theme +'/images/spacer.gif" title="' + (me.getLang('simpleupload.loading') || '') + '" >');
`
说明这里执行失败，发现有inserimage 为什么这里用这个方法，而且到最后还执行失败，另外indexOf在ie8下不支持，代码中有用户indexOf 请做下兼容。

**Comment by Phinome** [comment]
这个是之前的 bug ，已经修复，你可以 clone dev-1.4.3.3 这个分支，然后在本地构建，即可。
