### ISSUE TITLE
百度编辑器怎么把我内容里面的样式加载了，脚本执行了？？

### ISSUE THREAD

**Issue by a476552085** [fex-team/ueditor#2840]
什么情况？？我里面的代码都转为实体符号了。百度编辑器还帮我自动还原了？
&lt;link&nbsp;href=&quot;/files/css/shCoreDefault.css&quot;&nbsp;rel=&quot;stylesheet&quot;&nbsp;type=&quot;text/css&quot;&nbsp;/&gt;
&lt;script&nbsp;language=&quot;javascript&quot;&nbsp;type=&quot;text/javascript&quot;&nbsp;src=&quot;/files/js/shCore.js&quot;&gt;&lt;/script&gt;
&lt;script&gt;
SyntaxHighlighter.all();
&lt;/script&gt;

我这样的代码呗百度编辑器还原成并且执行了。求解啊，为什么他会自己还原？？

**Comment by DealBelinda** [comment]
源码会告诉你答案的
