### ISSUE TITLE
图片和视频上传问题

### ISSUE THREAD

**Issue by jutreio** [fex-team/ueditor#2841]
怎么修改图片和视频的上传路径

**Comment by zuihou** [comment]
这几天也在研究这个问题， 目前只知道修改config.js
window.UMEDITOR_CONFIG.imageUrl 参数。

但不知道如何在调用时动态修改 上传路径

**Comment by ccccc0511** [comment]
改上传地址可以直接改Config.json的吧,动态的估计就得去找文件保存方法那里了
