### ISSUE TITLE
2016-5-26更新的ueditor竟然有那么大的bug

### ISSUE THREAD

**Issue by song526457385** [fex-team/ueditor#2842]
切换到html代码方式，把标签带的样式全部清除了。标签带的style样式根本显示不出来，为标签上一个颜色样式，点击切换，直接没有，调了一个下午竟然，我去。

**Comment by DaWaJueJi** [comment]
我也刚发现这个问题了，倒地是配置问题，还是版本BUG

**Comment by song526457385** [comment]
就是一个版本bug,我换了一个版本就没有事了

**Comment by xxpurple** [comment]
我的也是.发现无论是从编辑器里切换到html,还是把内容赋值到div里,css都丢失了.

**Comment by wiyejing** [comment]
发现 1.4.3.3 上传视频，html模式，找不到视频代码了，video路径能找到视频文件。好像问题蛮多的

**Comment by xiaodongyuan177** [comment]
@song526457385  你降到哪个版本了，看来我也得降低版本了，这个问题我也遇到了

**Comment by tangtanglove** [comment]
无知者无罪，新版本默认配置过滤了样式标签啊！自己修改config配置文件吧

**Comment by ycz0926** [comment]
@tangtanglove 关键是把whitelist的单词拼错了。。。

**Comment by lenyi** [comment]
过滤有解决的的办法吗？
