### ISSUE TITLE
图片上传缩略图bug

### ISSUE THREAD

**Issue by s375214847** [fex-team/ueditor#2847]
"imageCompressEnable": true, /\* 是否压缩图片,默认是true _/
    "imageCompressBorder": 640, /_ 图片压缩最长边限制 */
上传时  图片任然是原大小

**Comment by hyyuno** [comment]
你要使用多图上传按钮，才能有这个压缩效果！

**Comment by wangyafengAlex** [comment]
我的是jsp mini的不想要压缩怎么改
