### ISSUE TITLE
thinkphp关闭调试模式后 UEditor 就不显示了

### ISSUE THREAD

**Issue by zhulinai** [fex-team/ueditor#2851]
我开启调试模式一切正常。然后我把Runtime文件夹删除。关闭调试模式。刷新页面。UEditor就没了。我开启调试模式。刷新页面。UEditor就出来了。然后我再关闭调试模式。我已经进去过的页面。也就是有缓存的页面。一切正常。当我进入没缓存过的页面。UEditor就又没了。所以。关闭调试模式+没有缓存。UEditor就不显示。
还有
// $(".registerform").Validform(); //就这一行代码！;
这句话如果取消注释UEditor就不能正常使用了。这句话是干什么用的啊？
感谢各位

**Comment by Phinome** [comment]
尝试百度或者 Google 一下吧。
