### ISSUE TITLE
UEditor 1.4.3.3 测出来几个比较严重的bug

### ISSUE THREAD

**Issue by andyzty** [fex-team/ueditor#2855]
1、插入表格后，前端页面和app端调用这端都为含有表格边框，Google搜了好多解决办法还是不行
如下图：
![Uploading QQ截图20160615174715.png…]()
![Uploading QQ截图20160615174736.png…]()

2、和bootstarp搭配时总是在模态下出现错位现象，toolbar和内容分离。。。
![Uploading QQ截图20160615175019.png…]()

我用的是java版的，对前端懂得不是很精，麻烦fex帮忙改一下，谢谢开源，谢谢分享。
@nwind

**Comment by andyzty** [comment]
3、只要鼠标点了上传的图片，就没办法将焦点移动到编辑框内的其他地方了。

4、UEditor里表格右击菜单设置表格的任何属性，保存完后都没有。

**Comment by 3xxx** [comment]
最近似乎比较忙啊，没空回复呢。

**Comment by Phinome** [comment]
1. 第一个问题，需要你修改 table 的 css 样式；
2. bootstrap 的样式和 UEditor 的样式冲突了，你需要调整一下；
3. 这个是 Bug ，但目前没有时间来修复；
4. 建议你下载最新的代码，然后在 ueditor.config.js 里的过滤规则里将 table 相关的元素，设置样式白名单，可参考里面已有的写法。
