### ISSUE TITLE
.net 版 1.4.3.3  新版问题求助

### ISSUE THREAD

**Issue by qhdedu** [fex-team/ueditor#2856]
官方能不能直接做出能加入水印图片的版本？
并且用户能指定所加的水印PNG文件 （也就是说水印文件不是固定的，开发者可以在程序中可以指定一个PNG文件）。

如果官方版本直接加入此功能，用户体验会更好！

另外，哪位能通过二次开发实现此功能，可否交流一下经验？

谢谢~~~~（QQ: 25295110 愿意与您沟通交流）

**Comment by paseo** [comment]
1. 水印有很多的第三方实现，这不是编辑器的范围
2. demo只是给你展示最基本的功能，做一个闭环。更多的功能要你自己去实现，孩子，不然你的价值何在？

**Comment by taozifly** [comment]
富文本编辑器是给你提供一个更加友好的文字和图片录入展示等，更多的是倾向于样式，而你说的水印是需要你处理的，比如你陪了一个上传路径，它给你一个图片，你在controller里面接收到这个文件的时候存储的时候给它打个水印就好了。

**Comment by Phinome** [comment]
1. 水印有很多实现，而且主要功能是在后端，你看看你使用的是什么后端语言，然后找第三方的库来实现即可；
2. 不是什么都要加到官方的编辑器里的，任何试图囊括所有功能的产品最终都是个畸形。
