### ISSUE TITLE
UE jsp图片上传 Action， 图片文件权限的问题。

### ISSUE THREAD

**Issue by yasinshaw** [fex-team/ueditor#2858]
说明：
1.本人的项目是基于java 的 spring框架，控制层是springmvc。
2.因为需要整合spring与apache，所以带来了上传图片的权限问题。需要每次上传图片都更改其权限为777
3.目前UE里图片上传是使用自带的action，另外的图片上传是使用springmvc的图片上传功能。
4.现在使用的方案是，每次提交UE的内容时，在service里把图片权限改为777.
5.但是带来了一个问题：在UE编辑时，上传图片。不能及时预览（因为还没有点击提交，文件通过UE传过去了，但权限还没有更改，所以请求不到图片资源。） 提交之后可以正常获得图片。
6.试过在json里把图片上传的action改为我的 springmvc 文件上传控制器映射，但显示无效的Action。

现在有两个解决办法：1是在UE上传图片时就改权限，2是把上传图片的action交给springmvc的文件上传控制器。
不知道具体该怎么办，求助。。

**Comment by Phinome** [comment]
百度一下
