### ISSUE TITLE
UE 复制复杂网页内容上传js报错

### ISSUE THREAD

**Issue by Taruca** [fex-team/ueditor#2859]
UE上传复制的网页内容时，会报错：
bootbox.min.js:6 Uncaught Error: Please specify a message。
复制较为简单的网页时就没有问题。
有没有大牛遇到过类似的问题？求帮忙解决一下。谢谢大家了！

**Comment by Phinome** [comment]
看看是不是你的复制网页的 js 引用的问题。 bootbox.min.js UEditor 是没有的。
