### ISSUE TITLE
html语言代码新建时成功，再次编辑后，html标签就被自动删除了，求问怎么解决

### ISSUE THREAD

**Issue by mankorn** [fex-team/ueditor#2863]
比如
新建时：代码语言选择html，输入《div》111《/div》。成功!
再次编辑：《div》111《/div》变成了111，有时候又一片空白，有时候又是出现toolbar  cancel  什么的

**Comment by cyycaoyang** [comment]
遇到同样的问题，你解决了吗？

**Comment by Phinome** [comment]
看文档。[文档](http://fex.baidu.com/ueditor/#qa-allowDivToP)
