### ISSUE TITLE
1.4.3.3jsp版本编辑器设置字体下划线，居中之类的样式不能保存

### ISSUE THREAD

**Issue by zhangyongbo** [fex-team/ueditor#2864]
1.4.3.3jsp版本编辑器设置字体下划线，居中之类的样式不能保存

**Comment by 412273066** [comment]
php版本也有同样问题

**Comment by Phinome** [comment]
之前的 1.4.3.3 版本有点问题，后来修复了，版本号不变，重新下载一次即可。[下载地址](http://ueditor.baidu.com/website/download.html)

**Comment by solgh** [comment]
还是不行啊
