### ISSUE TITLE
编辑器经常无法初始化加载，怎么回事？

### ISSUE THREAD

**Issue by haoyingshuang** [fex-team/ueditor#2865]
TypeError: UE.I18N is undefined
TypeError: UE.registerUI is not a function
TypeError: UE.getEditor is not a function

本地服务器是好使的，部署到线上就不行了，强制刷新缓存，清除浏览器历史缓存，重装浏览器 都试过，都不可用 怎么办？

**Comment by Phinome** [comment]
看看线上的网络环境。出现这个错误，应该是文件加载失败。
