### ISSUE TITLE
Refused to display 'http://api.sit.vveshow.com/buy/api/v1/w1/admin/media/platform/res?editorid=myEditor' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

### ISSUE THREAD

**Issue by ColdXu** [fex-team/ueditor#2866]
umditor 图片上传出现以上问题，怎么解决啊。

Refused to display 'http://api.sit.vveshow.com/buy/api/v1/w1/admin/media/platform/res?editorid=myEditor' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'

**Comment by Phinome** [comment]
都提示你是啥问题了。。。找找后端的同学。
