### ISSUE TITLE
此项目还有人在维护否？

### ISSUE THREAD

**Issue by paseo** [fex-team/ueditor#2867]
此项目还有人维护吗，百度的同学们？
如果有，动起来，issue里有的僵尸问题，回复一下关了可好？
如果有，有问题的issue或者决定增强的feature，打个label可好？

如果有，让大家看到这个项目是活的。就算工作忙顾不过来，大家也可以参与进来尽绵薄之力。

**Comment by Phinome** [comment]
😂 ，有些很久的 issue 关了，又有人去那儿讨论， 加之工作上的事儿，确实也有些缓慢。。。欢迎大家一起来参与，将它变得更好。

**Comment by paseo** [comment]
@Phinome 
有些低级的问题，可以给个url，关了了事，可以试试。

**Comment by 496604841** [comment]
这个项目似乎已经不维护了。

**Comment by Dafrok** [comment]
现在只有两个人在维护……还都是兼职的

**Comment by zhi-leaf** [comment]
图片跨域上传出错，图片已经上传成功，但界面上无法显示，JS调试是在24521行取iframe.contentDocument值出现跨域问题，出错提示是“Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin”。测试版本是1.4.3.3。有人处理下么？

**Comment by paseo** [comment]
@Dafrok 都是谁，你知道不。
请维护者冒个泡~

**Comment by paseo** [comment]
没资源，有时候是挺难的
