### ISSUE TITLE
有序列表加载不出

### ISSUE THREAD

**Issue by hzsdhf** [fex-team/ueditor#2868]
发现有好多有序列表的图加载不出来，在线完整示例里也一样，没人发现么
一、 十三、3) 6. 都不行

**Comment by paseo** [comment]
有排查过没？把排查的过程贴出来

**Comment by paseo** [comment]
@hzsdhf 有排查过没？把排查的过程贴出来

**Comment by hzsdhf** [comment]
@paseo 例如一、 就是这个图片的远程地址失效

**Comment by paseo** [comment]
@hzsdhf 
1. 尝试复制链接在浏览器中单独打开看是否能访问到  
2. 将失效的图标链接贴到issue里，方便定位

**Comment by hzsdhf** [comment]
@paseo 
一、的地址http://bs.baidu.com/listicon/list-cn-1-1.gif 
1.的地址http://bs.baidu.com/listicon/list-num-1-1.gif
第一个是有问题的，第二个正常。

**Comment by paseo** [comment]
@hzsdhf 这两张图片是可以正常访问的，请检查你的网络和公司的网管策略

**Comment by hzsdhf** [comment]
@paseo 纳尼，用4G网络是可以打开-_- ，公司 的网络真是服了。
