### ISSUE TITLE
图片跨域上传出错

### ISSUE THREAD

**Issue by zhi-leaf** [fex-team/ueditor#2870]
图片跨域上传出错，图片已经上传成功，但界面上无法显示，JS调试是在24521行取iframe.contentDocument值出现跨域问题。

出错提示是：
code:18
message:"Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin http://localhost:9080" from accessing a cross-origin frame."
name:"SecurityError"
stack:"Error: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin http://localhost:9080" from accessing a cross-origin frame.↵    at Error (native)↵    at HTMLIFrameElement.callback (http://localhost:9080/uetest1/scripts/ueditor2/ueditor.all.js:24521:43)"
**proto**:DOMException

测试版本是1.4.3.3。有人处理下么？

**Comment by leopeck** [comment]
我也是这个问题，查看网上，即使加了document.domain 也还没解决~~你解决l没？

**Comment by zhi-leaf** [comment]
没有，搞死人

**Comment by liwenjie1991** [comment]
哥们，有没有解决办法啊，图片跨域问题，单个图片上传成功，但是无法显示，多个上传就直接报错了，也是跟你一样的错
