### ISSUE TITLE
使用ueditor发布文章，删除后怎么顺带删除图片？

### ISSUE THREAD

**Issue by qf19910623** [fex-team/ueditor#2876]
如果要删除一篇文章，肯定得顺带把里面的图片等资源也删掉吧，ueditor有没有这方面的功能呢？难道还得自己用正则把路径匹配出来再删除？

**Comment by Phinome** [comment]
之前不是答复过你了么， #1860 ，这种需求是需要自己去实现的，编辑器只是帮你解决编辑的问题，至于编辑的内容你后续需要怎样的处理那都是后续处理的步骤了，编辑器是不会干涉的。你可以去社区里问问，看有没有人实现了相应的功能。
