### ISSUE TITLE
粘贴文字之后，图片地址变成本地路径，不是远程服务器的地址了

### ISSUE THREAD

**Issue by xiaodongyuan177** [fex-team/ueditor#2879]
版本 ueditor1_4_3_2-utf8-jsp ，我是自定义请求地址的
图片上传成功：
![image](https://cloud.githubusercontent.com/assets/19929418/16360360/683c3a62-3b91-11e6-8ebe-77d49c51cb90.png)

在编辑器中粘贴文字之后：
![image](https://cloud.githubusercontent.com/assets/19929418/16360362/78202b28-3b91-11e6-8877-b42c817cae1f.png)

**Comment by heixiongTT** [comment]
//设置远程图片是否抓取到本地保存
//,catchRemoteImageEnable: true //设置是否抓取远程图片
ueditor.config.js里面有这样一段，设置为false试试。

**Comment by xiaodongyuan177** [comment]
@heixiongTT  设置之后就没问题了
