### ISSUE TITLE
从word中复制的图片粘贴到UEditor中以后不能正常显示，work图片转存的按钮也不可用。

### ISSUE THREAD

**Issue by heixiongTT** [fex-team/ueditor#2883]
从word中复制的图片粘贴到UEditor中以后不能正常显示，work转存的按钮也不可用。
上周调试的时候发现word中的图片粘贴过来以后不能正常显示，但是work图片转存的按钮是可用的。
有遇到同样问题的朋友吗？
大家都是怎么解决带图片的word内容向UEditor中粘贴的问题？
1.4.3.3java_utf-8版本

**Comment by 3xxx** [comment]
最近word转存，图片可以上传，返回地址也是对的，但是编辑器中的链接地址不改变，郁闷了。

**Comment by 472630126** [comment]
我也遇到这个问题了，word里面粘贴进来的图片显示不了， 这个功能怎么实现啊，有老司机吗

**Comment by 3xxx** [comment]
占位符不能自动替换，奇怪了。原来是可以的啊。

**Comment by 472630126** [comment]
以前可以自动替换占位符吗？ 怎么弄

**Comment by heixiongTT** [comment]
@3xxx 图片还没有转存啊，占位符替换了也读不到本地图片啊。

**Comment by 472630126** [comment]
能不能让它可以自动转存过去呢，然后自动替换

**Comment by 3xxx** [comment]
@heixiongTT 图片转存没有其他设置，和图片上传是一样的。

**Comment by heixiongTT** [comment]
@3xxx 那请问，最新的版本里从word里拷贝了带图片的内容到ueditor中，图片转存的按钮还是disable，这个是bug吗？前一个版本中没有发现这个问题的。

**Comment by 3xxx** [comment]
看来还是用回原来版本。

**Comment by 3xxx** [comment]
chrome浏览器发生这个错误，不知道是否和这个错误有关，反正不管换什么版本都不自动替换占位符。
about:blank:1 Not allowed to load local resource: file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image002.jpg

**Comment by heixiongTT** [comment]
这个是浏览器安全问题，浏览器不允许直接访问本地文件，前个版本可以转存，转存过后会替换掉占位符的。

**Comment by adasir** [comment]
解决办法
1、修改ueditor.all.min.js文件，
搜索 function(d,e){c[b].indexOf(e)===-1&&a.setAttr(e)}
替换成 function(d,e){if(c[b].indexOf(e)===-1&&e!='style'&&e!='word_img')a.setAttr(e)}

UE.plugins.xssFilter 安全机制导致的
