### ISSUE TITLE
视频回显问题

### ISSUE THREAD

**Issue by herrdu** [fex-team/ueditor#2892]
当我上传视频保存后，再次打开编辑，发现上传后的视频位置是空的。于是debug，发现下面这段代码没有设置i的范围 。想知道这样设计的理由是什么？

```
    filterInputRule: function (root) {
        for (var i = 0, ci; ci = this.inputRules[i++];) {
            ci.call(this, root)
        }
    },
```

**Comment by chaosannals** [comment]
可能是要用ci = undefined来让循环终止吧。
毕竟js没有指针这东西，必须用索引。就成了有i又有ci。
不过这也只是我的猜测。

**Comment by pearlhpp** [comment]
请问，视频回显问题解决了么

**Comment by chaosannals** [comment]
我用ueditor并没有出现视频保存后为空的问题，反倒是“音乐”这一项有类似问题出现。在弹出的音乐框里可以搜索到音乐的表单，但是不能“试听”，而且点确定后就会出现有“音乐插入成功”字样的图片在编辑器里，但是点击“HTML源码”就会发现变成空的了。
