### ISSUE TITLE
插入视频问题

### ISSUE THREAD

**Issue by 632677663** [fex-team/ueditor#2893]
插入一个优酷视频,点击html源码,发现里面什么内容都没有.

**Comment by suning920** [comment]
我也遇到了这个问题，怎么解决

**Comment by keyhost** [comment]
我也是这样，插入过后就自动屏蔽了。请问高手些，这个问题怎么解决呢？我开始以为配置有问题。结果不是这样，他的案例就是这样。他官方网站的又没有问题，不知道是什么情况。。。

**Comment by suning920** [comment]
什么也没有，1.4.3里把这个视频放入iframe里都不行，但是但到1.4.2的iframe里可以

**Comment by sinopec** [comment]
同问，貌似是把iframe给删除了，怎么配置不删除啊，也没看到个配置的地方
