### ISSUE TITLE
最新版本的ue在提交编辑内容之后再重新编辑提交的内容，因为新加的输入过滤导致分页符运行异常

### ISSUE THREAD

**Issue by yrong334** [fex-team/ueditor#2894]
在编辑器里面插入分页符是：
`<p>aaaaaaaaaaaaaaaaaa</p><p><br></p><hr class="pagebreak" noshade="noshade" size="5" style="-webkit-user-select: none;"><p>bbbbbbbbbbbbbbbbba<br></p>`
提交后变成：
`<p>aaaaaaaaaaaaaaaaaa</p><p><br></p>_ueditor_page_break_tag_<p>bbbbbbbbbbbbbbbbba<br></p>`
但是如果我重新在编辑器渲染这段内容，在编辑器里面会变成：
`<p>aaaaaaaaaaaaaaaaaa</p><p><br></p><hr><p>bbbbbbbbbbbbbbbbba<br></p>`
如果此时我重新提交则分页符丢失。
经检查是输入过滤导致hr的属性全部丢失所致。
因此，当我将inputXssFilter设置为false时，则正常运行。

或者将hr过滤规则设置成hr:['class','noshade','size','style']也可正常运行。但不知这样是否还符合xss过滤的本身设计意图。

**Comment by One2r** [comment]
我也跟了半天，搞明白什么情况，也没找到解决方法~
