### ISSUE TITLE
UMeditor 设置了字体的大小以后，切换段落格式时样式没有变化 BUG

### ISSUE THREAD

**Issue by mzl930** [fex-team/ueditor#2902]
UMeditor里设置了字体的大小之后，切换段落格式时样式没有发生变化。

问题起因： 一开始是发现给字体加粗的时候之前所添加的所有格式都变无效了，检查时发现是页面本身定义了h1、h2、b、i 等标签的样式，覆盖了umeditor.min.css中定义的样式。（也就是说编辑器的样式优先级还不够高或者是针对性还不够。）
问题发现： 等我把样式修改好后发现，当我先设置了字体大小，然后再切换段落格式时，字体的大小没有变化。
问题原因： 设置字体大小时，font里设置了字体的大小；但是在之后设置段落格式的时候没有对font标签的样式做相应的修改。

浏览器： chrome、IE、FX
文件： umeditor.min.css

**Comment by mzl930** [comment]
在线演示也存在这个问题：
http://ueditor.baidu.com/website/umeditor.html

**Comment by cocca883** [comment]
我也遇到这个问题https://github.com/fex-team/ueditor/issues/2873
