### ISSUE TITLE
[请测试并修正]ueditor.parse.js:930字义了全局样式的li引起样式错误.

### ISSUE THREAD

**Issue by momoca** [fex-team/ueditor#2906]
[UEditor 1.4.3.3版本 2016-05-18](http://ueditor.baidu.com/build/build_down.php?n=ueditor&v=1_4_3_3-utf8-php)中
ueditor.parse.js:930

``` js
//原
        utils.cssRule('list', selector +' ol,'+selector +' ul{margin:0;padding:0;}li{clear:both;}'+customCss.join('\n'), document);
//修改如下:
        utils.cssRule('list', selector +' ol,'+selector +' ul{margin:0;padding:0;}'+selector +' li{clear:both;}'+customCss.join('\n'), document);
```

请测试并修正.

**Comment by 3xxx** [comment]
谢谢。https://github.com/fex-team/ueditor/issues/2839

**Comment by momoca** [comment]
哇,这你都看得到.这里是不是没人管理了呢?

**Comment by 3xxx** [comment]
我到不确定是不是这个错误引起的了。反正现在似乎可以了。

**Comment by momoca** [comment]
是这个.全定义一个个css全局的li还给li加了个clear:both;便bs中的li的浮动取消掉了.所以就不好用了.
我开始也是同样效果.后来发现只要一使用解析内容就会变这样.就开始找样式.
看样子是百度的临时工干的.再什么说也不应该定义全局样式呀.更何况根据上下文判断都是加了selector的.

**Comment by 3xxx** [comment]
哎，我今天修改后，遇到列表li还是不行。

**Comment by 3xxx** [comment]
谢谢你。百度的人用业余时间做的这个开源，也不可能花太多时间来管理这里。
我的ue粘贴word图文后，图片可以转存成功，但是就是不自动替换占位符，请问你会修改源码吗？

**Comment by momoca** [comment]
可以呀.分享一下代码.
