### ISSUE TITLE
关于图片上传后的显示过大问题

### ISSUE THREAD

**Issue by Justhin** [fex-team/ueditor#2907]
http://image.baidu.com/detail/newindex?col=&tag=&pn=0&pid=35219672791&aid=412384529&user_id=706197878&setid=-1&sort=0&newsPn=&star=&fr=&from=2

这种问题，我想知道是否有相应的API或config来限制图片显示的大小，这样图片太大
谢谢

**Comment by end1314** [comment]
please check file 'ueditor/thems/iframe.css', then add css 'img{width:100%;}'
also,you can change css here

**Comment by Justhin** [comment]
Thanks for your help! It's  solved my problem.
