### ISSUE TITLE
ueditor 你们好，为什么我从官网下载的jsp完整demo，word图片转存用不了。万急

### ISSUE THREAD

**Issue by 472630126** [fex-team/ueditor#2912]
我从官网下载的1.4.3.3 的jsp版本，按照官网的部署步骤完成部署，手动上传图片什么的都可以。就是word转存出不来，看后面的html源码，图片的地址被替换成
 http://localhost:8080/plugins/ueditor/themes/default/images/spacer.gif
所有的图片都是这个 src  ，所有的图片都打不开。

请问该如何解决。
谢谢

**Comment by heixiongTT** [comment]
用前一个版本吧，可以的。

**Comment by 472630126** [comment]
现在转存可以了。不过要一张张手动点，，能不能自动转存的

**Comment by heixiongTT** [comment]
你是换成上一个版本了吗？

**Comment by 3xxx** [comment]
chrome浏览器发生这个错误，不知道是否和这个错误有关，反正不管换什么版本都不自动替换占位符。图片可以上传成功，返回参数也正确。
about:blank:1 Not allowed to load local resource: file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image002.jpg

**Comment by adasir** [comment]
解决办法
1、修改ueditor.all.min.js文件，
搜索 function(d,e){c[b].indexOf(e)===-1&&a.setAttr(e)}
替换成 function(d,e){if(c[b].indexOf(e)===-1&&e!='style'&&e!='word_img')a.setAttr(e)}
