### ISSUE TITLE
百度图片搜索报错

### ISSUE THREAD

**Issue by lomotony** [fex-team/ueditor#2919]
1. 百度搜索报错了，是不是百度搜索的API改了，导致这样的错，你们都是一个公司的产品这样的bug不能改吗
2. 协议问题，是不是要根据当前的协议(https或者http)来调用百度图片API呢

**Comment by Phinome** [comment]
API 改了，现在图片搜索没有提供对外的 API 了，所以没法修改。

**Comment by lomotony** [comment]
@Phinome 那再版本更新的时候是不是会考虑把这个功能去掉？

**Comment by Phinome** [comment]
暂时是这样打算的
