### ISSUE TITLE
简单文件上传完成后未触发contentchange 事件

### ISSUE THREAD

**Issue by dz005** [fex-team/ueditor#2926]
/**
 * @description
 * 简单上传:点击按钮,直接选择文件上传
 * @author Jinqn
 * @date 2014-03-31
 */
UE.plugin.register('simpleupload', function (){
....
}

简单文件上传完成后未触发contentchange 事件。
导致监听contentchange 事件获取正文内容有误。

**Comment by Phinome** [comment]
[https://github.com/fex-team/ueditor/blob/dev-1.5.0/_src/plugins/simpleupload.js#L77](https://github.com/fex-team/ueditor/blob/dev-1.5.0/_src/plugins/simpleupload.js#L77)
