### ISSUE TITLE
优酷视频插入直接屏蔽掉

### ISSUE THREAD

**Issue by keyhost** [fex-team/ueditor#2927]
在官方网站下载的版本，在添加优酷的视频的时候，一点击HTML，就直接的屏蔽。
且在调用数据库内容的时候，如果有视频的代码，也直接的就屏蔽掉。

这个问题是在哪里弄？？我看官方网站的又是正常的，为什么下载下来就不正常。。。。。。

**Comment by axl-axl** [comment]
同样的问题好郁闷啊，上传的视频是可以的，但是链接是不行的

**Comment by dengdaijiushi** [comment]
对啊，我也是遇到这个问题。
另外大家自己上传的视频的格式都是什么啊，有测试支持的格式有哪些嘛？
video标签支持的太少了。
