### ISSUE TITLE
救急！！！！！ueditor的java版本上传图片提示'权限不足' 

### ISSUE THREAD

**Issue by BEE767** [fex-team/ueditor#2935]
<img src="https://cloud.githubusercontent.com/assets/9635477/7133368/41f02272-e2c5-11e4-9b3a-77ac339f9944.jpg" alt="bug" style="max-width:100%;">

**Comment by Daniel-yim** [comment]
是java服务端 的文件 写入权限不足的问题？

**Comment by qkcccc** [comment]
同这个问题。 楼主解决了么。。
