### ISSUE TITLE
win7 32位，flash13，ie8，上传多图点击选择图片按钮没任何反应，没有弹出上传操作框!!!

### ISSUE THREAD

**Issue by a365776929** [fex-team/ueditor#294]
win7 32位，flash13，ie8，上传多图点击选择图片按钮没任何反应，没有弹出上传操作框!!!

**Comment by tandaly** [comment]
估计你页面里面的js引入的顺序不对，IE运行的时候将后运行的js代码截断了，没有加载完导致的。
