### ISSUE TITLE
在vue的组件使用了百度Editor , 第一次根据路由进去该页面的时候editor 可以显示以及实例化，当我回退，再次进入的时候之前的页面，百度Editor就不能显示，不知道为什么，但我手动刷新当前页就可以显示百度editor？？？请问是什么原因呢？

### ISSUE THREAD

**Issue by YuKaiChan** [fex-team/ueditor#2945]

**Comment by hellflame** [comment]
首先整个webapp是通过vue-router进行路由切换，如果进入页面时首先加载含有ueditor组件的页面是能够正常使用的，并且没有报错，但是如果首先进入的页面不是这个含有ueditor组件的页面的话就会报一个错，以下截图是报错信息
ueditor.all.js:29419 Uncaught TypeError: Cannot read property 'style' of null
![](http://7xqh1q.dl1.z0.glb.clouddn.com/QQ%E6%88%AA%E5%9B%BE20160816172603.png)

以下是封装的组件

```vue
<template lang="jade">
div(v-ueditor="content", :config="config")
</template>

<script>
import Vue from 'vue'

Vue.directive('ueditor', {
        params: ['config'],
        twoWay: true,
        bind: function () {
            var self = this;
            this.el.id = 'ueditor' + new Date().getTime().toString()
            this.editor = UE.getEditor(this.el.id, this.params.config)
            this.editor.ready(function () {
                self.editorReady = true
                self.editor.addListener("contentChange", function () {
                    self.set(self.editor.getContent())
                })
                self.update(self.vm.$get(self.expression))
            })
        },
        update: function (newValue, oldValue) {
            if (this.editorReady) {
                this.editor.setContent(newValue)
            }
        },
        unbind: function () {
            this.editor.destroy()
        }
    })

export default {
props: {
    config: {
      type: Object,
      default: null
    },
  content: String
  },
  init(){
  }
}
</script>

```

**Comment by hellflame** [comment]
![image](https://cloud.githubusercontent.com/assets/7326970/17694938/d95aec92-63d8-11e6-96d3-5b881958c2e2.png)

还有，也需要手动指定初始化长宽，在这里我去掉了注释，不然一开始是报这两个错误的

**Comment by Phinome** [comment]
初步猜测可能是由于切换后dom节点销毁，但ueditor对象还持有之前的节点的引用所以此时会报错，你试试每次切换的时候销毁掉ueditor对象

**Comment by hellflame** [comment]
我能确认的是在页面切换时， `this.editor.destroy()`的确执行了，这样还不够么？
```vue
unbind: function () {
            this.editor.destroy()
        }
```

**Comment by Phinome** [comment]
destroy方法似乎是没有销毁掉，目前只是初步猜测，更详细的结果晚上我做个demo看看

**Comment by Phinome** [comment]
查了一下，有两点需要指出的：
1. 的确是需要手动指定初始化宽高，那个需要去掉注释；
2.`this.el.id = 'ueditor' + new Date().getTime().toString()` 这句话中 `this.el.id` 其实每次都是不一样的，即：init 的时候 this.el.id !== back 的时候 this.el.id，这样导致 UEditor 找不到挂载的节点。
3. `destroy` 没问题。

**Comment by hellflame** [comment]
关于这个id的话，即便我设置为某个固定值，报错依然存在诶，最终结果还是和之前是一样的=.=
![image](https://cloud.githubusercontent.com/assets/7326970/17758938/fba87b90-6525-11e6-827b-29b1eea3d3d0.png)

具体有没有能让我正常使用的方案呢

**Comment by Phinome** [comment]
晚上我给你个 DEMO 地址，你看看就知道了。

**Comment by Phinome** [comment]
[DEMO](https://github.com/Phinome/demo/blob/master/src/Editor.vue)，我这个仓库中的 `UEditor` 不是最新的，这段代码是可以跑的，你可以看看

**Comment by hellflame** [comment]
大概的直接原因找到了，，是因为我引用了jquery，在你给的demo中引入jq的话，就会和我得到类似的结果，猜测应该是ueditor内部某个地方又打包了jq=.=

还可以看到很多越来越多的textarea。。。。。。
![image](https://cloud.githubusercontent.com/assets/7326970/17842272/adc01862-6853-11e6-9c06-c570c8cc6133.png)

**Comment by YuKaiChan** [comment]
上面的问题，我很早就解决啦，就是在vue生命周期的ready function 初始化 bdE, 然后在beforeDestory/destoryed  function  把bdE 销毁  @hellflame  @Phinome

**Comment by lshnltt** [comment]
如果你是把UEditor封装成指令的话，重新进入不显示的原因是因为，你重新进入的时候UEditor挂在的id还没有显示在dom中，你把bind方法的代码放倒一个setTimeout函数中，设置5000毫秒的样子试试，应该就会显示了，如果你是直接在组件中使用，那就在ready钩子函数中掉用UE.getEditor，然后在组件中配置route属性，并且定义路由切换的钩子函数deactivate中把editor实例给销毁掉。反正你要巡着在dom渲染之后掉用UE.getEditor，在路由切换的时候把editor实例销毁就不会错了(不销毁也是又问题的)

**Comment by hellflame** [comment]
好的，多谢啦～ @lshnltt 
虽然已经没有用Ueditor了，，，thanks anyway
