### ISSUE TITLE
ueditor 1.4.2 PHP版本：代码语言（就是插入源代码）功能有问题

### ISSUE THREAD

**Issue by seozw** [fex-team/ueditor#295]
插入一个HTML源代码， 看起来没有问题，提交存储到数据库中， 然后重新编辑这一条信息的时候，编辑器内  代码语言（插入的源代码）不显示。。。就是pre内部好像都被过滤了。。。

**Comment by logy-bai** [comment]
我也遇到这个问题了,你是怎么解决的?
