### ISSUE TITLE
使用setCotent出错

### ISSUE THREAD

**Issue by zhang1096646030** [fex-team/ueditor#2951]
ueditor编辑器bug建议修复：
 版本：1.4.3.3和1.4.3.2都有此bug
 错误：ueditor.all.js:7320 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
 备注：onload的事件中调用setContent设置内容时出错，但是onClick事件中调用setContent设置内容时又是正常的，真实奇葩的bug，请求修复！

**Comment by iamziyue** [comment]
我也是，后来这样就没报错了。
~~~
ue.ready(function(){ue.setContent(v);});
~~~
