### ISSUE TITLE
请问1.5.0版本什么时候发布?

### ISSUE THREAD

**Issue by lomotony** [fex-team/ueditor#2954]
有的提交只是提交到了dev-1.5.0分支上，比如https://github.com/fex-team/ueditor/commit/69f47375a332a47f2ade4f68700bddb7dbe82f9f ，我觉得这个提交很重要，对于自定义按钮来说，但是这个提交仅在dev-1.5.0分支上。同时也该把一些bug修掉了，该去掉的应该去掉了，比如说百度图片的搜索，既然不支持了，就该去掉了。1.4.3版本过时了，什么时候能够发布1.5.0版本啊？

**Comment by lomotony** [comment]
有的提交只是提交到了dev-1.5.0分支上，比如https://github.com/fex-team/ueditor/commit/69f47375a332a47f2ade4f68700bddb7dbe82f9f，我觉得这个提交很重要，对于自定义按钮来说，但是这个提交仅在dev-1.5.0分支上。同时也该把一些bug修掉了，该去掉的应该去掉了，比如说百度图片的搜索，既然不支持了，就该去掉了。1.4.3版本过时了，什么时候能够发布1.5.0版本啊？

**Comment by lomotony** [comment]
刚发现dev-1.5.0分支上,package.json中的version是2.0.0，这个是为什么？

**Comment by lomotony** [comment]
@Phinome 能给个答案吗？

**Comment by Phinome** [comment]
多谢关心，目前业务繁忙，没有时间，暂时不能给你确切的时间，可以确定的是：目前接下来的计划是会整理 issue 。2.0 的版本会有一个较大的变更。

**Comment by Phinome** [comment]
dev-1.5.0 上的package.json 中的 version: 2.0.0 是个错误。原本的想法是不想做 1.5 的，但考虑到现实，所以才改成了 1.5.0 了。

**Comment by lomotony** [comment]
@Phinome 谢谢。那1.5.0版本会发布吗？

**Comment by Phinome** [comment]
会的，但近期不会发布的。可能要到11月份左右了。还得看业务情况。

**Comment by lomotony** [comment]
@Phinome thanks
