### ISSUE TITLE
​看到很多帖子都有问这个问题《后端配置项没有正常加载，上传插件不能正常使用！>

### ISSUE THREAD

**Issue by Afewtastelife** [fex-team/ueditor#2961]
看了很多关于这个问题的帖子，得到的解答基本是，看下面。。。
 提 `ISSUE` 之前，**请先看看文档**。传送门：[文档](http://fex.baidu.com/ueditor/)。很多问题，在文档中都能有答案。特别是配置之类的。

那么，我想说的是，我他妈看不懂！！！

**Comment by Afewtastelife** [comment]
继续补充问题，我发现这个编辑器，如果你的文本长，图片多，那么在后面的内容全部变成一小段代码。这个问题有没有人遇到过？还是只有我一个人遇到？

**Comment by Daniel-yim** [comment]
这个问题是需要在：ueditor.config.js中配置serverUrl属性的，有些功能是需要服务端支持的。

**Comment by yisuoyanyuqiong** [comment]
请问jsp版本的这个问题具体如何解决？看了很多帖子都没有改好。。。

**Comment by Geek-Icebreaker** [comment]
我配置了serverUrl .也出现了后台配置出错。路径绝对没问题。
