### ISSUE TITLE
1.4.3.3 插入视频貌似有bug

### ISSUE THREAD

**Issue by bb7788** [fex-team/ueditor#2964]
“视频”里的“插入视频”貌似有bug，插入视频后丢失。
插入视频后切换到查看html代码，看不到插入的视频代码。
[1.4.3.3 PHP 版本]存在这个问题，[1.4.3.2 PHP 版本]测试不存在这个问题
浏览器chrome 51.0.2704.106 m (64-bit)

**Comment by susan51531** [comment]
[官网demo](http://ueditor.baidu.com/website/onlinedemo.html) 现在的版本也有这个问题，
无法知道确切的版本号，build时间为  Sat Jun 04 2016 11:30:11 GMT+0800 (中国标准时间)

重现步骤:
1:找个优酷视频URL如:`http://player.youku.com/player.php/sid/XMTY3Mjk2NDI0OA==/v.swf`
2:插入视频，粘贴URL
3:编辑区出现视频默认图标，切换成html源码显示，此时看到的是embed标签
4:切换回所见即所得模式，之前的默认图标消失
5:切换成html源码，此时视频变成img标签 spacer.gif 视频url信息在_url中
6:预览时只按img显示spacer.gif,1x1px的图片

**Comment by wonderlq** [comment]
xss过滤的问题吧，试试在ueditor.config.js 中把xss过滤的相关设置成false，默认是true
