### ISSUE TITLE
UBuilder 无法下载

### ISSUE THREAD

**Issue by 17771258** [fex-team/ueditor#2978]
选择好功能后点击下载资源包 
页面提示 

UBuilder Error!
create temporary directory error!

请检查服务器情况。谢谢。

**Comment by zhyee** [comment]
没人管，哎

**Comment by 17771258** [comment]
现在还是无法下载啊！！！

**Comment by 17771258** [comment]
@Phinome 目前还是存在这个问题 是不支持自定义下载了是吗？
