### ISSUE TITLE
输入中文字符时，不触发contentChange事件无法实现统计字数；看到有相关issue，但无解决办法，期待反馈

### ISSUE THREAD

**Issue by lixin1991** [fex-team/ueditor#2982]
在火狐下有此问题，且只有中文状态下才出现

**Comment by willmao** [comment]
mac下也有，https://github.com/fex-team/ueditor/issues/2977
可以改一下代码。。。。

**Comment by lixin1991** [comment]
@willmao 情况有所不同，输入中文字符时   连keydown事件都不触发..   有建议吗

**Comment by willmao** [comment]
@lixin1991 火狐多少版本？我几天前在v31上遇到过不能触发keydown的问题，以为是低版本的问题就没多看

**Comment by lixin1991** [comment]
@willmao  龙蕊40       Ueditor其他功能正常

**Comment by willmao** [comment]
@lixin1991　这个问题主要是firefox中文下的keydown事件不能成功触发,中文状态下连续输入时，只有选择的那个空格键或者数字键有keyup事件触发，可以修改那段代码，保存一下数据触发contentChange事件。
在上述情况下，第一次输入的时候是更新undo按钮的状态是有问题的，ueditor里判断是否可以undo是用!!this.list[this.index - 1]这个条件，第一次输入保存后,index=list.length-1 =>0，上面条件返回undined，所以undo状态显示没有可以撤销的，这又是一个bug

**Comment by lixin1991** [comment]
我这边单字输入也无法获取到事件，  您是说keyup事件是可以触发到的吗？好像没有测试到… 你说的是具体哪行代码呢？  undo按钮的问题目前不考虑， 自定义按钮时已去掉。  感谢您的回复。

**Comment by lixin1991** [comment]
@willmao 我这边keyup事件同样无法触发， 不过经测试 中文输入时会触发输入法事件， 在compositionend事件中添加 保存数据 从而触发的contentChange ; 感谢提供思路；[https://github.com/fex-team/ueditor/blob/dev-1.5.0/_src/plugins/undo.js#L228](url)

**Comment by maoziliang** [comment]
contentChange的问题试试input事件吧
``` javascript
$(editor.body).on('input', () => {
  console.log(editor.getContent());
});
```
看能不能解决你们的问题。
