### ISSUE TITLE
最新版 Google Chrome 浏览器，点击上传图片时，等待非常久（重复点击会出现N个文件浏览对话框）

### ISSUE THREAD

**Issue by tianwei02** [fex-team/ueditor#2983]
最新版 Google Chrome 浏览器，点击上传图片时，等待非常久（重复点击会出现N个文件浏览对话框）

我们更换了许多电脑测试，是一样的。包括在官方演示页面上也是相同的结果。希望百度尽快修复该问题。

**Comment by terrywamg** [comment]
我也发现了相同的现象。
希望问题早点解决

**Comment by cdiwo** [comment]
我也是遇到了Chrome版本 52.0.2743.116 (64-bit)，之前的Chrome51没有问题，应该是Ueditor点击时触发input file的click()事件延迟

**Comment by cdiwo** [comment]
问题出处已找到，是通过js创建input file元素的时候accept属性为"image/*",这个地方修改为"image/jpeg,image/png"就可以正常弹出了

**Comment by Battlefield** [comment]
上次问这个问题快几个月了，终于可以解决了！ 习惯了Google Chrome，出现这种问题有点头疼。

**Comment by syifeng** [comment]
表示也遇到了这个问题，还有这个本来用这都好好的，服务器也没动，怎么就突然上传图片就出现问题了，说后端配置有问题
http://ip/ueditor/jsp/controller.jsp?action=config&&noCache=1472133232119 500 (Internal Server Error)
请求后台配置项http错误，上传功能将不能正常使用！

**Comment by Battlefield** [comment]
请求后台配置项http错误，偶尔会出现，就是加载上传配置文件失败，具体原因有待排查！刷新一次一般也就可以上传了。

**Comment by syifeng** [comment]
------------------ 原始邮件 ------------------
发件人: "Wei Wang";<notifications@github.com>;
发送时间: 2016年8月26日(星期五) 下午3:30
收件人: "fex-team/ueditor"<ueditor@noreply.github.com>; 
抄送: "动感地带"<935323727@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [fex-team/ueditor] 最新版 Google Chrome 浏览器，点击上传图片时，等待非常久（重复点击会出现N个文件浏览对话框） (#2983)




请求后台配置项http错误，偶尔会出现，就是加载上传配置文件失败，具体原因有待排查！刷新一次一般也就可以上传了。

**Comment by W4U** [comment]
@Battlefield 怎么解决的问题？麻烦您说明一下，谢谢

**Comment by mustcarrayout** [comment]
@Battlefield 我用的最新版的chrome(53.0)还是出现这个问题。
附件上传点击上传文件，打开文件选择框很快，但是多图片上传就很慢。单图片也很慢。求怎么解决。谢谢

**Comment by mustcarrayout** [comment]
@Battlefield  问题解决了，谢谢分享

**Comment by okfirelee** [comment]
是怎么解决的这个问题 现在最新版问题有点多啊 视频上传那块也有问题 视频上传再点HTML切换 src就没了,.....

**Comment by okfirelee** [comment]
通过js创建input file元素的时候accept属性为"image/*",这个地方修改为"image/jpeg,image/png"就可以正常弹出了 @fex-team 已经解决

**Comment by zhulp80** [comment]
@okfirelee  @cdiwo 这个input标签的文件在哪儿呢？

**Comment by debmzhang** [comment]
@zhulp80 在 ueditor.all.js ueditor.all.min.js 文件里, 搜索 accept 就找到了

**Comment by 6haoxiaowanzi** [comment]
修改ueditor.all.js还有image.js 找到accept="image
将image/*修改为:"image/jepg,image/png.image/jpg"即可

**Comment by zxbetter** [comment]
通过把 accept="image/*" 修改为:"image/jepg,image/png.image/jpg"得到了解决。谢谢上面的答案。

**Comment by zaleweb** [comment]
@debmzhang  在 ueditor.all.js ueditor.all.min.js 文件里, 搜索 accept 就找到了

**Comment by cdiwo** [comment]
@zaleweb 把ueditor/dialogs/image/image.js这个文件的accept也修改了
