### ISSUE TITLE
解决ueditor1_4_3_3-utf8-jsp 插入网络视频无法生成代码的问题

### ISSUE THREAD

**Issue by zhangjx1** [fex-team/ueditor#2984]
插入到编辑器无法生成视频代码
替换ueditor.all.js 到ueditor1_4_3_2-utf8-jsp版本的ueditor.all.js
如果还是报错的话继续替换vedio.js

因为我的问题就是没有办法生成视频代码。
这样做了可以生成代码。查看html标签也是没有问题的。

官网的线上demo和下载下来最新版demo应该不是一个版本的。

**Comment by huzhengguang** [comment]
是回退到1_4_3_2版本吗  也就是说 把1_4_3_3版本的ueditor.all.js放到1_4_3_2版本中覆盖掉，然后用1_4_3_2版本是吗

**Comment by dengdaijiushi** [comment]
大家怎么解决的 啊？

**Comment by dengdaijiushi** [comment]
我用1.4.3.2版本也不行

**Comment by zhangjx1** [comment]
是用1.4.3.2中的ueditor.all.js覆盖1.4.3.3中的ueditor.all.js文件。你反了

**Comment by wonderlq** [comment]
xss过滤的问题吧，
在ueditor.config.js中,
                 xssFilterRules: false
		//input xss过滤
		,inputXssFilter: false
		//output xss过滤
		,outputXssFilter: false
设置成这样，可以试下
