### ISSUE TITLE
为啥添加了视频点击源码，SRC会变为空

### ISSUE THREAD

**Issue by he4152** [fex-team/ueditor#2985]

**Comment by apollo47** [comment]
我也遇到同样问题，第二次切到html页面，video的src为空了。
有时候切换到html，video标签都没了。
ueditor 1.4.3

**Comment by bb7788** [comment]
1.4.3 貌似确实有这个问题，1.4.3.2 可以正常使用

**Comment by c295883531** [comment]
同上

**Comment by okfirelee** [comment]
同上

**Comment by okfirelee** [comment]
1.4.3.3版本存在如上问题 解决方法 还原成1.4.3.2 下载ueditor1_4_3_2 然后将里面第一层的JS全部替换到新版本中 进行版本回退 这是这个版本存在的bug....具体原因肯定是JS过滤标签规则出现问题 ...我也没时间排查了 这样比较省事！

**Comment by dengdaijiushi** [comment]
版本回退后也解决不了，网络视频无法生成代码的问题，网络视频保存时没有地址？

**Comment by wangshunwei219** [comment]
已解决（版本号1.4.3.3）：打开editor根目录下的ueditor.config.js，修改第365行“,whitList:”，改为“,whiteList:”。各位朋友不妨一试

**Comment by yyhhn2007** [comment]
刚才修改了whiteList发现点击html还是src空，晕掉折腾了一上午没搞懂啥原因
