### ISSUE TITLE
配置完了，运行时报错：获取后台配置项请求出错，上传功能将不能正常使用！

### ISSUE THREAD

**Issue by FlyangToCky** [fex-team/ueditor#2997]
问题描述
1.按照文档，可以访问controller.jsp并获取同样的返回信息，应该是配置正确了，但是运行时就报错：
“获取后台配置项请求出错，上传功能将不能正常使用！”
2.在火狐下刷新页面可以使用，其他浏览器都不行

**Comment by Geek-Icebreaker** [comment]
你好。楼主。你是更改了serverUrl默认上传地址出现的后台配置项请求出错的吗？
