### ISSUE TITLE
!!!实际验证，图片转存功能在1.4.3.3中无法使用，1.4.3.2中可使用，希望修复下！

### ISSUE THREAD

**Issue by syxuwen** [fex-team/ueditor#2999]
**下图为1.4.3.2版本**
![image](https://cloud.githubusercontent.com/assets/13964970/17737848/866f0222-64c1-11e6-8c50-604326a81200.png)

**下图为1.4.3.3版本**
![image](https://cloud.githubusercontent.com/assets/13964970/17737938/e1d89e2a-64c1-11e6-850a-e0bb54450abb.png)

遇到同样问题的小伙伴顶起来

**Comment by xjrzt** [comment]
同问+1

**Comment by adasir** [comment]
解决办法
1、修改ueditor.all.min.js文件，
搜索  function(d,e){c[b].indexOf(e)===-1&&a.setAttr(e)}
替换成  function(d,e){if(c[b].indexOf(e)===-1&&e!='style'&&e!='word_img')a.setAttr(e)}

UE.plugins.xssFilter 安全机制导致的
