### ISSUE TITLE
为什么UEditoer一直不能下载？

### ISSUE THREAD

**Issue by peeppp** [fex-team/ueditor#3004]
想使用UBulider定制一个编辑器，但始终不能下载，出现

UBuilder Error!
create temporary directory error!

已经很长很长时间了，为什么？mini版也不能正常下载

**Comment by atxkm** [comment]
百度要屎了吗。别啊。这几个开源的东西还是很不错的吗，能成立个社区，让别人维护么。。。

**Comment by bmkj** [comment]
同问，无法自定义打包下载
