### ISSUE TITLE
本地可以上传图片  部署到服务器上就不行

### ISSUE THREAD

**Issue by lameone1** [fex-team/ueditor#3012]
如标题所示，修改config.json 中的imageUrlPrefix的图片访问路径前缀为上片上传的服务器ip还是无效

**Comment by syifeng** [comment]
我的程序服务器上都跑了好几个月了，突然给我报这个问题，都说是修改前缀，本地没问题，上传就错

**Comment by 859988748** [comment]
看看Uploader.class.php里面的$_SERVER['DOCUMENT_ROOT']对不对
