### ISSUE TITLE
1.4.3.3版本实现上传图片按照指定宽度或者高度进行压缩上传的解决过程

### ISSUE THREAD

**Issue by lijie19866** [fex-team/ueditor#3013]
看到很多人在Issue里面提问关于1.4.3.3版本上传图片只能按照最长边压缩的问题，但是实际应用环境中，通常只需要压缩宽度即可。
在百度上搜索的解决方案也没有几个能真正解决问题，经过自己研究，结合之前有人发过的一些方法，终于把这个问题解决了，下面把过程给大家分享一下，希望能够对大家有所帮助：

我用的是asp版本，其他版本的解决方法应该也差不多。

实现过程：
首先找到Ueditor的配置文件config.json，添加如下代码：
`"imageCompressSide" : 1, /*等比压缩的基准，0为按照最长边，1为按照宽度，2为按照高度  1.4.3官方版本无此参数，自行添加 */`

![1](https://cloud.githubusercontent.com/assets/21252157/17992422/c04b055e-6b79-11e6-9359-2550b60866bc.jpg)

其次找到ueditor/dialogs/image/image.js，找到如下代码（在380行到397行之间）：
`width: imageCompressBorder,`
`height: imageCompressBorder,`
修改为如下代码：
`width: '1' == editor.getOpt('imageCompressSide') ? imageCompressBorder : 99999,`
`height: '2' == editor.getOpt('imageCompressSide') ? imageCompressBorder : 99999,`
保存即可生效，这样再上传图片时，会自动判断按照什么边为基准进行压缩。

![2](https://cloud.githubusercontent.com/assets/21252157/17992462/1210434a-6b7a-11e6-95b8-97907f732b99.jpg)

实际调试过程中，发现部分图片不能实现压缩，在“是否保留头部meta信息”后添加“单位字节”控制代码，问题解决（数值设定为0.1都不行，设为0.01后就可以了，不知道什么原因）：
`// 是否保留头部meta信息。`
`preserveHeaders: true,`
`// 单位字节，如果图片大小小于此值，不会采用压缩。`
`compressSize: 0.01`

![3](https://cloud.githubusercontent.com/assets/21252157/17992468/27dbf87c-6b7a-11e6-8729-c1992242d598.jpg)

**Comment by lijie19866** [comment]
说明一下，用这个方法可以实现多图上传自动压缩宽度，单图上传我也还没解决，暂时也没时间去搞

**Comment by ljnchn** [comment]
有用，多谢。

**Comment by Phinome** [comment]
赞，后续我会花点时间整理一下。
