### ISSUE TITLE
加载到widget.js的时候报错

### ISSUE THREAD

**Issue by 317599265** [fex-team/ueditor#3017]
加载editor_api.js的时候，ui/widget.js以上的都没问题 ，但是以下的全部报错 
ui/widget.js是这个错误 ReferenceError: jQuery is not defined
后面几个JS的错误为  UM.ui is undefined

**Comment by Anikinly** [comment]
really

**Comment by Phinome** [comment]
UM依赖 jquery ，你加载了么？
