### ISSUE TITLE
reactjs中使用ueditor，切换路由的时候，报Cannot read property 'getDom' of undefined

### ISSUE THREAD

**Issue by Say-Hello** [fex-team/ueditor#3021]
reactjs中使用ueditor，切换路由的时候，报Cannot read property 'getDom' of undefined

**Comment by Dafrok** [comment]
在componentWillUnmount的时候释放UEditor
多看文档

**Comment by Say-Hello** [comment]
`componentWillUnmount(){
	this.editor && this.editor.destroy();
}`我释放了，不行啊

**Comment by Say-Hello** [comment]
@Dafrok `componentWillUnmount(){
		this.editor && this.editor.destroy();
	}` 我释放了，如果不释放的话，下次就不渲染，释放了也报getDom没找到

**Comment by Dafrok** [comment]
componentWillUnmount的时候DOM节点已经被移除了，Ueditor在destroy的时候找不到节点就报错了。研究下react-router的setRouteLeaveHook，想办法在unmount之前释放Ueditor。生命周期相关问题请先仔细阅读文档。

**Comment by dreamcog** [comment]
遇到一个类似的问题。
@Dafrok 

1.在react-router里面的确已经调用了destroy的方法。但是还是在偶尔时候会有错误产生。具体描述如下：

情况1：
- 点新建
- 回到列表页面
- 再去新建
- 再回到列表页面 （没有错误）

情况2：
- 点新建
- 输入一些字符串
- 回到列表页面。报错：reader.entry.js:63077 Uncaught TypeError: Cannot read property 'lang' of undefined

多次测试后，发现是如果在ueditor里面有过输入行为就会产生这个错误。路由的调度如下图：

![2016-09-07 1 29 35](https://cloud.githubusercontent.com/assets/1401184/18283988/9d758d04-749a-11e6-8e80-c281c8329b62.png)

仅在页面Ueditor被输入文字后跳转会报这个错误。其他未见异常。
感谢！

附上释放代码：

![2016-09-07 1 31 06](https://cloud.githubusercontent.com/assets/1401184/18284022/c811ecce-749a-11e6-8105-ad9a917a329e.png)

由父组建，在创建时候设置。
