### ISSUE TITLE
前端使用Ueditor或HtmlBox之类的编辑器，输入文本信息后，传送给后端的Controller，由Controller保存至数据库。

### ISSUE THREAD

**Issue by s0948013** [fex-team/ueditor#3022]
我想实现一个功能：
前端使用Ueditor或HtmlBox之类的编辑器，输入文本信息后，传送给后端的Controller，由Controller保存至数据库。我用的是Spring mvc。
我想问的是：后台的Controller如何才能获得Ueditor或HtmlBox编辑的文本信息（暂时只考虑文本）？我创建了一个Data类，其中的articleContent字段与Ueditor/HtmlBox中的textarea是同名的。再把Data类当做参数传入Controller。可是，这样不行？传入的是null？

**Comment by zhugesiqing** [comment]
all()
