### ISSUE TITLE
ueditor 视频标签中的src属性值变成空

### ISSUE THREAD

**Issue by c295883531** [fex-team/ueditor#3026]
ueditor使用上传视频后 点击html查看代码后又返回视图界面，发现视频标签中的src属性值变成空
直接提交到后台发现获取到的数据中 src属性值也是空

我使用的是 google chrome浏览器， 版本是 版本 46.0.2490.80

**Comment by liuman2010** [comment]
我也遇到这样的情况。还没解决。

**Comment by wangshunwei219** [comment]
已解决（版本号1.4.3.3）：打开editor根目录下的ueditor.config.js，修改第365行“,whitList:”，改为“,whiteList:”。各位朋友不妨一试

**Comment by yyhhn2007** [comment]
发现视频src过滤edge浏览器不支持

**Comment by ycz0926** [comment]
同问下，这个问题如何修复呢？
