### ISSUE TITLE
请问有人和我一样图片选择框特别慢才能弹出吗

### ISSUE THREAD

**Issue by rocing** [fex-team/ueditor#3028]
请问有人和我一样图片选择框特别慢才能弹出吗？
大图上传和多图上传的本地图片选择框特别卡，大约点击后5秒钟才能弹出。有人和我一样问题吗

**Comment by 6haoxiaowanzi** [comment]
我的也是

**Comment by anyexinglu** [comment]
我也是：
在mac/windows的chrome浏览器（最新版本：52.0.2743.116 (64-bit)）里，editor上传图片按钮，点击后很久（大约12s）才弹框

http://ueditor.baidu.com/website/onlinedemo.html

另外，在mac的safari没复现

**Comment by Phinome** [comment]
解决方案，参看：[https://github.com/fex-team/ueditor/wiki/FAQ](https://github.com/fex-team/ueditor/wiki/FAQ)
