### ISSUE TITLE
UEditor怎么自定义右键

### ISSUE THREAD

**Issue by lrose0716** [fex-team/ueditor#3029]
```
    最近在做一个工作流自定义表单，在UEditor里设计流程表单，现在想在原有的右键菜单加入自定义菜单，如添加“文本控件属性”，请问要怎么实现？
```

非常感谢！

**Comment by rocing** [comment]
**建议阅读文档**
enableContextMenu {Boolean} [默认值：true] //打开右键菜单功能
contextMenu {Object} //右键菜单的内容，可以参考plugins/contextmenu.js里边的默认菜单的例子，label留空支持国际化，否则以此配置为准

`[{
    label: '', //显示的名称
    cmdName: 'selectall', //执行的command命令，当点击这个右键菜单时
    exec: function() { //exec可选，有了exec就会在点击时执行这个function，优先级高于cmdName
        //this是当前编辑器的实例
        //this.ui._dialogs['inserttableDialog'].open();
    }
}]`

**Comment by lrose0716** [comment]
这个实现了，谢谢。
现在遇到一个问题，在ueditor里插入input text ，在这个文本框上使用右键时用getclosenode获取不到这个文本框，请问要怎么解决？

**Comment by urchinstarz** [comment]
【bug】反馈。。看到楼主的这个问题，刚好一起问。
右键建立GROUP的时候，会出现标题无法显示的情况。
例如：增加个叫fonttor的右键菜单组。zh-cn.js里面已经在contextMenu 里面增加了文字：'fonttor':"cut",调用的时候，
`{group:'lang.fonttor',
					icon:'background',
                    subMenu:[
                      { 
						label:'粗体',
                        cmdName:'bold'
                        },
						{ 
						label:'斜体',
                        cmdName:'italic'
                        },
						{label:'下划线',
                        cmdName:'underline'
                        },
                    ]
			},`
会出现文字不显示的情况，看html源码【class="edui-box edui-label edui-menuitem-label edui-default"】这个div里面完全没有内容，应该是调用不出来。单独用{cmdName:'fonttor'则可以！},等待回复。另外，请教一下，右键添加改变字体color 按钮或者弹出按钮的方法有没有示例？而且也找不到color的源码在哪里。。。
