### ISSUE TITLE
php版本的UE怎么集成阿里云OSS啊？

### ISSUE THREAD

**Issue by LinJie-Guo** [fex-team/ueditor#3035]
没有插件的话，提供个开发思路也可以啊。

**Comment by AzhiLee** [comment]
so easy,  官方主页都有把上传动作改为别的接口的。在常见问题的第5.2条，如何自定请求地址

> UE.Editor.prototype._bkGetActionUrl = UE.Editor.prototype.getActionUrl;
UE.Editor.prototype.getActionUrl = function(action) {
    if (action == 'uploadimage' || action == 'uploadscrawl' || action == 'uploadimage') {
        return 'http://a.b.com/upload.php';
    } else if (action == 'uploadvideo') {
        return 'http://a.b.com/video.php';
    } else {
        return this._bkGetActionUrl.call(this, action);
    }
}

然后，你懂了吧

**Comment by Phinome** [comment]
http://ueditor.baidu.com/website/thirdproject.html 提问前能不能先看看官网。。。
