### ISSUE TITLE
UEditor样式被过滤无法显示问题

### ISSUE THREAD

**Issue by flying2945** [fex-team/ueditor#3038]
uEditor1.4.3.3.net版本,如何关闭过滤 html head body 等标记,我已经将allowDivTransToP,将true设置为false，addInputRule方法中将switch代码段中的case style,script都删掉了，还是不行，请高手解决

**Comment by huangleyuan** [comment]
我的也是   也没用   肯定是版本问题  网上肯定是以前的方法

**Comment by varrant** [comment]
我也遇到了，如何解决呢？
