### ISSUE TITLE
添加视频地址，预览可以播放，可是getContent()获取不到视频代码内容

### ISSUE THREAD

**Issue by qingyunluck** [fex-team/ueditor#3053]
添加视频地址，预览可以播放，可是getContent()获取不到视频代码内容？这是什么原因？

**Comment by qingyunluck** [comment]
添加视频地址，预览可以播放，可是getContent()获取不到视频代码内容

**Comment by qingyunluck** [comment]
问题已解决，是下载的demo中的ueditor.config.js配置文件，过滤embed标签了。打开http://ueditor.baidu.com/website/onlinedemo.html将ueditor.config.js下载下来和本地的文件对比发现的。贴出来希望能帮助到其它网友！

**Comment by Mars1314** [comment]
怎么解决呢
