### ISSUE TITLE
谷歌浏览器升级版本 52.0.2743.82 m以上。多图上传需相应很长时间才能弹窗

### ISSUE THREAD

**Issue by tianzhukui** [fex-team/ueditor#3059]
谷歌浏览器升级版本 52.0.2743.82 m以上。多图上传需相应很长时间才能弹窗，请官方查证一下

**Comment by myowls** [comment]
是的，我也遇到了，求官方解释和解决办法

**Comment by Phinome** [comment]
[https://github.com/fex-team/ueditor/wiki/FAQ](https://github.com/fex-team/ueditor/wiki/FAQ)

**Comment by myowls** [comment]
试了，在ueditor.all.js没有使用
