### ISSUE TITLE
在浏览器中运行 net/controller.ashx，不能返回正确结果

### ISSUE THREAD

**Issue by Wehas** [fex-team/ueditor#3061]
按照文档做：
设置连接凭据。点击「链接为...」按钮，在弹出的对话框中指定一个对目录具有读写权限的用户（如 administrator），然后点确定。

设置连接凭据

设置完毕后，可以点击「测试设置...」来测试权限是否正常。

设置连接凭据

在浏览器中运行 net/controller.ashx，如果返回以下接过，则表示应用程序运行成功。

 {"state":"action 参数为空或者 action 不被支持。"}
## 如果你确认上述步骤已经执行，但是依然有问题，请给我们提 Issue，我们会尽快答复解决。

页面报错为：
“/Resources/ueditor/net”应用程序中的服务器错误。

配置错误
配置错误

说明: 在处理向该请求提供服务所需的配置文件时出错。请检查下面的特定错误详细信息并适当地修改配置文件。 

分析器错误消息: 未能找到 CodeDom 提供程序类型“Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”。

**Comment by Phinome** [comment]
.net 的程序已无法支持解答了，请教一下 .net 的高人吧~
