### ISSUE TITLE
UE演示中无法使用插入视频功能

### ISSUE THREAD

**Issue by lewiyue** [fex-team/ueditor#3063]
步骤：
1 进入UI演示页面，链接：http://ueditor.baidu.com/website/onlinedemo.html
2 点击工具栏中的视频，在弹出的视频框中输入一个flv的链接，提示输入的链接有误。
这个flv链接为http://f02.v1.cn/transcode/14394590FLVSDT14-3.flv ， 在地址里面可以直接打开并下载。我看ueditor的源代码是支持flv视频格式的。
请问哪些链接可以预览并插入，此链接不能插入的原因是？谢谢。

问题截图如下：
![1](https://cloud.githubusercontent.com/assets/10934139/18673231/9d2f1110-7f7d-11e6-8f2a-f07847612f50.png)

**Comment by anttake** [comment]
插入在线视频是不能带格式的。
