### ISSUE TITLE
页面上多个ue，上下移动内容就会消失

### ISSUE THREAD

**Issue by magicblack** [fex-team/ueditor#3064]
想实现添加多页文章时，动态创建多个ue，每个ue是一页内容。
现在发现一个问题，我动态创建的多个ue，想要每次点击上下移动交换位置，其中一个内容就会消失。
html内容大概是
table -> tr -> td ->ue    有多行。每行1个ue 。 
变量  current 和 prev 都是 tr 。

jquery代码：   current.after(prev);

**Comment by yhany** [comment]
我和你一样有这个问题，请问你解决了吗，是不是要每次getContent出来之后重新恢复过去
