### ISSUE TITLE
我设置内容改变监听获取编辑器内容，但是获取的内容不对。我是个菜鸟。

### ISSUE THREAD

**Issue by laolang81** [fex-team/ueditor#3065]
在单个上传过程中出现的问题，多个能正常获取到编辑器内容。下面是代码。

// 编辑器添加事件
                    UE.getEditor('container').addListener('afterSelectionChange', function(editor) {
                        // 获取编辑器中的内容（html 代码）
                        var img = UE.getEditor('container').getContent();
                        console.log("获取的编辑器内容:"+img);
                        我发现此处获取的内容不是编辑器内容，而是下面的
&lt;p&gt;&lt;img class=&quot;loadingclass&quot; id=&quot;loading_itcb9f70&quot; src=&quot;/UEditor/themes/default/images/spacer.gif&quot; title=&quot;正在上传...&quot;/&gt;&lt;/p&gt;

```
        }
});
```

**Comment by Phinome** [comment]
监听 `contentChange` 而不是 `afterSelectionChange`。

**Comment by Phinome** [comment]
http://ueditor.baidu.com/doc/ 这是 API 文档
