### ISSUE TITLE
点击单图上传按钮，总是持续10秒左右才弹出“选择图片”的窗口，如何缩短响应时间呢？

### ISSUE THREAD

**Issue by zhulp80** [fex-team/ueditor#3070]
点击单图上传按钮，总是持续10秒左右才弹出“选择图片”的窗口，如何缩短响应时间呢？
请大侠们指点。。。

**Comment by zhulp80** [comment]
问题出处已找到，是通过js创建input file元素的时候accept属性为"image/*",这个地方修改为"image/gif,image/jpeg,image/png,image/jpg,image/bmp"就可以正常弹出了

**Comment by wuxianlijiang** [comment]
是修改ueditor.all.min.js吗？我按您的办法修改了，还是没有效果。请求指导。

**Comment by Phinome** [comment]
https://github.com/fex-team/ueditor/blob/dev-1.5.0/_src/plugins/simpleupload.js#L31 如果是 ueditor.all.min.js 那就搜索 `type="file"`，找到紧随的`accept` 修改一下就可以了。

**Comment by wuxianlijiang** [comment]
可能我的配置位置不一样。解决方法如下：
打开 ueditor\dialogs\image.js
查找：
image/*
修改为：
image/gif,image/jpeg,image/png,image/jpg,image/bmp
即可解决。

ueditor\ueditor.all.min.js中也有相关配置，同样修改为好。
ueditor\third-party\webuploader\webuploader.js中亦有类似配置，如用到，也需要修改。
@Phinome

**Comment by Phinome** [comment]
好，dialogs 那个是多图上传的，webuploader 是上传功能的依赖，你先按照刚才说的修改吧，下午我会找时间更新 UEditor 的。
