### ISSUE TITLE
ueditor引用在线视频，无法生成html代码的解决方法

### ISSUE THREAD

**Issue by 1810979988** [fex-team/ueditor#3071]
ueditor引用在线视频，无法生成html代码的解决方法：ueditor.config.js中// xss过滤白名单加入如下标签即可
            embed:  [
                'type', 'class', 'style', 'pluginspage',
                'src', 'width', 'height', 'align', 'wmode',
                'play', 'loop', 'menu', 'allowscriptaccess',
                'allowfullscreen', 'id'
            ]

**Comment by lzm-zeem** [comment]
这个编辑器坑太多！
