### ISSUE TITLE
[firefox]mac ms word 纯文本粘贴 去style正则替换失败

### ISSUE THREAD

**Issue by ursulashan** [fex-team/ueditor#3072]
### 问题同上

> 粘贴内容为:
> 
> ```
> <style>@font-face {
>   font-family: "宋体";
> }@font-face {
>   font-family: "Cambria Math";
> }@font-face {
>   font-family: "@宋体";
> }@font-face {
>   font-family: "Cambria";
> }p.MsoNormal, li.MsoNormal, div.MsoNormal { margin: 0cm 0cm 0.0001pt; text-align: justify; font-size: 12pt; font-family: Cambria; }.MsoChpDefault { font-family: Cambria; }div.WordSection1 {  }</style>
> <p class="MsoNormal"><span style="font-size:48.0pt" lang="EN-US">derreretewt</span><span lang="EN-US"></span></p >
> ```
#### 通过 `filterPasteWord` 方法 处理结果为:

```
@font-face {
  font-family: "宋体";
}@font-face {
  font-family: "Cambria Math";
}@font-face {
  font-family: "@宋体";
}@font-face {
  font-family: "Cambria";
}p.MsoNormal, li.MsoNormal, div.MsoNormal { margin: 0cm 0cm 0.0001pt; text-align: justify; font-size: 12pt; font-family: Cambria; }.MsoChpDefault { font-family: Cambria; }div.WordSection1 {  }
<p class="MsoNormal"><span style="font-size:48.0pt" lang="EN-US">derreretewt</span><span lang="EN-US"></span></p >
```

仅去除了标签 但是标签里的内容仍然保留

**Comment by Phinome** [comment]
可能需要升级一下了。
