### ISSUE TITLE
图片上传混乱问题

### ISSUE THREAD

**Issue by gxy874368991** [fex-team/ueditor#3073]
目前图片上传混乱，我在网上找了一些方法，看他们说的是管用的，但是我更改了后不好使
//_this.imageList.push(json);修改为这个_this.imageList[$file.index()]=json;//按照选好的图片顺序上传
image.js文件    有人知道怎么办 吗

**Comment by hedahang** [comment]
https://github.com/fex-team/ueditor/pull/2659/commits/714fa0f0dc031d7555e0b194c87444ec685753af
