### ISSUE TITLE
后台配置项返回格式出错，上传功能将不能正常使用

### ISSUE THREAD

**Issue by shaocongWu** [fex-team/ueditor#3076]
环境：php+CodeIgniter框架

本地部署测试一切正常，但上传至服务器部署后编辑器图片上传按钮处于不可点击状态

后台返回信息为：后台配置项返回格式出错，上传功能将不能正常使用

查阅过一些相关资料，但查阅所得的结果大部分均为“后端配置项没有正常加载”的问题，似乎跟此问题有一定的区别。

目前有点迷茫，不清楚是否是imageUrlPrefix或是imagePathFormat的路径设置问题，仍在自行探索解决途径。

**Comment by Phinome** [comment]
先看看这篇文档：http://fex.baidu.com/ueditor/#dev-request_specification，看看是不是后端返回的格式有问题。
