### ISSUE TITLE
如何监控 编辑器中光标放在指定的元素中

### ISSUE THREAD

**Issue by flftfqwxf** [fex-team/ueditor#3083]
有以下需求，当用户将光标聚焦在一个DIV上时，自动选择住这个DIV里的IMG，
在UEDITOR中，应该如何实现，目前想到的方案，大概是使用selectionchange事件，但这个事件比较费性能，有无其他方案？？

**Comment by Phinome** [comment]
为啥要用 selectionchange 事件？你不是 focus 的时候选择么？那自然是 focus 事件，然后往后查找div 节点中的 img 。
