### ISSUE TITLE
Ueditor上传视频成功，预览也成功，查看HTML代码再返回，视频路径被清空

### ISSUE THREAD

**Issue by maxmas** [fex-team/ueditor#3089]
Ueditor上传视频成功，预览也成功，检视HTML代码如下

`<p>
    <video class="edui-upload-video  vjs-default-skin video-js" controls="" preload="none" width="420" height="280" src="/upload/201609/1475202106637.flv" data-setup="{}"></video>
</p>`

检视完HTML代码再返回预览介面，视频不见了，再查看HTML代码，发现视频路径被清空了

`<p>
    <video class="edui-upload-video  vjs-default-skin   video-js" controls="" preload="none" width="420" height="280" src data-setup="{}"></video>
</p>`

这个BUG 怎么解决呢?

系统环境：WIN XP
浏览器：Chrome 版本 49.0.2623.112 m

**Comment by SunShineSon** [comment]
这个问题已经有人问过了，我也是参考那个解决方案吧问题解决，希望对你有用
修改 ueditor.config.js 文件的368行，将 whitList 修改为 whiteList

**Comment by atxkm** [comment]
@SunShineSon 百度真是要玩了，这都没人管

**Comment by maxmas** [comment]
@SunShineSon , 
谢谢你的指点, 已经正常了 ^^

**Comment by Phinome** [comment]
1.4.3.3 版本增加了白名单过滤功能防止站点被 xss ，因此过滤了很多属性，需要自行配置。至于 @atxkm 与其抱怨不如像 @SunShineSon 那样做些有帮助的事儿。
