### ISSUE TITLE
后端配置项没有正常加载，上传插件不能正常使用！

### ISSUE THREAD

**Issue by onping** [fex-team/ueditor#309]
后端配置项没有正常加载，上传插件不能正常使用！
jsp 图片上传 
我该如何配置？

**Comment by Coca-code** [comment]
php ,配置贴个代码。

**Comment by helloworlda0** [comment]
@onping 怎么解决的

**Comment by csg0328** [comment]
UEditor
1.4.3在本地测试正常，传到服务器上就报 “后端配置项没有正常加载，上传插件不能正常使用！”
