### ISSUE TITLE
添加百度地图，无法添加动态地图，官方例子也有同样的问题

### ISSUE THREAD

**Issue by caiweiming** [fex-team/ueditor#3090]
在使用过程中，发现插图百度地图时，如果勾选了“插入动态地图”，则无法插入地图，一开始以为是我自己配置的问题，去官网的演示试了一下，也是同样的问题。

**Comment by niutianhu** [comment]
同样，前几天还没事这几天就不行了，添加地图图片没事，勾上动态地图就没反应了，希望官方尽快解决

**Comment by 13sai** [comment]
是的，所以我们用1.4.2版本

**Comment by Phinome** [comment]
地图的API变更了，UEditor 的升级暂时没有人力支持。
