### ISSUE TITLE
只有页面加载进来之后，通过点击某个按钮才能将内容显示到编辑器里面

### ISSUE THREAD

**Issue by luohagogo** [fex-team/ueditor#3091]
能不能在页面加载的时候，在$(document).ready(function(){
//显示数据
})
这里面直接显示？我调用给的方法提示错误，但是通过点击页面上按钮去调用方法却可以。

**Comment by chenpeiguang** [comment]
文档里有，直接把内容赋值到要初始化的容器中就可以了
