### ISSUE TITLE
有序列表问题

### ISSUE THREAD

**Issue by chenpeiguang** [fex-team/ueditor#3094]
我在编辑器里面直接输入“1.aaa”,按回车 后会直接变成有序列表，可以取消吗

**Comment by huaganshang** [comment]
同问，谢谢

**Comment by chenpeiguang** [comment]
解决了，看源码不能取消，要自己改一下源码

**Comment by tyn520215** [comment]
同问这个怎么解决

**Comment by chenpeiguang** [comment]
在150700行左右，有一个keydown事件，
 if (/^\s*1\s*\.[^\d]/.test(html)) {
                        // parent.innerHTML = html.replace(/^\s*1\s*\./,'');
                        rng.setStartAtLast(parent).collapse(true).select();
                        me.__hasEnterExecCommand = true;
                        // me.execCommand('insertorderedlist');
                        me.__hasEnterExecCommand = false;
                    }
把这个注释就可以了

**Comment by chenpeiguang** [comment]
在15700行左右，有一个keydown事件，
`if (/^\s1\s.[^\d]/.test(html)) {
// parent.innerHTML = html.replace(/^\s1\s./,'');
rng.setStartAtLast(parent).collapse(true).select();
me.__hasEnterExecCommand = true;
// me.execCommand('insertorderedlist');
me.__hasEnterExecCommand = false;
}`
把这个注释就可以了
