### ISSUE TITLE
不能自定义打包下载了

### ISSUE THREAD

**Issue by lvtao320** [fex-team/ueditor#3095]
使用官网的 http://ueditor.baidu.com/website/download.html#ubuilder 页面打包下载，提交后一片空白了...

**Comment by bmkj** [comment]
同问，不能自定义打包下载了

**Comment by xiaoheixiaoheia** [comment]
一样，今天想自定义打包之后就是空页面

**Comment by softxdlm** [comment]
就是为什么啊？不能打包了

**Comment by Phinome** [comment]
暂时不支持自定义打包了，在升级新的版本，后续会放出来~
