### ISSUE TITLE
ueditor 在edge 浏览器下不能实现单图和多图的上传

### ISSUE THREAD

**Issue by Dirmond** [fex-team/ueditor#3104]
1.  在window10 edge 浏览器按下 F12
2. 在window10 edge 浏览器下打开ueditor初始化之后页面
3. 控制台会出现 Permission denied 错误
4.  点击页面上的 单图上传 的按钮，没有任何反应
5.  点击页面上的 多图上传 的按钮，在弹出窗口里面没有 点击选择图片 按钮，所以在edge 浏览器上面不能进行多图上传
6. 以上的bug 请在edge 调试模式先才能进行重现（先打开控制台再进行以上操作）

**Comment by Phinome** [comment]
可能需要查查 edge 权限的问题。
