### ISSUE TITLE
ueditor 1.4.3 多图上传 PNG格式图片压缩不了

### ISSUE THREAD

**Issue by wolfish99** [fex-team/ueditor#3105]
ueditor 1.4.3 多图上传 PNG格式图片压缩不了，JPG文件正常可以压缩到"imageCompressBorder": 500,我设定的尺寸。PNG不行，跪求解决方案

**Comment by Phinome** [comment]
后端的问题，找个熟悉你选择的后端语言的人问问，或者搜索一下所选语言的 png 压缩
