### ISSUE TITLE
使用setContent方法时，提升Cannot set property 'innerHTML' of undefined

### ISSUE THREAD

**Issue by cnhero** [fex-team/ueditor#3108]
使用setContent方法时，提升Cannot set property 'innerHTML' of undefined

实例对象已经创建成功，并且界面上也能正常显示编辑器。

查看源代码发现：
问题出现在

>  me.body.innerHTML = (isAppendTo ? me.body.innerHTML : '') + html;
> 
> body为空

请问是什么原因呀？

**Comment by mrtansl** [comment]
editor.addListener("ready", function () {
				        // editor准备好之后才可以使用
         editor.setContent("xxx");
				})
