### ISSUE TITLE
PHP版1.4.2和1.4.3上传图片提示“找不到临时文件”

### ISSUE THREAD

**Issue by flyskyz0668** [fex-team/ueditor#311]
两台服务器，都是Windows 2003系统，一台正常，另一台单图、多图上传都提示“找不到临时文件”。
换成1.3.6 PHP版，两台服务器都正常。

**Comment by dreamylife** [comment]
php.ini 里面有上传临时目录upload_tmp_dir ，如果是win服务器，去到C:/windows/Temp目录，右键属性，给予USERS权限就好了。如果是LINUX，同样去/temp 给个权限就行了。
