### ISSUE TITLE
在火狐和IE中无法粘贴qq的截图

### ISSUE THREAD

**Issue by weiruifeng** [fex-team/ueditor#3111]
将QQ截图直接粘贴到UEditor里，在chrome浏览器里粘贴成功了但是在火狐浏览器里面没有粘贴成功，追踪了下源代码，发现了getPasteImage方法是用来获取剪切板里的内容，代码如下
 function getPasteImage(e){
        return e.clipboardData && e.clipboardData.items && e.clipboardData.items.length == 1 && /^image\//.test(e.clipboardData.items[0].type) ? e.clipboardData.items:null;
    }
但该方法只有chrome支持，请问我该如何才能将QQ的截图在火狐浏览器里面粘贴呢？

**Comment by Phinome** [comment]
看了一下是 firefox 的 bug。目前没找到合适的解决方案。
