### ISSUE TITLE
php-utf8版本中/php/Uploader.class.php第66行构造方法最后一行可能导致BUG

### ISSUE THREAD

**Issue by a88027180** [fex-team/ueditor#3114]
环境 php7+apache2.4
已经编译进iconv扩展
但是使用的是glibc版本
phpinfo的展示是这样的
iconv support   enabled
iconv implementation    glibc
iconv library version   2.12

php-utf8版本中/php/Uploader.class.php第66行构造方法最后一行为
$this->stateMap['ERROR_TYPE_NOT_ALLOWED'] = iconv('unicode', 'utf-8', $this->stateMap['ERROR_TYPE_NOT_ALLOWED']);
会导致php错误
iconv('unicode', 'utf-8','任何字符串') 都会返回false,会执行失败
**在仔细检查了一下其他转换都是正常的，无论utf-8,gbk还是别的编码
但是从unicode转到其他或者从其他转到unicode都会返回false**

另外使用libiconv版本是正常的

最后
感觉这句代码并没有什么存在的必要-0-

**Comment by Phinome** [comment]
已经不知道当初的作者为啥这样写了，如果不影响其他的功能，你可以在你本地将之删除。
