### ISSUE TITLE
附件图标地址暴露后台地址的BUG，有没有一个官方的配置项

### ISSUE THREAD

**Issue by bhzln** [fex-team/ueditor#3115]
在文档里面没有找到可以调整附件图标地址的参数，不知道是尚未设计这个方法还是让用户自己用替换字符串处理，目前百度到的只有http://www.91ctc.com/article/article-386.html，这个帖子是2015年的

**Comment by Phinome** [comment]
先按照那个改一下吧，代码应该是没有变过的。
