### ISSUE TITLE
在https环境中，如何配置才能让百度地图功能正常使用？

### ISSUE THREAD

**Issue by YingzhiLin** [fex-team/ueditor#3116]
在https环境下，百度地图的文件无法加载，在Chrome浏览器中提示下面信息：

Mixed Content: The page at 'https://xxx.xxx.xxx/' was loaded over HTTPS, but requested an insecure script 'http://api.map.baidu.com/api?v=1.1&services=true'. This request has been blocked; the content must be served over HTTPS.

所以无法加载百度地图API，百度地图功能无法使用。
在ueditor.config.js文件中，没有找到相应的配置参数。

请提供解决的方法，谢谢！

**Comment by DieMoe233** [comment]
百度地图的API地址我看了看是支持https的，只不过默认是http而已，你可以关键字搜索api.map.baidu.com然后改一改地址试试？

**Comment by YingzhiLin** [comment]
先谢谢 DieMoe233的提示。我对js的语法不怎么熟悉，所以对文件做了下面这个改动，勉强可以用了。

**修改**

1. ueditor.all.min.js 文件，搜索 api.map.baidu.com，找到后把前面的http:// 改成 //，去掉了http:
2. dialogs/map/文件夹的 map.html和show.html文件，修改如下：

第一处
`<script type="text/javascript" src="//api.map.baidu.com/api?v=1.1&services=true&s=1"></script>`

第二处
`var url = "//api.map.baidu.com/staticimage?center="`

**结果**

勉强可用。

但至少提示有两个问题：

1. https://api.map.baidu.com/res/11/bmaps.css 该文件不存在
2. http://api.map.baidu.com/getmodules?v=1.1&mod=oppc,marker,control 非https不能访问。

**Comment by YingzhiLin** [comment]
还要增加一个修改位置。
第三处
map.html文件的脚本中差不多是56行这个位置上，
原来是
`marker.setPoint(point); `
改成
`marker.setPosition(point);`
