### ISSUE TITLE
Ueditor 放到 CDN 上，跟项目分离

### ISSUE THREAD

**Issue by doushichao** [fex-team/ueditor#3117]
当 Ueditor 放到 CDN 上，跟项目分离的时候，表情出现问题，，internal.js:4 Uncaught SecurityError: Blocked a frame with origin "http://xxxxx" from accessing a frame with origin "http://xxxxxxx". Protocols, domains, and ports must match.

**Comment by Phinome** [comment]
跨域了，你要保证两个是在同一个域下

**Comment by doushichao** [comment]
Ueditor 不能放到 CDN 上么？放到 CDN 上 域肯定不一样呀，一个是 www.xxx.com 一个是 cdn.xxx.com

**Comment by Phinome** [comment]
http://rawgit.com/ 你可以自行放置，不是什么都需要我们来提供吧？
