### ISSUE TITLE
如何获取百度编辑器内所有的图片地址

### ISSUE THREAD

**Issue by Messilimeng** [fex-team/ueditor#3124]
需求是 现在发微信图文消息 消息的内容内图片都要通过微信的接口上传图片

现在我想获取里面的所有图片地址 然后一次性上传 成功后再替换原来的地址

我想问一下有没有好点的方法可以获取呢？

**Comment by zengzhan** [comment]
var temp_imgs = ue.document.getElementsByTagName("img");
                for (var i = 0; i < temp_imgs.length; i++) {
                    var isrc = temp_imgs[i].src;
                    if (/^((?!qqzeng.com).)*$/.test(isrc)) {}
