### ISSUE TITLE
图片上传配置问题

### ISSUE THREAD

**Issue by wjkang** [fex-team/ueditor#3125]
后端返回配置项为
"{\"imageActionName\":\"UploadImage\",\"imageFieldName\": \"upfile\",\"imageCompressEnable\":\"true\",\"imageCompressBorder\": 1600,\"imageInsertAlign\": \"none\",\"imageUrlPrefix\": \"\",\"imageAllowFiles\": [\".png\", \".jpg\", \".jpeg\", \".gif\", \".bmp\"]}"
上传图片的时候报错： errorHandler is not defined(…)

后端返回配置改为 
{"imageActionName":"UploadImage","imageFieldName": "upfile","imageCompressEnable":"true","imageCompressBorder": 1600,"imageInsertAlign": "none","imageUrlPrefix": "","imageAllowFiles": [".png", ".jpg", ".jpeg", ".gif", ".bmp"]} 才正常

前一种字符串格式可以转成JSON，不应该报错才对

**Comment by Phinome** [comment]
你还要是返回第一种格式，把外层的引号转义啊，这明显是后端返回有问题啊~
