### ISSUE TITLE
1.4.3版本上传附件中文文件名失败如何解决？

### ISSUE THREAD

**Issue by lijie19866** [fex-team/ueditor#3127]
1.4.3GBK ASP版本
在上传图片或者文件时，中文名称的附件，有些可以成功，有些就直接报上传失败
在网上搜索了很多方法，都无法解决，求大神帮助，不胜感激

**Comment by lijie19866** [comment]
十分无助啊，有官方人员看到吗？
我从官网下载了，没有做任何改动直接部署，也是这个问题
请问如何可以联系到你们？
这个问题已经困扰了我很久了，一直没解决
请问有没有好心人能帮我看看什么原因？
我一定配合调试

**Comment by Phinome** [comment]
这个问题，既然你是采用 asp 的版本，那么找一个懂 asp 的人，或许会有帮助。
