### ISSUE TITLE
有序列表和无序列表的序号图标没有了

### ISSUE THREAD

**Issue by tonyjian** [fex-team/ueditor#3137]
例如中文的序号的，发现是使用百度服务器上的图片的，但现在访问不了了，403，求解决

**Comment by fly2xiang** [comment]
无序列表中的破折号，小圆圈不能使用。
使用的这两个图片403：

[](http://bs.baidu.com/listicon/dash.gif)
[](http://bs.baidu.com/listicon/dot.gif)
