### ISSUE TITLE
使用自定义请求地址上传图片，前端如何获取上传成功后返回的json 数据？

### ISSUE THREAD

**Issue by elonbase** [fex-team/ueditor#3140]
版本：1.4.3.3

自定义上传请求地址：
UE.Editor.prototype.getActionUrl = function(action) {
    if (action == 'uploadimage' || action == 'uploadscrawl' || action == 'uploadimage' || action == 'catchimage') {
      return 'http://api.xxxxxx.com.cn/file/uploadImg/'+token;
    } else {
      return;
    }
}

后端返回JSON:
{code:200,data:"http://XXXX.com/builder_images/18ffcd2f-beb0-4996-80a7-c5825189135f.jpg",status:true}

**Comment by edeye** [comment]
没有这个功能,写的很死,只能配置imageUrlPrefix为图片的前缀,然后返回固定格式的json,你这种返回的json是不符合ueditor的格式的,你可以看下这个:http://fex.baidu.com/ueditor/#dev-request_specification
而且也根本没说,如果服务器返回的哦state是Fail的话,前端是如何显示的
