### ISSUE TITLE
SPAN标签被过滤掉了

### ISSUE THREAD

**Issue by jiduwuyu** [fex-team/ueditor#3146]
`<p><strong>原告名称：</strong><span>张三</span></p><br/>`

，在编辑器里面通过html查看后变成了` <p><strong>原告名称：</strong>张三</p><br/>`，我也修改了ueditor.all.js 里面的  $removeEmpty里面去掉了span没有用，实在不知道怎么办了

**Comment by lenyi** [comment]
解决了吗  我也遇到了

**Comment by MoonRaito** [comment]
ueditor.config.js

		// xss过滤白名单 名单来源: https://raw.githubusercontent.com/leizongmin/js-xss/master/lib/default.js
		,whitList: {


添加 span
