### ISSUE TITLE
分享一个自己写的GO语言与Ueditor的配置文件

### ISSUE THREAD

**Issue by jinfei** [fex-team/ueditor#3162]
由于官方配置文件没有GO语言版本的，于是只能自己去书写一个。以下是我的代码，希望能帮到需要的同学：）

> 
package config

type upload_config struct {
	ImageActionName     string   `json:"imageActionName"`     // 执行上传图片的action名称
	ImageFieldName      string   `json:"imageFieldName"`      // 提交的图片表单名称
	ImageMaxSize        int      `json:"imageMaxSize"`        // 上传大小限制，单位B
	ImageAllowFiles     []string `json:"imageAllowFiles"`     // 上传图片格式显示
	ImageCompressEnable bool     `json:"imageCompressEnable"` // 是否压缩图片默认是true
	ImageCompressBorder int      `json:"imageCompressBorder"` // 图片压缩最长边限制
	ImageInsertAlign    string   `json:"imageInsertAlign"`    // 插入的图片浮动方式
	ImageUrlPrefix      string   `json:"imageUrlPrefix"`      // 图片访问路径前缀
	ImagePathFormat     string   `json:"imagePathFormat"`

	// 涂鸦图片上传配置项
	ScrawlActionName  string `json:"scrawlActionName"` // 执行上传涂鸦的action名称
	ScrawlFieldName   string `json:"scrawlFieldName"`  // 提交的图片表单名称
	ScrawlPathFormat  string `json:"scrawlPathFormat"` // 上传保存路径可以自定义保存路径和文件名格式
	ScrawlMaxSize     int    `json:"scrawlMaxSize"`    // 上传大小限制，单位B
	ScrawlUrlPrefix   string `json:"scrawlUrlPrefix"`  // 图片访问路径前缀
	ScrawlInsertAlign string `json:"scrawlInsertAlign"`

	// 截图工具上传
	SnapscreenActionName  string `json:"snapscreenActionName"`  // 执行上传截图的action名称
	SnapscreenPathFormat  string `json:"snapscreenPathFormat"`  // 上传保存路径可以自定义保存路径和文件名格式
	SnapscreenUrlPrefix   string `json:"snapscreenUrlPrefix"`   // 图片访问路径前缀
	SnapscreenInsertAlign string `json:"snapscreenInsertAlign"` // 插入的图片浮动方式

	// 抓取远程图片配置
	CatcherLocalDomain []string `json:"catcherLocalDomain"`
	CatcherActionName  string   `json:"catcherActionName"` // 执行抓取远程图片的action名称
	CatcherFieldName   string   `json:"catcherFieldName"`  // 提交的图片列表表单名称
	CatcherPathFormat  string   `json:"catcherPathFormat"` // 上传保存路径可以自定义保存路径和文件名格式
	CatcherUrlPrefix   string   `json:"catcherUrlPrefix"`  // 图片访问路径前缀
	CatcherMaxSize     int      `json:"catcherMaxSize"`    // 上传大小限制，单位B
	CatcherAllowFiles  []string `json:"catcherAllowFiles"` // 抓取图片格式显示

	// 上传视频配置
	VideoActionName string   `json:"videoActionName"` // 执行上传视频的action名称
	VideoFieldName  string   `json:"videoFieldName"`  // 提交的视频表单名称
	VideoPathFormat string   `json:"videoPathFormat"` // 上传保存路径可以自定义保存路径和文件名格式
	VideoUrlPrefix  string   `json:"videoUrlPrefix"`  // 视频访问路径前缀
	VideoMaxSize    int      `json:"videoMaxSize"`    // 上传大小限制，单位B，默认100MB
	VideoAllowFiles []string `json:"videoAllowFiles"` // 上传视频格式显示

	// 上传文件配置
	FileActionName string   `json:"fileActionName"` // controller里执行上传视频的action名称
	FileFieldName  string   `json:"fileFieldName"`  // 提交的文件表单名称
	FilePathFormat string   `json:"filePathFormat"` // 上传保存路径可以自定义保存路径和文件名格式
	FileUrlPrefix  string   `json:"fileUrlPrefix"`  // 文件访问路径前缀
	FileMaxSize    int      `json:"fileMaxSize"`    // 上传大小限制，单位B，默认50MB
	FileAllowFiles []string `json:"fileAllowFiles"` // 上传文件格式显示

	// 列出指定目录下的图片
	ImageManagerActionName  string   `json:"imageManagerActionName"`  // 执行图片管理的action名称
	ImageManagerListPath    string   `json:"imageManagerListPath"`    // 指定要列出图片的目录
	ImageManagerListSize    int      `json:"imageManagerListSize"`    // 每次列出文件数量
	ImageManagerUrlPrefix   string   `json:"imageManagerUrlPrefix"`   // 图片访问路径前缀
	ImageManagerInsertAlign string   `json:"imageManagerInsertAlign"` // 插入的图片浮动方式
	ImageManagerAllowFiles  []string `json:"imageManagerAllowFiles"`  // 列出的文件类型

	// 列出指定目录下的文件
	FileManagerActionName string   `json:"fileManagerActionName"` //执行文件管理的action名称
	FileManagerListPath   string   `json:"fileManagerListPath"`   // 指定要列出文件的目录
	FileManagerUrlPrefix  string   `json:"fileManagerUrlPrefix"`  // 文件访问路径前缀
	FileManagerListSize   int      `json:"fileManagerListSize"`   // 每次列出文件数量
	FileManagerAllowFiles []string `json:"fileManagerAllowFiles"` // 列出的文件类型
}

type upload_return struct {
	Name     string `json:"name"`
	Original string `json:"original"`
	Size     string `json:"size"`
	State    string `json:"state"`
	Type     string `json:"Type"`
	Url      string `json:"url"`
}

//上传配置文件
var UploadConfig upload_config

//上传文件返回结果
var UploadReturn upload_return

func init() {

	UploadConfig.ImageActionName = "uploadimage"
	UploadConfig.ImageFieldName = "upfile" // 提交的图片表单名称
	UploadConfig.ImageMaxSize = 2048000    // 上传大小限制，单位B
	ImageAllowFiles := []string{".png", ".jpg", ".jpeg", ".gif", ".bmp"}
	UploadConfig.ImageAllowFiles = ImageAllowFiles // 上传图片格式显示

	UploadConfig.ImageCompressEnable = true // 是否压缩图片默认是true
	UploadConfig.ImageCompressBorder = 1600 // 图片压缩最长边限制
	UploadConfig.ImageInsertAlign = "none"  // 插入的图片浮动方式
	UploadConfig.ImageUrlPrefix = ""        // 图片访问路径前缀
	UploadConfig.ImagePathFormat = "/upload/image/{yyyy}{mm}{dd}/{time}{rand:6}"

	// 涂鸦图片上传配置项
	UploadConfig.ScrawlActionName = "uploadscrawl"                                // 执行上传涂鸦的action名称
	UploadConfig.ScrawlFieldName = "upfile"                                       // 提交的图片表单名称
	UploadConfig.ScrawlPathFormat = "/upload/image/{yyyy}{mm}{dd}/{time}{rand:6}" // 上传保存路径可以自定义保存路径和文件名格式
	UploadConfig.ScrawlMaxSize = 2048000                                          // 上传大小限制，单位B
	UploadConfig.ScrawlUrlPrefix = ""                                             // 图片访问路径前缀
	UploadConfig.ScrawlInsertAlign = "none"

	// 截图工具上传
	UploadConfig.SnapscreenActionName = "uploadimage"                                 // 执行上传截图的action名称
	UploadConfig.SnapscreenPathFormat = "/upload/image/{yyyy}{mm}{dd}/{time}{rand:6}" // 上传保存路径可以自定义保存路径和文件名格式
	UploadConfig.SnapscreenUrlPrefix = ""                                             // 图片访问路径前缀
	UploadConfig.SnapscreenInsertAlign = "none"                                       // 插入的图片浮动方式

	// 抓取远程图片配置
	CatcherLocalDomain := []string{"127.0.0.1", "localhost", "img.baidu.com"}
	UploadConfig.CatcherLocalDomain = CatcherLocalDomain
	UploadConfig.CatcherActionName = "catchimage"                                  // 执行抓取远程图片的action名称
	UploadConfig.CatcherFieldName = "source"                                       // 提交的图片列表表单名称
	UploadConfig.CatcherPathFormat = "/upload/image/{yyyy}{mm}{dd}/{time}{rand:6}" // 上传保存路径可以自定义保存路径和文件名格式
	UploadConfig.CatcherUrlPrefix = ""                                             // 图片访问路径前缀
	UploadConfig.CatcherMaxSize = 2048000                                          // 上传大小限制，单位B
	CatcherAllowFiles := []string{".png", ".jpg", ".jpeg", ".gif", ".bmp"}
	UploadConfig.CatcherAllowFiles = CatcherAllowFiles // 抓取图片格式显示

	// 上传视频配置
	UploadConfig.VideoActionName = "uploadvideo"                                 // 执行上传视频的action名称
	UploadConfig.VideoFieldName = "upfile"                                       // 提交的视频表单名称
	UploadConfig.VideoPathFormat = "/upload/image/{yyyy}{mm}{dd}/{time}{rand:6}" // 上传保存路径可以自定义保存路径和文件名格式
	UploadConfig.VideoUrlPrefix = ""                                             // 视频访问路径前缀
	UploadConfig.VideoMaxSize = 102400000                                        // 上传大小限制，单位B，默认100MB
	VideoAllowFiles := []string{".flv", ".swf", ".mkv", ".avi", ".rm", ".rmvb", ".mpeg", ".mpg", ".ogg", ".ogv", ".mov", ".wmv", ".mp4", ".webm", ".mp3", ".wav", ".mid"}
	UploadConfig.VideoAllowFiles = VideoAllowFiles // 上传视频格式显示

	// 上传文件配置
	UploadConfig.FileActionName = "uploadfile"                                  // controller里执行上传视频的action名称
	UploadConfig.FileFieldName = "upfile"                                       // 提交的文件表单名称
	UploadConfig.FilePathFormat = "/upload/image/{yyyy}{mm}{dd}/{time}{rand:6}" // 上传保存路径可以自定义保存路径和文件名格式
	UploadConfig.FileUrlPrefix = ""                                             // 文件访问路径前缀
	UploadConfig.FileMaxSize = 51200000                                         // 上传大小限制，单位B，默认50MB
	FileAllowFiles := []string{".png", ".jpg", ".jpeg", ".gif", ".bmp", ".flv", ".swf", ".mkv", ".avi", ".rm", ".rmvb", ".mpeg", ".mpg", ".ogg", ".ogv", ".mov", ".wmv", ".mp4", ".webm", ".mp3", ".wav", ".mid", ".rar", ".zip", ".tar", ".gz", ".7z", ".bz2", ".cab", ".iso", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx", ".pdf", ".txt", ".md", ".xml"}
	UploadConfig.FileAllowFiles = FileAllowFiles // 上传文件格式显示

	// 列出指定目录下的图片
	UploadConfig.ImageManagerActionName = "listimage" // 执行图片管理的action名称
	UploadConfig.ImageManagerListPath = "/img/list"   // 指定要列出图片的目录
	UploadConfig.ImageManagerListSize = 20            // 每次列出文件数量
	UploadConfig.ImageManagerUrlPrefix = ""           // 图片访问路径前缀
	UploadConfig.ImageManagerInsertAlign = "none"     // 插入的图片浮动方式
	ImageManagerAllowFiles := []string{".png", ".jpg", ".jpeg", ".gif", ".bmp"}
	UploadConfig.ImageManagerAllowFiles = ImageManagerAllowFiles // 列出的文件类型

	// 列出指定目录下的文件
	UploadConfig.FileManagerActionName = "listfile"   //执行文件管理的action名称
	UploadConfig.FileManagerListPath = "/upload/list" // 指定要列出文件的目录
	UploadConfig.FileManagerUrlPrefix = ""            // 文件访问路径前缀
	UploadConfig.FileManagerListSize = 20             // 每次列出文件数量
	FileManagerAllowFiles := []string{".png", ".jpg", ".jpeg", ".gif", ".bmp", ".flv", ".swf", ".mkv", ".avi", ".rm", ".rmvb", ".mpeg", ".mpg", ".ogg", ".ogv", ".mov", ".wmv", ".mp4", ".webm", ".mp3", ".wav", ".mid", ".rar", ".zip", ".tar", ".gz", ".7z", ".bz2", ".cab", ".iso", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx", ".pdf", ".txt", ".md", ".xml"}
	UploadConfig.FileManagerAllowFiles = FileManagerAllowFiles

}

**Comment by Phinome** [comment]
欢迎按http://ueditor.baidu.com/website/thirdproject.html 整理成一个插件，提一个 pull request。
