### ISSUE TITLE
求HTTPS版本的UEDITOR

### ISSUE THREAD

**Issue by maodei** [fex-team/ueditor#3166]
我的网站全站已经升级成HTTPS， CMS后台用的是百度的Ueditor, 但是里面的表情插件引用的表情还是 http 开头的，导致生成的页面不是纯 https 的。

这个如何解决？

有https版本的 ueditor 吗？

**Comment by Phinome** [comment]
既然你已经用上 https 了，你可以把 UEditor 的静态资源都放到你的服务器上。
