### ISSUE TITLE
UEditor 编辑器自动过滤一下HTML标签  这个怎么解决啊

### ISSUE THREAD

**Issue by lenyi** [fex-team/ueditor#3168]
UEditor 编辑器自动过滤一下HTML标签  这个怎么解决啊，切换到html代码方式，把HTML 标签放在里面被过滤了，有谁知道这个怎么解决吗？？？

**Comment by MoonRaito** [comment]
ueditor.config.js

	// xss过滤白名单 名单来源: https://raw.githubusercontent.com/leizongmin/js-xss/master/lib/default.js
	,whitList: {
添加
