### ISSUE TITLE
SyntaxHighlighter插件有问题？

### ISSUE THREAD

**Issue by wolf8210137** [fex-team/ueditor#3173]
UE V1.4.3.1，使用代码高亮功能，提交后再打开，所有代码变成一行，是什么原因？

已排除了服务端保存的原因。是否有人遇过？

**Comment by HaddyYang** [comment]
SyntaxHighlighter将代码解析成table标签，你看看是否对table加了样式处理。
我没用这个插件，用prettify.py处理代码高亮，可看看这个链接http://yshblog.com/blog/91
