### ISSUE TITLE
下载UM版本UEditor报403错误

### ISSUE THREAD

**Issue by taoye518** [fex-team/ueditor#3178]
http://ueditor.baidu.com/website/download.html#mini

这个链接下载UM版本的所有utf-8编码资源包都提示403 Forbidden

好像没有看到可以上传图片的地方，所以上传不了截图。

**Comment by 16S110Rainmaker** [comment]
相同的问题。
![image](https://cloud.githubusercontent.com/assets/16821826/20865015/3d5eafbc-ba41-11e6-9d19-a501d03b7947.png)
