### ISSUE TITLE
后台jsp引入uedtior.all. js报错

### ISSUE THREAD

**Issue by moya25** [fex-team/ueditor#318]
editor.ui.getDom('elementpath').innerHTML = '<div class="edui-editor-breadcrumb">' + editor.getLang("elementPathTip") + ':</div>';
加载界面时，这里报未知的运行时错误。。请问这是什么问题

**Comment by ylhssn** [comment]
我也碰见这个问题了，在ie8、chrome中测这个问题，在chrome中正常，在IE8中就会报错，改了好久，才发现将ueditor在table中进行引用，就不会报错了…坑货啊
