### ISSUE TITLE
如何设置不显示多图上传中的在线管理和图片搜索功能 对于新版Ueditor 1.4.3 

### ISSUE THREAD

**Issue by mig29sk** [fex-team/ueditor#3180]
请问要如何如何设置不显示多图上传中的在线管理和图片搜索功能 对于新版Ueditor 1.4.3 。
我按照网上的方法 试着 在image.html 删除

<span class="tab" data-content-id="online"><var id="lang_tab_online"></var></span>
<span class="tab" data-content-id="search"><var id="lang_tab_search"></var></span>
和删除头部  var 定义的两个相关变量 ，但是 chrome google浏览器下仍然会显示出来 ，FF 和IE不会显示 

请问要如何解决 ？ 谢谢各位

**Comment by Phinome** [comment]
你不要这两个功能，在dialog/image.html 里删除相应的 html，以及 dialog/image.js 中删除相关的代码，不就解决了？
