### ISSUE TITLE
这种注册多个自定义按钮的方式太坑了吧？

### ISSUE THREAD

**Issue by wangjingjing** [fex-team/ueditor#3186]
`UE.registerUI('bold italic redo undo underline strikethrough', function(editor, uiName) {......});`

注册自定义的按钮是不是必须用预先定义好的bold、italic、redo等关键字？我没理解错吧。

那不就是覆盖这些按钮本来的触发函数吗？我要是想自定义20个按钮，必须先把预定义好的按钮中找出20个不能用的按钮名字给我自己用，哪位大神想出的这种方式？太服了

**Comment by herrdu** [comment]
这个问题没有解决直接关闭了吗？
