### ISSUE TITLE
修改文档可以保存，修改图片边框就无法保存

### ISSUE THREAD

**Issue by rearchris** [fex-team/ueditor#3194]
直接先代码：

```
<form  method="post" action="abc.php" >
    <script type="text/plain" name="content" id="content" style="width:690px;"></script>
</form>
```

```
<script type="text/javascript" src="library/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="library/ueditor/ueditor.all.js"></script>
<script type="text/javascript">
	var ue= UE.getEditor('content');		
	ue.ready(function(){
		ue.setContent('{$resModify.content}');
		var html = ue.getContent();
		var txt = ue.getContentTxt();
	});
</script>
```

以上代码是我修改用Ueditor编写文章，但我发现文章的内容可以修改并保存成功，但修改图片的边框就无法保存边框的大小比如：1px;无法保存成功。
是代码哪儿出错了吗？请指教，谢谢！

**Comment by rearchris** [comment]
还有，如果我给某个词添加超链接，也是无法保存的。这是为什么？当然我是在转成HTML格式的时候添加的。

**Comment by Phinome** [comment]
UEditor 只能监控到 `contentChange` 而触发自动保存，至于你所说的图片边框以及添加超链接而发生的修改，其实质是属性的变更，因此不会触发 `contentChange` ，没有触发 `contentChange` 自然也不会调用`Save` 方法。如果你需要监听属性的变更，你可以自行实现，API 可以参考：[UEditor API 文档](http://ueditor.baidu.com/doc/#UE.Editor)

**Comment by rearchris** [comment]
不好意思，我没找到哪个可以监听属性变更。因为我想更改很多属性，希望能监听所有属性的变更，如果有变更了就能保存。
非常感谢。

**Comment by Phinome** [comment]
我之前的意思就是 UEditor 不提供这种属性级别的变更监听，给你的 API 文档，是让你在实现属性监听的时候，用到 UEditor 内部方法时可以参考，减少你寻找 UEditor 内部方法的时间。编辑器自身是不会实现这种属性的变更事件的。
