### ISSUE TITLE
希望有wordpress的3.9以上版本插件

### ISSUE THREAD

**Issue by ookangzheng** [fex-team/ueditor#367]
目前wordpress 3.9以上的插件都有問題，請官方弄一個吧~~ 相信wordpress建站的站長都很多~~

**Comment by noinlijin** [comment]
wordpress需要一个ueditor，自带的实在太难用了

**Comment by wugr** [comment]
为什么抄送我？

Sent from Huawei Mobile

李进Noin <notifications@github.com>编写：

**Comment by MrCrutch** [comment]
跪求啊！！！希望能有个wordpress版的，一直安装不了，wordpress4.4.1

**Comment by wugr** [comment]
？

Sent from Huawei Mobile

"Mr.Crutch" <notifications@github.com>编写：

**Comment by Phinome** [comment]
没有人力支持了，看开源社区的力量了。
