### ISSUE TITLE
 关于批量图片抓去的问题

### ISSUE THREAD

**Issue by yunwu2014** [fex-team/ueditor#404]
getContent 内容时获取的批量抓去的图片没有替换掉原来的地址

**Comment by KevinPan** [comment]
有没有配置项，能在使用 "图片搜索“ 的时候不要请求服务器再替换成相对路径的src吗？我就直接用外部链接这样行吗？

还有一个问题就是：能不能在多图上传的功能里加一个配置项，现在多图上传有4个tab，很多时候我可能只想用其中的几个（比如我有时候只想用“插入图片”1个tab），如果能配置这个就好了！

**Comment by KevinPan** [comment]
我的第一个问题在看其他issue的时候找到答案了：关闭远程抓取: 在 ueditor.config.js 里配置 catchRemoteImageEnable: false

这个配置项默认没有出现在ueditor.conig.js文件中
