### ISSUE TITLE
图片上传正常但是在线管理里面显示不正常 jsp

### ISSUE THREAD

**Issue by encoreyi** [fex-team/ueditor#412]
多图中本地上传能把图片上传至服务器
在config.json中配置了列出指定目录下的图片imageManagerListPath
在在线管理中能列出图片但都是灰的查看了该页面中图片的指向
src="C:/work/mywork2014/.metadata/.me_tcat7/webapps/test/ueditor/jsp/upload/image/20140611/1402484245400045382.jpg?noCache=hwbeinjz" _src="C:/work/mywork2014/.metadata/.me_tcat7/webapps/test/ueditor/jsp/upload/image/20140611/1402484245400045382.jpg"
为什么这种情况 ？
版本1.4.3 jsp utf-8
求解 谢谢！

**Comment by fzw-gf** [comment]
请问yuanxinz，你所谓的1.1.3jar包是什么呀？
