### ISSUE TITLE
求高手指点 为什么自定义请求地址后 上传图片 $_GET['action'] 总是没有 uploadimage

### ISSUE THREAD

**Issue by whiteButterfly** [fex-team/ueditor#424]
不知怎么回事  我用的最新的版本 按照文档说的  自定义请求地址 如下
UE.Editor.prototype._bkGetActionUrl = UE.Editor.prototype.getActionUrl;
    UE.Editor.prototype.getActionUrl = function(action) {
    if (action == 'uploadimage' || action == 'uploadscrawl' || action == 'uploadimage') {
        
        return 'http://ci.zhangbinbin:8080/test/upload1‘;
    } else if (action == 'uploadvideo') {
        return 'http://ci.zhangbinbin:8080/test/upload1';
    } else {
        return this._bkGetActionUrl.call(this, action);
    }
}
但是 在http://ci.zhangbinbin:8080/test/upload1中根本就没法获得 $_GET['action'] 准确的说就没有这个参数 所以每次都是  请求地址出错  请问是什么原因呢 而且我在 ueditor.config.js中也配置了  serverUrl: "http://ci.zhangbinbin:8080/test/upload1"  也不行啊   求指教了 ，要是能帮忙解决问题了请吃饭啊！！！！

**Comment by litao8976** [comment]
我的也是啊，后台拿不到图片，怎么办？
