### ISSUE TITLE
继续求助啊  怎么去掉 Img返回的参数

### ISSUE THREAD

**Issue by yinfuluantan** [fex-team/ueditor#429]
单张图片上传后返回的参数
<.i.m.g s.rc="/xxx/xxx.jpg"   title="xxxx.jpg" alt="xxxxxx.jpg"/>  
怎么能把这里的 titile参数去掉  返回的是系统自动生成的文件名！毛用都没有！用户鼠标放上去也显示这个无用的东西！影响体验！ 求去除！ 求指教！  1.4以前都可以直接在PHP文件里定义 现在找不到了！
//其实返回的alt里带的文件格式也是多余的吧！

**Comment by haimingguan** [comment]
请问一下，如何得到上传图片的返回的这段html。simpleupload 插件上传了一个图片，我想监听这个动作。
