### ISSUE TITLE
asp版本图片上传本地可以，但是上传服务器提示错误

### ISSUE THREAD

**Issue by huoshanzuoer** [fex-team/ueditor#490]
本地上传一点问题也没有，但是上传到服务器之后，上传图片提示   服务器返回出错  ，很纳闷的问题，看了服务器的权限，IIS_USER权限也都加上了，我qq912021230，希望尽快给回复，谢谢

**Comment by wangwuxia** [comment]
去掉asp/Uploader.Class.asp顶部的所有注释行。
