### ISSUE TITLE
dede 整合最新版本编辑器后，发现栏目内容 内容里内容无法保存

### ISSUE THREAD

**Issue by zzh111** [fex-team/ueditor#499]
dede 整合最新版本编辑器后，发现栏目内容 内容里内容无法保存，，内容页功能正常。

**Comment by itrainfox** [comment]
可以在dedecms后台的目录下的templates中修改，分别修改，catalog_edit.htm、catalog_add.htm，这两个文件中，

function checkSubmit()
{
   if(document.form1.typename.value==""){
          alert("栏目名称不能为空！");
          document.form1.typename.focus();
          return false;
     }
     document.form1.content.value = document.getElementById("ueditor_0").contentWindow.document.body.innerHTML;//添加此行即可，其中的ueditor_0根据你自己的情况来修改。
     return true;
}

**Comment by 54programmer** [comment]
楼上的，你这样操作能用？我的不行哎！！！
