### ISSUE TITLE
ASP版本上传图片本地测试成功，上传到服务器出错

### ISSUE THREAD

**Issue by lucklucky** [fex-team/ueditor#501]
用的是UEditor1.4.2版本的，本地分别用localhost和本机IP192.168.0.121测试都成功的，但是上传到虚拟主机后使用多图上传功能，点击开始上传后，提示“图片上传成功”，但图片上面显示“服务器返回出错”，而且FTP查看，图片实际也没有上传。就像这样的错误：http://zhidao.baidu.com/link?url=plLryUyECK5Kq8lg8tyygydOrhpdBPIq0OhOm6zNZX4DpYJMfEtYDT4X8VC1xITb3RbgnBYweiTmaxlJIiQhx2PCl-RYNcXKvCKuUJi-TbG，求帮助。

**Comment by wangwuxia** [comment]
这个很诡异的问题，去掉asp/Uploader.Class.asp顶部的所有注释行。我就这样解决的，大家可以试试
