### ISSUE TITLE
ueditor1.4.3 jsp上传图片、文件报"未找到上传数据"

### ISSUE THREAD

**Issue by kitikousei** [fex-team/ueditor#827]
上传功能都报这个错。debug跟进时，request中能获得上传文件的路径，临时存放路径，文件大小等相关信息。但是在执行时
FileItemIterator iterator = upload.getItemIterator(request);

			while (iterator.hasNext()) {
				fileStream = iterator.next();

				if (!fileStream.isFormField())
					break;
				fileStream = null;
	}
文件迭代中无信息！

**Comment by LittleDouBi** [comment]
不知道这个问题解决了没有，我也遇到了，很忧伤啊

**Comment by penghao122** [comment]
这个问题解决了。ueditor自事的fileupload组件与spring的有冲突。
将那个类BinaryUploader 重写就可以了

try {	

			String savePath = (String) conf.get("savePath");
			String originFileName = UUID.randomUUID().toString() + ".jpg";
			String suffix = FileType.getSuffixByFilename(originFileName);

			originFileName = originFileName.substring(0,originFileName.length() - suffix.length());
			savePath = savePath + suffix;

			long maxSize = ((Long) conf.get("maxSize")).longValue();

			if (!validType(suffix, (String[]) conf.get("allowFiles"))) {
				return new BaseState(false, AppInfo.NOT_ALLOW_FILE_TYPE);
			}

			savePath = PathFormat.parse(savePath, originFileName);

			String physicalPath = (String) conf.get("rootPath") + savePath;


			File f = new File(request.getParameter("upfile"));
			byte[] buf = FileUtils.readFileToByteArray(f);			
			InputStream is = new ByteArrayInputStream(buf);
			State storageState = StorageManager.saveFileByInputStream(is,physicalPath, maxSize);
			is.close();
					

			if (storageState.isSuccess()) {
				storageState.putInfo("url", PathFormat.format(savePath));
				storageState.putInfo("type", suffix);
				storageState.putInfo("original", originFileName + suffix);
			}

			return storageState;
		}catch (Exception e) {
			e.printStackTrace();
			System.out.println(e.getMessage());
		}
		return new BaseState(false, AppInfo.IO_ERR
如解决不了可以邮件给我 penghao122@126.com

**Comment by penghao122** [comment]
你可以根据需要修改我的代码

**Comment by sxpujs** [comment]
由于ueditor与java集成的方式是使用controller.jsp，不支持Spring MVC。需要使用Spring 
我写了一个可以使用的版本，需要修改ueditor.jar的源代码，请参考下面的链接。
第一个工程是修改了ueditor的源代码的程序。第二个工作是与spring boot集成来测试ueditor的样例代码。
https://github.com/sxpujs/ueditor
https://github.com/sxpujs/spring-boot-ueditor

**Comment by jamesMuWB** [comment]
重写一下BinaryUploader.save方法：

	public static final State save(HttpServletRequest request,
			Map<String, Object> conf) {
		
		try {
			MultipartHttpServletRequest multipartRequest = (MultipartHttpServletRequest) request;
			MultipartFile multipartFile = multipartRequest.getFile(conf.get("fieldName").toString());

	        String savePath = (String) conf.get("savePath");
	        String originFileName = multipartFile.getOriginalFilename();
	        String suffix = FileType.getSuffixByFilename(originFileName);

	        originFileName = originFileName.substring(0,originFileName.length() - suffix.length());
	        savePath = savePath + suffix;

	        long maxSize = ((Long) conf.get("maxSize")).longValue();

	        if (!validType(suffix, (String[]) conf.get("allowFiles"))) {
	            return new BaseState(false, AppInfo.NOT_ALLOW_FILE_TYPE);
	        }

	        savePath = PathFormat.parse(savePath, originFileName);

	        State storageState = StorageManager.saveFileByInputStream(multipartFile.getInputStream(),savePath, maxSize);


	        if (storageState.isSuccess()) {
	            storageState.putInfo("url", PathFormat.format(savePath));
	            storageState.putInfo("type", suffix);
	            storageState.putInfo("original", originFileName + suffix);
	        }

	        return storageState;
	        
	    }catch (Exception e) {
	        e.printStackTrace();
	        System.out.println(e.getMessage());
	    }
		return new BaseState(false, AppInfo.IO_ERROR);
	}

**Comment by Actinian** [comment]
有可能是被过滤器 拦截了，在web.xml里将 
 <filter>
    <filter-name>struts2</filter-name>
    <filter-class>org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter</filter-class>
  </filter>
注释掉,启用   
 <filter>
    <filter-name>struts2</filter-name>
    <filter-class>项目包.ueditor.filter.ImageUploadFilter</filter-class>
  </filter>
由于赶项目，先这么解决有更好的解决办法希望指出  谢谢
