### ISSUE TITLE
上传视频-出现http请求错误

### ISSUE THREAD

**Issue by xiezhushu** [fex-team/ueditor#929]
上传图片和文件都没有问题，上传视频走到100%之后出现http请求错误，不知是何原因呢？

服务器：Win2003企业版 + ASP.NET4.0

![image](https://cloud.githubusercontent.com/assets/8121309/3534999/be261d32-07f7-11e4-9aaf-b734dccc0ad9.png)

本地VS2013调试上传视频没有问题。

**Comment by edibea** [comment]
请问上传文件如何解决的呢？我是在配置上传文件时出现了http请求错误

**Comment by coopoo** [comment]
视频超出大小，也会提示HTTP请求失败

**Comment by edibea** [comment]
已经把HTTP请求失败解决了，发现是路径的设置除了问题。多加了一个"/"，谢谢啦
